import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {work,root,read,save,sharp,ffmpeg,probe} from './author.mjs';
const require=createRequire(import.meta.url),{RGBLuminanceSource,HybridBinarizer,BinaryBitmap,MultiFormatReader,DecodeHintType,BarcodeFormat}=require('@zxing/library');
async function decode(file){const {data,info}=await sharp(file).greyscale().raw().toBuffer({resolveWithObject:true});const source=new RGBLuminanceSource(new Uint8ClampedArray(data),info.width,info.height);return new MultiFormatReader().decode(new BinaryBitmap(new HybridBinarizer(source)),new Map([[DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.QR_CODE]],[DecodeHintType.TRY_HARDER,true]])).getText();}
const reports=await read(path.join(work,'evidence/render.json'));assert.equal(reports.length,13);const checks=[];
for(const r of reports){const mp4=r.assets.find(a=>a.path.endsWith('.mp4')),file=path.join(root,mp4.path),details=await probe(file),v=details.streams.find(s=>s.codec_type==='video'),a=details.streams.find(s=>s.codec_type==='audio');assert.equal(v.codec_name,'h264');assert.equal(a.codec_name,'aac');assert.equal(v.width,r.promo?1080:1920);assert.equal(v.height,r.promo?1920:1080);assert.equal(v.avg_frame_rate,'24/1');assert.ok(mp4.bytes<20*1024*1024);assert.ok(r.seconds>=(r.promo?30:60)&&r.seconds<=(r.promo?40:90));assert.equal(r.motion.length,6);
 const raw=await fs.readFile(file);assert.ok(raw.indexOf(Buffer.from('moov'))<raw.indexOf(Buffer.from('mdat')));for(const asset of r.assets){const bytes=await fs.readFile(path.join(root,asset.path));assert.equal(bytes.length,asset.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),asset.sha256);}
 const decoded=await ffmpeg(['-loglevel','info','-threads','2','-i',file,'-map','0:v:0','-map','0:a:0','-af','volumedetect','-f','null','-']);
 const meanDb=Number(decoded.stderr.match(/mean_volume: (-?[\d.]+) dB/)?.[1]),peakDb=Number(decoded.stderr.match(/max_volume: (-?[\d.]+) dB/)?.[1]);assert.ok(Number.isFinite(meanDb)&&meanDb>-40&&meanDb<0);assert.ok(Number.isFinite(peakDb)&&peakDb<=0);
 const audio=await read(path.join(work,'audio',`${r.locale}-${r.id}.json`));const captions=await fs.readFile(path.join(root,r.assets.find(a=>a.path.endsWith('.vtt')).path),'utf8');assert.ok(captions.startsWith('WEBVTT'));for(const s of audio.steps)assert.ok(captions.split(/\n\n/gu).filter(block=>block.includes('-->')).map(block=>block.split('\n').slice(1).join('')).join('').replace(/\s/gu,'').includes(s.body.replace(/\s/gu,'')));
 let moving=0;for(const [i,m] of r.motion.entries()){assert.ok(Math.hypot(m.mouse.start.x-m.mouse.end.x,m.mouse.start.y-m.mouse.end.y)>10);if(!r.promo){const c=m.sourceCrop,t=m.target,W=1776,H=700,zoom=1.28;const tx=(t.x+t.width/2)*W/c.width,ty=(t.y+t.height/2-c.y)*H/c.height,cx=Math.max(0,Math.min(W-W/zoom,tx-W/(2*zoom))),cy=Math.max(0,Math.min(H-H/zoom,ty-H/(2*zoom)));assert.ok(Math.abs(m.mouse.end.x-(72+(tx-cx)*zoom))<1);assert.ok(Math.abs(m.mouse.end.y-(185+(ty-cy)*zoom))<1);}
  const frames=[];for(const at of [.9,2.5]){const out=path.join(work,'evidence',`${r.locale}-${r.id}-${i}-mouse-${at}.png`);await ffmpeg(['-ss',String(audio.steps[i].at+at),'-i',file,'-frames:v','1',out]);frames.push(await sharp(out).extract({left:72,top:r.promo?565:185,width:r.promo?936:1776,height:r.promo?580:700}).raw().toBuffer());}assert.notEqual(createHash('sha256').update(frames[0]).digest('hex'),createHash('sha256').update(frames[1]).digest('hex'));moving++;
 }
 checks.push({locale:r.locale,id:r.id,seconds:Number(details.format.duration),bytes:mp4.bytes,decoded:true,meanDb,peakDb,movingSteps:moving,illustrativeTerminal:r.promo?null:r.motion[4].illustration});console.log(`Verified ${r.locale}/${r.id}`);
}
const qr=await decode(path.join(work,'wechat/二维码.png'));assert.equal(qr,'https://www.chinatech.in/toolbox/office');const promotion=reports.find(r=>r.promo),end=path.join(work,'evidence/promo-end.png');await ffmpeg(['-ss',String(promotion.seconds-2),'-i',path.join(root,promotion.assets.find(a=>a.path.endsWith('.mp4')).path),'-frames:v','1',end]);assert.equal(await decode(end),qr);assert.equal(await decode(path.join(work,'wechat/01-Office工具箱推广封面.jpg')),qr);
const contact=path.join(work,'evidence/preview-sheet.png'),poster=path.join(work,'evidence/zh-CN-install-poster.png'),it=path.join(work,'evidence/it-install-poster.png');const images=await Promise.all([poster,it,end].map(async(file,i)=>({input:await sharp(file).resize(i===2?360:960,i===2?640:540,{fit:'contain',background:'white'}).png().toBuffer(),left:i===2?1920:i*960,top:0})));await sharp({create:{width:2280,height:640,channels:4,background:'white'}}).composite(images).png().toFile(contact);
await save(path.join(work,'evidence/verification.json'),{status:'PASS',checkedAt:new Date().toISOString(),episodes:checks.length,websiteEpisodes:12,motionSteps:78,checks,qr,qrVerifiedIn:['original','actualVideoEnd','jpegCover'],terminalExecution:false});
