package in.chinatech.phoneassistant;
public final class GrantActivity extends android.app.Activity {
 @Override public void onCreate(android.os.Bundle state){super.onCreate(state);if(getIntent().getBooleanExtra("seed_contact",false))seedContact();android.net.Uri tree=android.provider.DocumentsContract.buildTreeDocumentUri("in.chinatech.phoneassistanttest.documents","root");for(String target:new String[]{"in.chinatech.phoneassistant","in.chinatech.phoneassistant.chinatech"}){try{grantUriPermission(target,tree,android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION|android.content.Intent.FLAG_GRANT_WRITE_URI_PERMISSION|android.content.Intent.FLAG_GRANT_PREFIX_URI_PERMISSION|android.content.Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);}catch(IllegalArgumentException missing){}}finish();}
 private void seedContact(){android.content.ContentResolver resolver=getContentResolver();android.content.ContentValues v=new android.content.ContentValues();v.putNull("account_type");v.putNull("account_name");android.net.Uri raw=resolver.insert(android.provider.ContactsContract.RawContacts.CONTENT_URI,v);long id=android.content.ContentUris.parseId(raw);
  data(id,"vnd.android.cursor.item/name",new String[]{"data1","data2","data3"},new String[]{"CT_SYNTHETIC_CHINATECH","Synthetic","ChinaTech"});
  data(id,"vnd.android.cursor.item/phone_v2",new String[]{"data1","data2"},new String[]{"+391234567890","3"});data(id,"vnd.android.cursor.item/email_v2",new String[]{"data1","data2"},new String[]{"synthetic@example.invalid","2"});data(id,"vnd.android.cursor.item/organization",new String[]{"data1","data4"},new String[]{"Synthetic Organization","Synthetic Role"});data(id,"vnd.android.cursor.item/postal-address_v2",new String[]{"data1","data4","data7","data10"},new String[]{"Synthetic Address","Synthetic Street","Synthetic City","Italy"});data(id,"vnd.android.cursor.item/note",new String[]{"data1"},new String[]{"Synthetic note only"});data(id,"vnd.android.cursor.item/contact_event",new String[]{"data1","data2"},new String[]{"2000-01-02","3"});
  android.graphics.Bitmap image=android.graphics.Bitmap.createBitmap(32,32,android.graphics.Bitmap.Config.ARGB_8888);image.eraseColor(0xff123456);java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();image.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);image.recycle();android.content.ContentValues photo=new android.content.ContentValues();photo.put("raw_contact_id",id);photo.put("mimetype","vnd.android.cursor.item/photo");photo.put("data15",out.toByteArray());resolver.insert(android.provider.ContactsContract.Data.CONTENT_URI,photo);
 }
 private void data(long id,String mime,String[] fields,String[] values){android.content.ContentValues v=new android.content.ContentValues();v.put("raw_contact_id",id);v.put("mimetype",mime);for(int i=0;i<fields.length;i++)v.put(fields[i],values[i]);getContentResolver().insert(android.provider.ContactsContract.Data.CONTENT_URI,v);}
}
