package in.chinatech.phoneassistant;
import android.app.*;
import android.content.*;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.*;
import android.provider.DocumentsContract;
import java.io.*;
import java.net.*;
import java.util.*;
/** Instrumentation lives exclusively in the separately signed test APK. No test entry in released APK. */
public final class RuntimeTests extends Instrumentation {
 private Bundle options;private TransferEngine engine;private Context target;private int checks;private String phase="begin";
 @Override public void onCreate(Bundle args){options=args;start();}
 private void require(boolean yes,String label){if(!yes)throw new AssertionError(label);checks++;}
 private void waitFor(java.util.concurrent.Callable<Boolean> test,long timeout,String label)throws Exception{long until=SystemClock.elapsedRealtime()+timeout;while(SystemClock.elapsedRealtime()<until){if(test.call())return;Thread.sleep(100);}throw new AssertionError(label+" status="+(engine==null?0:engine.status));}
 @Override public void onStart(){Bundle result=new Bundle();try{target=new BridgeContext(getTargetContext());if("tls".equals(options.getString("mode"))){phase="tls-local";tls(result);result.putInt("checks",checks);finish(Activity.RESULT_OK,result);return;}Intent i=new Intent().setClassName(target,"in.chinatech.phoneassistant.MainActivity").putExtra("receiving",false).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);runOnMainSync(()->target.startActivity(i));Thread.sleep(1000);engine=TransferEngine.get(target);target.startActivity(new Intent().setClassName("in.chinatech.phoneassistanttest","in.chinatech.phoneassistant.GrantActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitFor(()->{try(android.database.Cursor c=target.getContentResolver().query(DocumentsContract.buildDocumentUriUsingTree(tree(),"root"),new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID},null,null,null)){return c!=null&&c.moveToFirst();}catch(SecurityException unavailable){return false;}},10000,"synthetic folder grant");target.getContentResolver().takePersistableUriPermission(tree(),Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);String mode=options.getString("mode","receiver");phase="resources";require(target.getString(R.string.app_name).contains("ChinaTech"),"private resource");phase="qr";for(int qrTest=0;qrTest<12;qrTest++){ProtocolCore.Pairing synthetic=new ProtocolCore.Pairing("gateway",24567,ProtocolCore.token(16),System.currentTimeMillis()+60000,ProtocolCore.random(32),ProtocolCore.hex(new byte[32]),"TEST-ONLY-SSID","test-only-password","wpa2");Bitmap qr=QrCodec.encode(synthetic.encode());require(QrCodec.decode(qr).equals(synthetic.encode()),"QR roundtrip");synthetic.erase();qr.recycle();}runOnMainSync(()->engine.stop());waitFor(()->!engine.isActive(),10000,"stop existing");if(mode.equals("receiver"))receiver(result);else if(mode.equals("fault"))faults(result);else if(mode.equals("camera"))camera(result);else if(mode.equals("entry"))entry(result);else if(mode.equals("selection"))selection(result);else if(mode.equals("gallery"))gallery(result);else if(mode.equals("contacts"))contacts(result);else if(mode.equals("scope"))scope(result);else sender(result);result.putInt("checks",checks);result.putString("phase",phase);finish(Activity.RESULT_OK,result);}catch(Throwable e){result.putString("failure",e.getClass().getSimpleName()+":"+e.getMessage()+(e.getCause()==null?"":" cause="+e.getCause().getClass().getSimpleName()+":"+e.getCause().getMessage()));result.putString("phase",phase);result.putInt("checks",checks);finish(Activity.RESULT_CANCELED,result);}}
 private android.widget.CheckBox findCheckbox(android.view.View view,String text){if(view instanceof android.widget.CheckBox&&((android.widget.CheckBox)view).getText().toString().contains(text))return (android.widget.CheckBox)view;if(view instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)view;for(int i=0;i<group.getChildCount();i++){android.widget.CheckBox found=findCheckbox(group.getChildAt(i),text);if(found!=null)return found;}}return null;}
 private void selection(Bundle result)throws Exception {
  phase="selection-ui";engine.store.clear();Uri source=DocumentsContract.createDocument(target.getContentResolver(),DocumentsContract.buildDocumentUriUsingTree(tree(),"root"),"text/plain","synthetic-select.txt");engine.store.add(source,"files","synthetic-select.txt","text/plain",0,true);TransferStore.Row row=engine.page("files",0).get(0);require(row.selected,"selected fixture");
  ActivityMonitor monitor=addMonitor("in.chinatech.phoneassistant.MainActivity",null,false);runOnMainSync(()->target.startActivity(new Intent(target,MainActivity.class).putExtra("receiving",false).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_MULTIPLE_TASK)));MainActivity activity=(MainActivity)monitor.waitForActivityWithTimeout(10000);require(activity!=null,"selection activity");Thread.sleep(100);android.view.View category=findButton(activity.getWindow().getDecorView(),target.getString(R.string.category_count,target.getString(R.string.category_files),1));require(category!=null,"file category visible");runOnMainSync(category::performClick);android.widget.CheckBox[] checkbox={null};runOnMainSync(()->{for(android.view.View root:android.view.inspector.WindowInspector.getGlobalWindowViews()){android.widget.CheckBox found=findCheckbox(root,"synthetic-select.txt");if(found!=null)checkbox[0]=found;}});require(checkbox[0]!=null&&checkbox[0].isChecked(),"actual category checkbox");
  java.lang.reflect.Field field=TransferEngine.class.getDeclaredField("tasks");field.setAccessible(true);java.util.concurrent.atomic.AtomicInteger busy=(java.util.concurrent.atomic.AtomicInteger)field.get(engine);busy.incrementAndGet();try{android.view.View[] none={null};runOnMainSync(()->{for(android.view.View root:android.view.inspector.WindowInspector.getGlobalWindowViews()){android.view.View found=findButton(root,target.getString(R.string.unselect_category));if(found!=null)none[0]=found;}});require(none[0]!=null,"actual category deselect button");runOnMainSync(none[0]::performClick);require(checkbox[0].isChecked()&&engine.page("files",0).get(0).selected,"busy category action leaves matching state");runOnMainSync(checkbox[0]::performClick);require(checkbox[0].isChecked(),"busy click visually rolled back");require(engine.page("files",0).get(0).selected,"busy click did not change snapshot");}finally{busy.decrementAndGet();}
  runOnMainSync(checkbox[0]::performClick);require(!checkbox[0].isChecked(),"idle click visibly deselects");require(!engine.page("files",0).get(0).selected&&engine.selectedCount()==0,"idle click persisted before transfer");android.view.View[] all={null};runOnMainSync(()->{for(android.view.View root:android.view.inspector.WindowInspector.getGlobalWindowViews()){android.view.View found=findButton(root,target.getString(R.string.select_category));if(found!=null)all[0]=found;}});require(all[0]!=null,"actual category select button");runOnMainSync(all[0]::performClick);waitFor(()->checkbox[0].isChecked()&&engine.page("files",0).get(0).selected,10000,"category callback reads committed selection");require(engine.selectedCount()==1,"bulk choice persisted before visible completion");removeMonitor(monitor);result.putBoolean("actualCheckboxMatchesSelection",true);result.putString("busyScope","production task counter injected to represent an in-flight bulk operation");phase="complete";
 }
 private void scope(Bundle result)throws Exception {
  phase="scope-recreation";ActivityMonitor monitor=addMonitor("in.chinatech.phoneassistant.MainActivity",null,false);runOnMainSync(()->target.startActivity(new Intent(target,MainActivity.class).putExtra("receiving",false).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_MULTIPLE_TASK)));MainActivity first=(MainActivity)monitor.waitForActivityWithTimeout(10000);require(first!=null,"activity available");java.lang.reflect.Field field=MainActivity.class.getDeclaredField("scanConsent");field.setAccessible(true);((ScanConsent)field.get(first)).request(new boolean[]{true,false,false});runOnMainSync(first::recreate);waitFor(()->monitor.getLastActivity()!=null&&monitor.getLastActivity()!=first,10000,"recreation event");MainActivity next=(MainActivity)monitor.getLastActivity();require(next!=null&&next!=first,"actual Activity recreated");boolean[] chosen=((ScanConsent)field.get(next)).consume();require(chosen!=null&&chosen[0]&&!chosen[1]&&!chosen[2],"selected scan scope preserved");require(((ScanConsent)field.get(next)).consume()==null,"callback cannot replay");removeMonitor(monitor);result.putBoolean("actualActivityScanScopeRecreation",true);phase="complete";
 }
 private byte[] imageBytes(int color)throws Exception {Bitmap image=Bitmap.createBitmap(64,64,Bitmap.Config.ARGB_8888);image.eraseColor(color);ByteArrayOutputStream out=new ByteArrayOutputStream();require(image.compress(Bitmap.CompressFormat.PNG,100,out),"synthetic PNG created");image.recycle();return out.toByteArray();}
 private boolean mediaExists(Uri uri)throws Exception {try(android.database.Cursor c=target.getContentResolver().query(uri,new String[]{android.provider.MediaStore.MediaColumns._ID},null,null,null)){return c!=null&&c.moveToFirst();}}
 private String mediaKey(ProtocolCore.Item item){return ProtocolCore.hex(item.hash)+":"+item.size+":"+item.mime;}
 private ProtocolCore.Item mediaSource(byte[] bytes,Uri directory)throws Exception {Uri parent=DocumentsContract.buildDocumentUriUsingTree(tree(),"root");Uri file=DocumentsContract.createDocument(target.getContentResolver(),parent,"image/png","synthetic-photo.png");try(OutputStream out=target.getContentResolver().openOutputStream(file,"w")){out.write(bytes);}ProtocolCore.Item item=new ProtocolCore.Item(ProtocolCore.token(16),"synthetic-photo.png","image/png",bytes.length,ProtocolCore.sha256(bytes));engine.store.received(ProtocolCore.token(16),item,file,directory);return item;}
 private void gallery(Bundle result)throws Exception {
  phase="gallery-create";Uri directory=tree().buildUpon().appendQueryParameter("synthetic-run",ProtocolCore.token(16)).build();runOnMainSync(()->engine.setDirectory(tree()));byte[] bytes=imageBytes(0xff000000|new java.util.Random().nextInt(0xffffff));ProtocolCore.Item one=mediaSource(bytes,directory);CancellationScope scope=new CancellationScope(Runnable::run,()->{});
  MediaImporter.Result first=new MediaImporter(target,scope).run(engine.store,directory,(n,k,f)->{});require(first.imported==1&&first.failed==0,"actual MediaStore image import");MediaImportStore journal=new MediaImportStore(target);Uri dest=journal.get(mediaKey(one)).dest;require(mediaExists(dest),"gallery row visible");try(android.database.Cursor c=target.getContentResolver().query(dest,new String[]{android.provider.MediaStore.MediaColumns.IS_PENDING},null,null,null)){require(c!=null&&c.moveToFirst()&&c.getInt(0)==0,"pending cleared only after verification");}
  MediaImporter.Result repeat=new MediaImporter(target,scope).run(engine.store,directory,(n,k,f)->{});require(repeat.imported==0&&repeat.skipped==1&&repeat.failed==0,"retry no duplicate copy");require(dest.equals(journal.get(mediaKey(one)).dest),"same gallery URI after retry");
  // A journal may still say pending after publication. Editing this public copy must never cause deletion.
  journal.put(mediaKey(one),dest,"pending");try(OutputStream out=target.getContentResolver().openOutputStream(dest,"w")){out.write(new byte[]{9,8,7});}
  MediaImporter.Result edited=new MediaImporter(target,scope).run(engine.store,directory,(n,k,f)->{});require(edited.failed==1&&edited.imported==0,"changed visible copy reports failure");require(mediaExists(dest),"changed public copy retained");
  phase="gallery-intent-recovery";byte[] next=imageBytes(0xff000000|new java.util.Random().nextInt(0xffffff));ProtocolCore.Item two=mediaSource(next,directory);String name="CT-"+ProtocolCore.token(16)+"-synthetic-recovery.png";journal.intent(mediaKey(two),name);android.content.ContentValues values=new android.content.ContentValues();values.put(android.provider.MediaStore.MediaColumns.DISPLAY_NAME,name);values.put(android.provider.MediaStore.MediaColumns.MIME_TYPE,"image/png");values.put(android.provider.MediaStore.MediaColumns.RELATIVE_PATH,"Pictures/ChinaTech/");values.put(android.provider.MediaStore.MediaColumns.IS_PENDING,1);Uri interrupted=target.getContentResolver().insert(android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI,values);require(interrupted!=null,"fixture created between insert and URI journal");try(OutputStream out=target.getContentResolver().openOutputStream(interrupted,"w")){out.write(next);}
  MediaImporter.Result recovered=new MediaImporter(target,scope).run(engine.store,directory,(n,k,f)->{});result.putString("recoveryResult",recovered.imported+"/"+recovered.skipped+"/"+recovered.failed+" "+recovered.lastFailure);require(recovered.imported==0&&recovered.skipped==1&&recovered.failed==1,"creation intent recovered without another copy");require(interrupted.equals(journal.get(mediaKey(two)).dest),"creation intent resolves exact URI");require("published".equals(journal.get(mediaKey(two)).state),"recovered row committed");
  // Journal lives independently of the scan index and a newly constructed importer.
  journal.close();MediaImportStore reopened=new MediaImportStore(target);require(reopened.get(mediaKey(two)).dest.equals(interrupted),"journal persists across helper recreation");reopened.close();result.putBoolean("actualMediaStoreImportAndRecovery",true);result.putInt("galleryChecks",checks-12);phase="complete";
 }
 private void contacts(Bundle result)throws Exception {
  phase="contacts-seed";target.startActivity(new Intent().setClassName("in.chinatech.phoneassistanttest","in.chinatech.phoneassistant.GrantActivity").putExtra("seed_contact",true).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));
  waitFor(()->{try(android.database.Cursor c=target.getContentResolver().query(android.provider.ContactsContract.Data.CONTENT_URI,new String[]{"_id"},"mimetype=? AND data1=?",new String[]{"vnd.android.cursor.item/note","Synthetic note only"},null)){return c!=null&&c.moveToFirst();}},10000,"synthetic contact inserted by test-only writer");
  // Diagnostics inspect only the test writer's synthetic note contact; no contact values are logged.
  phase="contacts-provider-diagnostic";
  try(android.database.Cursor selected=target.getContentResolver().query(android.provider.ContactsContract.Data.CONTENT_URI,new String[]{"contact_id"},"mimetype=? AND data1=?",new String[]{"vnd.android.cursor.item/note","Synthetic note only"},null)){
   require(selected!=null&&selected.moveToFirst(),"synthetic contact selected");long id=selected.getLong(0);
   try(android.database.Cursor contact=target.getContentResolver().query(android.content.ContentUris.withAppendedId(android.provider.ContactsContract.Contacts.CONTENT_URI,id),new String[]{android.provider.ContactsContract.Contacts.LOOKUP_KEY},null,null,null)){
    require(contact!=null&&contact.moveToFirst(),"synthetic lookup available");
    Uri vcard=Uri.withAppendedPath(android.provider.ContactsContract.Contacts.CONTENT_VCARD_URI,contact.getString(0)).buildUpon().appendQueryParameter(android.provider.ContactsContract.Contacts.QUERY_PARAMETER_VCARD_NO_PHOTO,"false").build();
    CancellationScope directScope=new CancellationScope(Runnable::run,()->{});ByteArrayOutputStream raw=new ByteArrayOutputStream();
    try(InputStream input=ProviderIo.input(target.getContentResolver(),vcard,directScope)){byte[] buffer=new byte[16384];int n;while((n=input.read(buffer))!=-1){if(raw.size()+n>1024*1024)throw new IOException("SYNTHETIC_DIAGNOSTIC_LIMIT");raw.write(buffer,0,n);}}
    byte[] exported=raw.toByteArray();String structure=new String(exported,java.nio.charset.StandardCharsets.UTF_8);result.putInt("standardVcardBytes",exported.length);result.putBoolean("startsWithBegin",structure.startsWith("BEGIN:VCARD"));result.putBoolean("endsWithEnd",structure.trim().endsWith("END:VCARD"));result.putBoolean("version21",structure.contains("VERSION:2.1"));result.putBoolean("version30",structure.contains("VERSION:3.0"));result.putBoolean("version40",structure.contains("VERSION:4.0"));result.putInt("cardCount",structure.split("BEGIN:VCARD",-1).length-1);
    try{ContactExport.copy(new ByteArrayInputStream(exported),new ByteArrayOutputStream(),()->{});result.putBoolean("framingValid",true);}catch(Exception e){result.putString("framingFailure",e.getClass().getSimpleName()+":"+(e.getMessage()!=null&&e.getMessage().matches("[A-Z_]{1,80}")?e.getMessage():"UNSPECIFIED"));}
   }
  }
  phase="contacts-scan";
  CancellationScope scope=new CancellationScope(Runnable::run,()->{});TransferStore store=new TransferStore(target);store.clear();PhoneScanner scanner=new PhoneScanner(target,store,scope,(n,f)->{},false,true,false);scanner.scan();require(scanner.failures==0,"actual standard contact export without fallback");java.util.List<TransferStore.Row> rows=store.page("contacts",0);require(rows.size()==1,"contact archive indexed");TransferStore.Row row=rows.get(0);ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(InputStream in=ProviderIo.input(target.getContentResolver(),row.uri,scope)){byte[] buffer=new byte[16384];int n;while((n=in.read(buffer))>=0)bytes.write(buffer,0,n);}String text=new String(bytes.toByteArray(),java.nio.charset.StandardCharsets.UTF_8);for(String field:new String[]{"BEGIN:VCARD","TEL","EMAIL","ORG","ADR","NOTE","BDAY","PHOTO","END:VCARD"})require(text.contains(field),"system vCard preserves "+field);
  android.content.Context denied=new android.content.ContextWrapper(target){public int checkSelfPermission(String permission){return android.Manifest.permission.READ_CONTACTS.equals(permission)?android.content.pm.PackageManager.PERMISSION_DENIED:super.checkSelfPermission(permission);}};
  try{SourceAccess.check(denied,row);throw new AssertionError("revoked export sent");}catch(SecurityException expected){require(true,"cached export blocked under denied access policy");}
  SourceAccess.check(denied,new TransferStore.Row(row.n,row.uri,row.id,row.name,row.mime,row.size,row.hash,row.selected,"files"));require(true,"manual file category remains independent of Contacts permission");store.close();result.putBoolean("actualContactsProviderStandardVcard",true);result.putString("revocationScope","denied Context policy injection, not system permission revocation");phase="complete";
 }
 private void tls(Bundle result)throws Exception {SessionTls id=new SessionTls(System.currentTimeMillis()+600000);try(javax.net.ssl.SSLServerSocket server=(javax.net.ssl.SSLServerSocket)id.context.getServerSocketFactory().createServerSocket(0,1,InetAddress.getLoopbackAddress())){server.setSoTimeout(10000);java.util.concurrent.CompletableFuture<Boolean> remote=new java.util.concurrent.CompletableFuture<>();new Thread(()->{try(javax.net.ssl.SSLSocket peer=(javax.net.ssl.SSLSocket)server.accept()){peer.setSoTimeout(10000);peer.startHandshake();peer.getOutputStream().write(42);peer.getOutputStream().flush();remote.complete(true);}catch(Throwable e){result.putString("serverFailure",e.getClass().getSimpleName()+":"+e.getMessage()+(e.getCause()==null?"":" cause="+e.getCause().getClass().getSimpleName()+":"+e.getCause().getMessage()));remote.completeExceptionally(e);}}).start();try(javax.net.ssl.SSLSocket socket=(javax.net.ssl.SSLSocket)SessionTls.pinned(id.pin).getSocketFactory().createSocket(InetAddress.getLoopbackAddress(),server.getLocalPort())){socket.setSoTimeout(10000);socket.startHandshake();require(socket.getInputStream().read()==42,"actual AndroidKeyStore TLS pinned handshake");require(remote.get(10,java.util.concurrent.TimeUnit.SECONDS),"server handshake");result.putBoolean("pinnedAndroidTls",true);}catch(Exception clientError){try{remote.get(10,java.util.concurrent.TimeUnit.SECONDS);}catch(Exception ignored){}throw clientError;}}finally{id.close();}}
 private android.view.View findButton(android.view.View view,String text){if(view instanceof android.widget.Button&&((android.widget.Button)view).getText().toString().equals(text))return view;if(view instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)view;for(int i=0;i<group.getChildCount();i++){android.view.View found=findButton(group.getChildAt(i),text);if(found!=null)return found;}}return null;}
 private void entry(Bundle result)throws Exception{phase="launcher-entry";ActivityMonitor hostMonitor=addMonitor("in.chinatech.phoneassistant.LaunchActivity",null,false);Intent launch=target.getPackageManager().getLaunchIntentForPackage(target.getPackageName());require(launch!=null,"APK launcher intent");result.putString("launchComponent",launch.getComponent().flattenToShortString());runOnMainSync(()->target.startActivity(launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP)));Activity host=hostMonitor.waitForActivityWithTimeout(10000);require(host!=null,"standalone APK launcher started");Thread.sleep(500);android.view.View receive=findButton(host.getWindow().getDecorView(),target.getString(R.string.receiver_title));require(receive!=null&&receive.getVisibility()==android.view.View.VISIBLE&&receive.hasOnClickListeners(),"receive button visible");ActivityMonitor bridge=addMonitor("in.chinatech.phoneassistant.MainActivity",null,false);runOnMainSync(receive::performClick);Activity receiver=bridge.waitForActivityWithTimeout(10000);require(receiver!=null&&receiver.getIntent().getBooleanExtra("receiving",false),"receive click opens standalone assistant");runOnMainSync(()->engine.stop());waitFor(()->!engine.isActive(),15000,"entry cleanup");removeMonitor(bridge);removeMonitor(hostMonitor);result.putBoolean("standaloneLauncherReceiveRoute",true);phase="complete";}
 private void camera(Bundle result)throws Exception {phase="camera-frames";ActivityMonitor monitor=addMonitor("in.chinatech.phoneassistant.LiveQrActivity",null,false);runOnMainSync(()->target.startActivity(new Intent().setClassName(target,"in.chinatech.phoneassistant.LiveQrActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)));Activity scanner=monitor.waitForActivityWithTimeout(10000);require(scanner!=null,"camera activity");java.lang.reflect.Field frames=LiveQrActivity.class.getDeclaredField("processedFrames");frames.setAccessible(true);waitFor(()->frames.getLong(scanner)>=3,15000,"real Camera2 YUV frames");result.putLong("cameraFramesRead",frames.getLong(scanner));runOnMainSync(scanner::finish);removeMonitor(monitor);phase="complete";}
 private int destinationCount()throws Exception {Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(tree(),"root");try(android.database.Cursor c=target.getContentResolver().query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID},null,null,null)){return c==null?0:c.getCount();}}
 private void faults(Bundle result)throws Exception {
  phase="manual-hotspot-qr";runOnMainSync(()->{engine.setDirectory(tree());engine.configureManualHotspot("TEST-ONLY-MANUAL","test-only-password");});waitFor(()->engine.serverPair!=null,15000,"manual hotspot QR without local MAC");require(engine.wifi.manuallyConfigured(),"manual mode explicit");require(QrCodec.decode(QrCodec.encode(engine.serverPair.encode())).equals(engine.serverPair.encode()),"manual hotspot QR decode");runOnMainSync(()->engine.stop());waitFor(()->!engine.isActive(),10000,"manual mode close");
  phase="lost-complete";int before=destinationCount();runOnMainSync(()->{engine.useRouter();engine.prepareReceiver();});waitFor(()->engine.serverPair!=null,15000,"fault receiver");ProtocolCore.Pairing pair=engine.serverPair;String task=ProtocolCore.token(16),object=ProtocolCore.token(16);byte[] nonce=ProtocolCore.random(32),bytes=new byte[65537];Arrays.fill(bytes,(byte)17);ProtocolCore.Item item=new ProtocolCore.Item(object,"synthetic-fault.bin","application/octet-stream",bytes.length,ProtocolCore.sha256(bytes));
  Thread approve=new Thread(()->{while(engine.isActive()){if(engine.pendingConfirmation!=null)runOnMainSync(()->engine.decide(true));try{Thread.sleep(50);}catch(InterruptedException stop){return;}}});approve.start();
  try(FaultPeer p=new FaultPeer(pair,task,nonce)){require(!p.object(item,bytes),"first object written");p.complete(item);}
  Thread.sleep(200);require(engine.isActive(),"lost COMPLETE retains listener");require(destinationCount()==before+1,"one saved object");
  phase="bad-finish";try(FaultPeer p=new FaultPeer(pair,task,nonce)){require(p.object(item,bytes),"reconnect verifies and skips saved object");p.complete(item);p.readComplete(item);ProtocolCore.writeFinish(p.out,2,ProtocolCore.sha256(bytes));}Thread.sleep(200);require(engine.isActive(),"wrong FINISH count refused");require(destinationCount()==before+1,"replay no duplicate");
  phase="finish-recover";try(FaultPeer p=new FaultPeer(pair,task,nonce)){require(p.object(item,bytes),"second replay skips");p.complete(item);byte[] digest=p.readComplete(item);ProtocolCore.writeFinish(p.out,1,digest);}waitFor(()->engine.status==R.string.receiver_complete,10000,"valid FINISH completes");waitFor(()->!engine.isActive(),10000,"completion cleanup");require(destinationCount()==before+1,"exactly one fixture after recovery");
  phase="lost-finish";runOnMainSync(()->{engine.useRouter();engine.prepareReceiver();});waitFor(()->engine.serverPair!=null,15000,"new fault session");pair=engine.serverPair;task=ProtocolCore.token(16);nonce=ProtocolCore.random(32);Thread approve2=new Thread(()->{while(engine.isActive()){if(engine.pendingConfirmation!=null)runOnMainSync(()->engine.decide(true));try{Thread.sleep(50);}catch(InterruptedException stop){return;}}});approve2.start();try(FaultPeer p=new FaultPeer(pair,task,nonce)){require(!p.object(item,bytes),"new task writes distinct destination");p.complete(item);p.readComplete(item);}Thread.sleep(200);require(engine.isActive(),"lost FINISH retains confirmed saved files");java.lang.reflect.Field grace=TransferEngine.class.getDeclaredField("completedGrace");grace.setAccessible(true);grace.setLong(engine,SystemClock.elapsedRealtime()+500);waitFor(()->engine.status==R.string.receiver_complete_unconfirmed,5000,"scaled final grace expires honestly");require(destinationCount()==before+2,"unconfirmed final receipt keeps saved file");result.putBoolean("nativeFinalRecovery",true);result.putString("graceTest","500ms scaled deadline; production is 180000ms");phase="complete";
 }
 private final class FaultPeer implements AutoCloseable {
  final javax.net.ssl.SSLSocket socket;final DataInputStream in;final DataOutputStream out;
  FaultPeer(ProtocolCore.Pairing pair,String task,byte[] nonce)throws Exception {socket=(javax.net.ssl.SSLSocket)SessionTls.pinned(pair.pin).getSocketFactory().createSocket(pair.host,pair.port);socket.setSoTimeout(10000);socket.startHandshake();in=new DataInputStream(new BufferedInputStream(socket.getInputStream()));out=new DataOutputStream(new BufferedOutputStream(socket.getOutputStream()));ProtocolCore.writeString(out,pair.magic(),10);ProtocolCore.writeString(out,pair.session,30);out.write(pair.secret);out.write(nonce);ProtocolCore.writeString(out,task,30);out.writeLong(1);out.flush();require("APPROVED".equals(ProtocolCore.readString(in,20)),"fault peer approved");out.writeBoolean(true);out.flush();}
  boolean object(ProtocolCore.Item item,byte[] bytes)throws Exception {ProtocolCore.writeString(out,"OBJECT",20);ProtocolCore.writeItem(out,item);String action=ProtocolCore.readVerifiedControl(in,()->{});boolean skipped=action.equals("SKIP");require(skipped||action.equals("WRITE"),"object disposition");if(!skipped){require(ProtocolCore.equal(ChunkTransport.send(new ByteArrayInputStream(bytes),out,in,item.size,()->{}),item.hash),"chunk hash");out.write(item.hash);out.flush();}require("SAVED".equals(ProtocolCore.readVerifiedControl(in,()->{})),"saved frame");byte[] hash=new byte[32];in.readFully(hash);require(ProtocolCore.equal(hash,item.hash),"disk hash acknowledgement");return skipped;}
  void complete(ProtocolCore.Item item)throws Exception {ManifestDigest digest=new ManifestDigest();digest.add(item);ProtocolCore.writeString(out,"COMPLETE",20);out.writeLong(1);out.writeLong(item.size);out.write(digest.finish());out.flush();}
  byte[] readComplete(ProtocolCore.Item item)throws Exception {require("COMPLETE".equals(ProtocolCore.readString(in,20))&&in.readLong()==1,"final complete count");byte[] actual=new byte[32];in.readFully(actual);ManifestDigest expected=new ManifestDigest();expected.add(item);require(ProtocolCore.equal(actual,expected.finish()),"final digest");return actual;}
  public void close()throws IOException{socket.close();}
 }
 private Uri tree(){return DocumentsContract.buildTreeDocumentUri("in.chinatech.phoneassistanttest.documents","root");}
 private boolean wifiReady(){android.net.ConnectivityManager manager=target.getSystemService(android.net.ConnectivityManager.class);for(android.net.Network n:manager.getAllNetworks()){android.net.NetworkCapabilities caps=manager.getNetworkCapabilities(n);android.net.LinkProperties p=manager.getLinkProperties(n);if(caps!=null&&p!=null&&caps.hasTransport(android.net.NetworkCapabilities.TRANSPORT_WIFI)&&!caps.hasTransport(android.net.NetworkCapabilities.TRANSPORT_VPN))for(android.net.LinkAddress address:p.getLinkAddresses())try{ProtocolCore.validateHost(address.getAddress().getHostAddress());return true;}catch(IOException invalid){}}return false;}
 private void receiver(Bundle result)throws Exception {
  phase="hotspot";runOnMainSync(()->{engine.setDirectory(tree());engine.createHotspot();});waitFor(()->engine.serverPair!=null||engine.status==R.string.hotspot_failed||engine.status==R.string.permission_denied||engine.status==R.string.transfer_failed||engine.status==R.string.service_start_failed,40000,"hotspot bounded result");boolean hotspot=engine.serverPair!=null&&!engine.serverPair.ssid.isEmpty();result.putBoolean("hotspotQrGenerated",hotspot);result.putInt("hotspotStatus",engine.status);result.putString("hotspotFailure",engine.wifi.lastFailure);if(hotspot){require(engine.serverPair.host.equals("gateway"),"no local MAC or guessed IP");require(QrCodec.decode(QrCodec.encode(engine.serverPair.encode())).equals(engine.serverPair.encode()),"actual hotspot QR");}
  runOnMainSync(()->engine.stop());waitFor(()->!engine.isActive(),10000,"hotspot cleanup");phase="lan-listen";waitFor(this::wifiReady,30000,"emulator Wi-Fi route restored after hotspot stop");runOnMainSync(()->{engine.useRouter();engine.prepareReceiver();});waitFor(()->engine.serverPair!=null,15000,"LAN receiver QR");ProtocolCore.Pairing pair=engine.serverPair;require(pair.ssid.isEmpty(),"LAN pairing");require(!pair.host.equals("gateway"),"LAN actual address");
  // Pairing is carried only over an adb-forwarded, loopback-only transient test socket, never in logs.
  try(ServerSocket ipc=new ServerSocket(10081,5,InetAddress.getLoopbackAddress())){ipc.setSoTimeout(30000);boolean handed=false;while(!handed){try(Socket host=ipc.accept()){host.setSoTimeout(10000);DataInputStream request=new DataInputStream(host.getInputStream());if(!"PAIR".equals(ProtocolCore.readString(request,20)))continue;DataOutputStream out=new DataOutputStream(host.getOutputStream());ProtocolCore.writeString(out,pair.encode(),512);out.flush();handed=true;}catch(IOException retry){}}}
  phase="receive";long until=SystemClock.elapsedRealtime()+180000;while(SystemClock.elapsedRealtime()<until){if(engine.pendingConfirmation!=null)runOnMainSync(()->engine.decide(true));if(engine.status==R.string.receiver_complete)break;if(!engine.isActive())throw new AssertionError("receiver ended status="+engine.status);Thread.sleep(100);}require(engine.status==R.string.receiver_complete,"receiver completion");require(engine.receivedCount==3,"all three saved");result.putLong("receivedCount",engine.receivedCount);result.putLong("residualCount",engine.residualCount());require(engine.residualCount()==0,"no unfinished fixture");phase="complete";
 }
 private void sender(Bundle result)throws Exception {
  phase="source";String code=options.getString("code");require(code!=null,"pair supplied in memory");Uri parent=DocumentsContract.buildDocumentUriUsingTree(tree(),"root");int[] sizes={0,65537,2097153};List<Uri> sources=new ArrayList<>();for(int n:sizes){Uri uri=DocumentsContract.createDocument(target.getContentResolver(),parent,"application/octet-stream","synthetic-"+n+".bin");try(OutputStream out=target.getContentResolver().openOutputStream(uri,"w")){byte[] b=new byte[65536];for(int k=0;k<b.length;k++)b[k]=(byte)(k*31+7);int left=n;while(left>0){int count=Math.min(left,b.length);out.write(b,0,count);left-=count;}}sources.add(uri);}runOnMainSync(()->engine.clearSelection());waitFor(()->!engine.isActive(),10000,"clear source");runOnMainSync(()->engine.addUris(sources));waitFor(()->!engine.isActive(),10000,"index source");require(engine.selectedCount()==3,"selected scope");phase="send";runOnMainSync(()->engine.send(code));long until=SystemClock.elapsedRealtime()+180000;while(SystemClock.elapsedRealtime()<until){if(engine.pendingConfirmation!=null)runOnMainSync(()->engine.decide(true));if(engine.status==R.string.sender_complete)break;if(!engine.isActive())throw new AssertionError("sender ended status="+engine.status+" diagnostic="+engine.diagnostic);Thread.sleep(100);}require(engine.status==R.string.sender_complete,"sender saved hash acknowledgments");result.putLong("selectedCount",engine.selectedCount());result.putLong("fixtureBytes",(long)sizes[0]+sizes[1]+sizes[2]);phase="complete";
 }
}
