import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{randomUUID,createHash,createDecipheriv}from'node:crypto';import postgres from'postgres';
const f=JSON.parse(readFileSync('.local/office-desktop/fixture.private.json')),base=f.origin,admin=f.users.find(x=>x.role==='admin'),other=f.users.find(x=>x.role==='other');if(base!=='http://127.0.0.1:3162')throw Error('Local fixture required');
const c=JSON.parse(readFileSync('.local/backend/connection.private.json'));for(const k of ['DB_URL','APP_DATABASE_URL']){const u=new URL(c[k]);if(u.hostname!=='127.0.0.1'||u.port!=='55422')throw Error('Local DB required');}
const sql=postgres(c.DB_URL,{max:3,prepare:false}),runtime=postgres(c.APP_DATABASE_URL,{max:1,prepare:false});const checks=[];const pass=name=>{checks.push(name);console.log('PASS '+name);};
async function call(path,{user,method='GET',body,headers={}}={}){const response=await fetch(base+path,{method,headers:{...(user?{Cookie:user.cookies.map(x=>x.name+'='+x.value).join('; ')}:{}),...(body?{'Content-Type':'application/json'}:{}),...(user&&body?{Origin:base,'X-CT-Account-ID':user.id,'X-CT-Session-ID':user.sessionId}:{}),...headers},body:body?JSON.stringify(body):undefined});return{status:response.status,headers:response.headers,data:await response.json()};}
const adminPath='/api/account/toolbox/office-desktop',sessionPath='/api/toolbox/office-desktop/session',packagePath='/api/toolbox/office-desktop/package';
try{
 for(const user of [undefined,other])assert.equal((await call(adminPath,{user})).status,user?403:401);pass('anonymous and unrelated actual Auth users cannot manage desktop keys');
 const draft={requestId:randomUUID(),label:'Local desktop test',expiresAt:new Date(Date.now()+86400000).toISOString(),maxDevices:1,actions:['install','activate','uninstall','reinstall']};
 for(const headers of [{Origin:'https://foreign.invalid'},{'X-CT-Session-ID':randomUUID()},{'X-CT-Account-ID':other.id}])assert.ok([403,409].includes((await call(adminPath,{user:admin,method:'POST',body:draft,headers})).status));
 const created=await call(adminPath,{user:admin,method:'POST',body:draft});assert.equal(created.status,200,JSON.stringify(created.data));const key=created.data.key;f.licenseId=created.data.license.id;f.key=key;writeFileSync('.local/office-desktop/fixture.private.json',JSON.stringify(f),{mode:0o600});
 const replay=await call(adminPath,{user:admin,method:'POST',body:draft});assert.equal(replay.status,200);assert.equal(replay.data.key,key);assert.equal((await call(adminPath,{user:admin,method:'POST',body:{...draft,label:'changed'}})).status,409);pass('same-origin, actual account/session binding, idempotent creation and conflicting receipt checks');
 const list=await call(adminPath,{user:admin});assert.equal(list.status,200);assert.equal(list.data.total,1);assert.equal(JSON.stringify(list.data).includes(key),false);assert.equal(JSON.stringify(list.data).includes('key_hash'),false);assert.match(list.headers.get('cache-control'),/no-store/);pass('bounded administrator list excludes key material and disables caching');
 const installationId=randomUUID();const opening={key,installationId,language:'zh-CN'};
 assert.equal((await call(sessionPath,{method:'POST',body:{...opening,key:'CTO-invalid'}})).status,403);assert.equal((await call(sessionPath+'?key=bad',{method:'POST',body:opening})).status,400);assert.equal((await call(sessionPath,{method:'POST',body:opening,headers:{Origin:'https://foreign.invalid'}})).status,403);
 const race=await Promise.all([call(sessionPath,{method:'POST',body:opening}),call(sessionPath,{method:'POST',body:{...opening,installationId:randomUUID()}})]);assert.deepEqual(race.map(x=>x.status).sort(),[200,403]);const index=race[0].status===200?0:1;
 let session=await call(sessionPath,{method:'POST',body:opening});let activeId=installationId;if(index!==0){const [d]=await sql`select installation_id from chinatech_v2_private.office_desktop_devices where license_id=${f.licenseId}`;activeId=d.installation_id;session=await call(sessionPath,{method:'POST',body:{...opening,installationId:activeId}});}assert.equal(session.status,200);pass('concurrent first registration enforces device limit with a real database lock');
 const authorization={Authorization:'Bearer '+session.data.sessionToken,'X-CT-Installation-ID':activeId};const job={requestId:randomUUID(),action:'install'};
 assert.equal((await call(packagePath,{method:'POST',body:job,headers:{...authorization,'X-CT-Installation-ID':randomUUID()}})).status,401);
 const packageResult=await call(packagePath,{method:'POST',body:job,headers:authorization});assert.equal(packageResult.status,200);const p=packageResult.data;const aes=createDecipheriv('aes-256-gcm',createHash('sha256').update('chinatech-office-desktop:payload:v1\0'+session.data.sessionToken).digest(),Buffer.from(p.nonce,'base64'));aes.setAuthTag(Buffer.from(p.tag,'base64'));aes.setAAD(Buffer.from(JSON.stringify([p.v,p.action,p.version,p.digest,p.expiresAt,p.jobId])));const plaintext=Buffer.concat([aes.update(Buffer.from(p.ciphertext,'base64')),aes.final()]);assert.deepEqual(plaintext,readFileSync('server-assets/office-desktop/runner.ps1.txt'));
 const again=await call(packagePath,{method:'POST',body:job,headers:authorization});assert.equal(again.status,200);assert.equal(again.data.expiresAt,p.expiresAt);assert.notEqual(again.data.nonce,p.nonce);assert.equal((await call(packagePath,{method:'POST',body:{...job,action:'uninstall'},headers:authorization})).status,409);pass('authenticated encrypted job download verifies bytes, binding and retry semantics');
 const disable={licenseId:f.licenseId,enabled:false,expectedRevision:'1',requestId:randomUUID()};assert.equal((await call(adminPath,{user:admin,method:'PATCH',body:disable})).status,200);assert.equal((await call(adminPath,{user:admin,method:'PATCH',body:disable})).status,200);assert.equal((await call(sessionPath,{method:'POST',body:{...opening,installationId:activeId}})).status,403);assert.equal((await call(packagePath,{method:'POST',body:{...job,requestId:randomUUID()},headers:authorization})).status,403);
 assert.equal((await call(adminPath,{user:admin,method:'PATCH',body:{...disable,enabled:true,expectedRevision:'2',requestId:randomUUID()}})).status,200);assert.equal((await call(packagePath,{method:'POST',body:{...job,requestId:randomUUID()},headers:authorization})).status,401);pass('disable and re-enable reject old sessions and preserve device counts');
 const [unscoped]=await runtime`select count(*)::int n from chinatech_v2_private.office_desktop_licenses`;assert.equal(unscoped.n,0);
 await assert.rejects(runtime`update chinatech_v2_private.office_desktop_licenses set key_hash=${'b'.repeat(64)} where id=${f.licenseId}`,e=>e.code==='42501');pass('FORCE RLS hides unscoped rows and column grants forbid key alteration');
 session=await call(sessionPath,{method:'POST',body:{...opening,installationId:activeId}});const revoked={Authorization:'Bearer '+session.data.sessionToken,'X-CT-Installation-ID':activeId};await sql`update chinatech_v2_private.office_command_control set command_version=command_version+1 where admin_user_id=${admin.id}`;assert.equal((await call(packagePath,{method:'POST',body:{...job,requestId:randomUUID()},headers:revoked})).status,401);pass('global website control epoch invalidates outstanding desktop sessions');
 const [counts]=await sql`select count(*)::int n from chinatech_v2_private.office_desktop_devices where license_id=${f.licenseId}`;assert.equal(counts.n,1);
 writeFileSync('.local/office-desktop/proof/api-results.json',JSON.stringify({checks,count:checks.length,environment:'real local Supabase Auth / restricted PostgreSQL / Next.js',production:false,officeExecuted:false},null,2));
}finally{await sql.end();await runtime.end();}
