\set ON_ERROR_STOP on
begin;
select no_plan();
select synthetic_seed_item(n) from generate_series(71,75)n;
select is(synthetic_sales_call(71,'sale.create',10000)->>'status','paid_pending_pickup','paid-held correction fixture');
select is(synthetic_sales_call(72)->>'status','awaiting_payment','partial correction fixture');
select throws_ok($$insert into inventory_transactions(id,store_id,item_id,transaction_type,amount,method,actor_id,created_at) values(gen_random_uuid(),'10000000-0000-4000-8000-000000000001',synthetic_item_id(71),'refund',100,'cash','20000000-0000-4000-8000-000000000001',now())$$,'23514',null,'legacy refund cannot silently remove held-sale money');
select throws_ok($$insert into inventory_transactions(id,store_id,item_id,transaction_type,amount,method,actor_id,created_at) values(gen_random_uuid(),'10000000-0000-4000-8000-000000000001',synthetic_item_id(71),'adjustment',10,'cash','20000000-0000-4000-8000-000000000001',now())$$,'23514',null,'legacy adjustment cannot bypass new paid balance');
select is((select paid_cents from inventory_sale_orders where inventory_item_id=synthetic_item_id(71)),10000::bigint,'blocked legacy money path leaves aggregate balance intact');
select throws_ok($$update inventory_items set imei_check_status='unknown' where id=synthetic_item_id(72)$$,'23514',null,'ordinary product-save verification reset is refused after taking payment');
select throws_ok($$update inventory_items set serial_or_imei='CHANGED-SERIAL' where id=synthetic_item_id(72)$$,'23514',null,'sold/held item identity immutable');
select throws_ok($$update inventory_items set storage_capacity='Changed' where id=synthetic_item_id(72)$$,'23514',null,'sold/held specification immutable');
select throws_ok($$update inventory_stock_unit_identifiers set is_primary=false where stock_unit_id=(select stock_unit_id from inventory_sale_orders where inventory_item_id=synthetic_item_id(72))$$,'23514',null,'old product-update first identifier rewrite refused');
select throws_ok($$delete from inventory_stock_unit_identifiers where stock_unit_id=(select stock_unit_id from inventory_sale_orders where inventory_item_id=synthetic_item_id(72))$$,'23514',null,'held identifiers cannot be deleted');
select throws_ok($$update inventory_product_variants set specifications='{"network_variant":"cellular"}' where id=(select variant_id from inventory_stock_units where legacy_inventory_item_id=synthetic_item_id(72))$$,'23514',null,'shared variant specifications immutable for a held item');
select throws_ok($$update inventory_stock_units set variant_id=(select variant_id from inventory_stock_units where legacy_inventory_item_id=synthetic_item_id(73)) where legacy_inventory_item_id=synthetic_item_id(72)$$,'23514',null,'held item cannot swap identity via variant');
select lives_ok($$update inventory_product_variants set updated_at=clock_timestamp() where id=(select variant_id from inventory_stock_units where legacy_inventory_item_id=synthetic_item_id(72))$$,'unchanged variant upsert metadata remains compatible');
select lives_ok($$update inventory_items set notes='Synthetic holding note' where id=synthetic_item_id(72)$$,'unrelated holding note is not an identity change');
select lives_ok($$update inventory_items set imei_check_status='unknown',storage_capacity='512 GB' where id=synthetic_item_id(73)$$,'unsold item remains editable');
select lives_ok($$update inventory_stock_unit_identifiers set display_value='SYN-UNSOLD-UPDATED',normalized_value='SYNUNSOLDUPDATED' where stock_unit_id=(select id from inventory_stock_units where legacy_inventory_item_id=synthetic_item_id(73))$$,'unsold identifier edit remains allowed');
select lives_ok($$update inventory_product_variants set specifications='{"test":"unsold"}' where id=(select variant_id from inventory_stock_units where legacy_inventory_item_id=synthetic_item_id(73))$$,'unsold variant edit remains allowed');
select is(synthetic_sales_call(72,'payment.append',7000,true)->>'status','delivered','rejected ordinary edit does not strand held money or prevent legitimate delivery');
select is(synthetic_sales_call(71,'pickup.confirm')->>'status','delivered','blocked refund leaves valid paid pickup operational');
select is((select p->'product'->>'identifier' from jsonb_array_elements(repairdesk_inventory_sales_list('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000004','{"limit":100}')->'data'->'rows')p where p->>'inventory_item_id'=synthetic_item_id(72)::text),'•••• L-72','bulk list masks persisted sale snapshot identifier for inventory reader');
select is((select p->'product'->>'identifier' from jsonb_array_elements(repairdesk_inventory_sales_list('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','{"limit":100}')->'data'->'rows')p where p->>'inventory_item_id'=synthetic_item_id(74)::text),'•••• L-74','bulk list masks available item identifier even for owner');
select ok(not (repairdesk_inventory_sales_list('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000004','{"limit":100}')::text like '%SYN-SERIAL-72%'),'full identifier absent from entire inventory-reader list payload');
update store_settings set store_address='' where store_id='10000000-0000-4000-8000-000000000001';
select is(synthetic_sales_call(75)->>'code','completed','historical incomplete seller does not discard accepted financial facts');
update store_settings set store_address='Current repaired address' where store_id='10000000-0000-4000-8000-000000000001';
select is(repairdesk_inventory_sales_read('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','receipt',(select id from inventory_sale_orders where inventory_item_id=synthetic_item_id(75)),'sale')->>'code','historical_store_identity_incomplete','current repaired settings cannot legalize an empty historical seller');
select is((select store_snapshot->>'address' from inventory_sale_orders where inventory_item_id=synthetic_item_id(75)),'','historical empty seller snapshot was not overwritten');
select is((select paid_cents from inventory_sale_orders where inventory_item_id=synthetic_item_id(75)),3000::bigint,'blocked historic print preserves payment balance');
select is(repairdesk_inventory_sales_read('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','detail',(select id from inventory_sale_orders where inventory_item_id=synthetic_item_id(75)))->>'ok','true','financial detail still accessible when historical print is blocked');
select is((select provolatile::text from pg_proc where oid='repairdesk_inventory_sales_read(uuid,uuid,text,uuid,text,uuid,text)'::regprocedure),'s','detail and receipt use statement-consistent snapshot');
select * from finish();
rollback;
