\set ON_ERROR_STOP on
begin;
select no_plan();
select synthetic_seed_item(n,'phone') from generate_series(101,105)n;
update inventory_items set public_no='FILTER-'||right(id::text,3),brand='FilterAlpha',legacy_payload=coalesce(legacy_payload,'{}')||'{"location":"A"}'::jsonb where id in(select synthetic_item_id(n) from generate_series(101,105)n);
update inventory_items set category='tablet',brand='FilterBeta',legacy_payload=coalesce(legacy_payload,'{}')||'{"location":"B"}'::jsonb where id=synthetic_item_id(102);
update inventory_items set category='accessory' where id=synthetic_item_id(103);
update inventory_items set category='智能手机',legacy_payload=coalesce(legacy_payload,'{}')||'{"location":"B"}'::jsonb where id=synthetic_item_id(104);
update inventory_items set category='game_console' where id=synthetic_item_id(105);
insert into inventory_items select (jsonb_populate_record(null::inventory_items,to_jsonb(i)||jsonb_build_object('id',synthetic_item_id(106),'public_no','FILTER-106','store_id','10000000-0000-4000-8000-000000000002','legacy_payload','{}'::jsonb))).* from inventory_items i where id=synthetic_item_id(101);
insert into inventory_items select (jsonb_populate_record(null::inventory_items,to_jsonb(i)||jsonb_build_object('id',synthetic_item_id(107),'public_no','FILTER-BUYBACK','source_type','buyback','legacy_payload','{}'::jsonb))).* from inventory_items i where id=synthetic_item_id(101);
create function pg_temp.filtered(f jsonb) returns jsonb language sql as $$ select repairdesk_inventory_sales_list('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','{"search":"FILTER-","limit":30}'::jsonb||f); $$;
select is((pg_temp.filtered('{}')->'data'->>'total')::integer,5,'cross-store item excluded from total');
select is((pg_temp.filtered('{"categories":[],"statuses":[],"brands":[],"locations":[]}')->'data'->>'total')::integer,5,'empty filters preserve all');
select is((pg_temp.filtered('{"categories":["phone"]}')->'data'->>'total')::integer,2,'phone includes existing legacy alias');
select is((pg_temp.filtered('{"categories":["other"]}')->'data'->>'total')::integer,1,'unknown category remains other');
select is(pg_temp.filtered('{"categories":["other"]}')->'data'->'rows'->0->'product'->>'category','other','projection uses same normalized category');
select is((pg_temp.filtered('{"categories":["phone"],"brands":["FilterAlpha"],"locations":["A"],"statuses":["in_stock"]}')->'data'->>'total')::integer,1,'combined filters intersect on same base');
select is((pg_temp.filtered('{"categories":["tablet"],"brands":["FilterAlpha"]}')->'data'->>'total')::integer,0,'zero matches stays zero');
select is(pg_temp.filtered('{"categories":["tablet"],"brands":["FilterAlpha"]}')->'data'->'counts','{"all":0,"available":0,"awaiting_payment":0,"paid_pending_pickup":0,"delivered":0}'::jsonb,'zero counts complete');
select is(jsonb_array_length(pg_temp.filtered('{"categories":["phone"],"limit":1}')->'data'->'rows'),1,'pagination bounded');
select is((pg_temp.filtered('{"categories":["phone"],"limit":1}')->'data'->'counts'->>'all')::integer,2,'counts remain before pagination');
select is((pg_temp.filtered('{"queue":"available","categories":["phone"],"offset":1,"limit":1}')->'data'->>'total')::integer,2,'selected queue total before paging');
select is(pg_temp.filtered('{"categories":"phone"}')->>'code','invalid_request','non-array category rejected');
select is(pg_temp.filtered('{"categories":["bad"]}')->>'code','invalid_request','unknown filter enum rejected');
select is(pg_temp.filtered('{"statuses":["intake"]}')->>'code','invalid_request','raw status cannot bypass display enum');
select is(pg_temp.filtered('{"brands":[null]}')->>'code','invalid_request','non-string brand rejected');
select is(pg_temp.filtered('{"locations":[""]}')->>'code','invalid_request','empty location rejected');
select is(pg_temp.filtered('{"categories":["phone","phone","phone","phone","phone","phone"]}')->>'code','invalid_request','array bound enforced in DB');
select is((pg_temp.filtered('{"search":"FILTER-BUYBACK"}')->'data'->'counts'->>'all')::integer,0,'product master list excludes buyback from both rows and counts');
select * from finish();
rollback;
