import type { InventorySalesLanguage } from "../model/contracts";

const messages = {
  legacyReserved: ["Riservato · storico", "Reserved · legacy", "已留货 · 历史记录"],
  removed: ["Rimosso", "Removed", "已移除"],
  returned: ["Reso", "Returned", "已退回"],
  currentIdentity: [
    "Completa i dati del negozio attuale prima di stampare.",
    "Complete the current store details before printing.",
    "打印前请补齐当前店铺资料。",
  ],
  identifier: ["Identificativo dispositivo", "Device identifier", "设备标识"],
  projection: [
    "Verifica la scheda originale con il responsabile.",
    "Ask the manager to verify the original inventory record.",
    "请店铺负责人核对原库存记录。",
  ],
  title: ["Vendita", "Sale", "商品售卖"],
  available: ["In magazzino", "In stock", "待售 / 在库"],
  awaiting_payment: ["Acconto / rate", "Deposit / instalments", "定金分期留货"],
  paid_pending_pickup: ["Pagato · da ritirare", "Paid · awaiting pickup", "付清待交付"],
  delivered: ["Consegnato", "Delivered", "已交付"],
  all: ["Tutti", "All", "全部"],
  sell: ["Vendi / ricevi acconto", "Sell / take deposit", "售卖 / 收定金"],
  collect: ["Aggiungi pagamento", "Add payment", "继续收款"],
  pickup: ["Conferma consegna", "Confirm delivery", "确认交付"],
  inspect: ["Controlli pre-vendita", "Pre-sale checks", "售前检查"],
  prepare: ["Rendi disponibile", "Mark ready for sale", "标记待售"],
  customer: ["Cliente", "Customer", "客户"],
  createCustomer: ["Crea e seleziona cliente", "Create and select customer", "创建并选择客户"],
  customerRequired: [
    "Seleziona prima un cliente verificato.",
    "Select a verified customer first.",
    "请先明确选择客户。",
  ],
  sharedPhone: [
    "Confermo che è un altro cliente con lo stesso numero.",
    "This is a different customer sharing this number.",
    "确认这是共用手机号的另一位客户。",
  ],
  price: ["Prezzo totale (€)", "Total price (€)", "总售价 (€)"],
  amount: ["Questo pagamento (€)", "This payment (€)", "本次收款 (€)"],
  paid: ["Incassato", "Received", "已收"],
  balance: ["Da incassare", "Balance due", "待收余款"],
  date: ["Data e ora · Roma", "Date and time · Rome", "日期时间 · 罗马"],
  method: ["Modalità", "Payment method", "收款方式"],
  note: ["Nota del pagamento", "Payment note", "收款备注"],
  hold: ["Conserva in negozio", "Keep in store", "收款后留店"],
  deliverNow: ["Incassa e consegna", "Collect and deliver", "收款并交付"],
  deliveryNote: [
    "Confermo la consegna effettiva. La garanzia inizia ora.",
    "Confirm actual handover. Warranty begins on delivery.",
    "确认商品实际交给客户，保修从交付起算。",
  ],
  heldNote: [
    "Il prodotto resta in negozio. La garanzia non è iniziata.",
    "The product stays in store. Warranty has not started.",
    "商品仍留店，保修尚未开始。",
  ],
  used: ["Prodotto usato", "Used product", "二手商品"],
  warranty: ["Garanzia", "Warranty", "保修期限"],
  months24: ["24 mesi", "24 months", "24 个月"],
  months12: ["12 mesi · solo usato", "12 months · used only", "12 个月 · 仅二手"],
  consent: [
    "Il cliente ha espressamente accettato 12 mesi per questo prodotto usato.",
    "The customer expressly agreed to 12 months for this used product.",
    "客户已明确同意本二手商品缩短至 12 个月。",
  ],
  save: ["Conferma", "Confirm", "确认保存"],
  cancel: ["Chiudi", "Close", "关闭"],
  pending: ["Salvataggio…", "Saving…", "正在保存…"],
  retry: ["Riprova", "Retry", "重试"],
  refresh: ["Aggiorna e verifica", "Refresh and review", "刷新并核对"],
  loading: ["Caricamento…", "Loading…", "正在读取…"],
  error: [
    "Impossibile completare. Riprova con gli stessi dati; non duplicare il pagamento.",
    "Could not complete. Retry the same details; do not duplicate the payment.",
    "暂未确认结果。请保留相同资料重试，勿重复登记收款。",
  ],
  conflict: [
    "I dati sono cambiati. Aggiorna e verifica importi e stato prima di confermare.",
    "The record changed. Refresh and review amounts and status before confirming.",
    "资料已变化。请刷新核对金额和状态后再确认。",
  ],
  overpayment: [
    "Importo positivo, massimo il saldo residuo.",
    "Enter a positive amount no greater than the balance.",
    "收款必须大于零且不能超过余款。",
  ],
  invalidDate: [
    "Verifica data e ora di Roma, senza date future.",
    "Check the Rome date and time; future dates are not allowed.",
    "请核对罗马日期时间，不能登记未来时间。",
  ],
  blocked: [
    "Completa i controlli richiesti prima della vendita o consegna.",
    "Complete required checks before selling or delivering.",
    "请先完成售前检查，再售卖或交付。",
  ],
  permission: [
    "Operazione non autorizzata per questo account.",
    "Your account cannot perform this action.",
    "当前账号无权执行此操作。",
  ],
  dormant: [
    "Vendite non abilitate. L'inventario resta consultabile.",
    "Sales is disabled. Inventory remains readable.",
    "售卖功能尚未启用，库存仍可查看。",
  ],
  legacy: [
    "Scheda storica senza unità: sola lettura.",
    "Historical record without a stock unit: read only.",
    "历史记录缺少库存单元，仅可查看。",
  ],
  occupied: [
    "Vendita registrata: identità e controlli del dispositivo sono bloccati.",
    "A sale is recorded: device identity and checks are locked.",
    "已登记收款，设备身份、规格及检测状态已锁定。",
  ],
  workflowOff: [
    "Controlli non abilitati. Rivolgiti al responsabile del negozio.",
    "Inspection workflow is disabled. Contact the store manager.",
    "检测流程未启用，请联系店铺负责人。",
  ],
  imei_check_status: [
    "IMEI / numero seriale verificato",
    "IMEI / serial verified",
    "IMEI / SN 核验",
  ],
  activation_lock_status: ["Blocco account rimosso", "Account lock removed", "账号锁已关闭"],
  data_wipe_status: ["Dati cancellati", "Data wiped", "资料已清除"],
  functional_grade: ["Funzionalità", "Functionality", "功能检测"],
  cosmetic_grade: ["Condizioni estetiche", "Cosmetic condition", "外观等级"],
  unknown: ["Non verificato", "Not checked", "未检查"],
  pass: ["Superato", "Passed", "通过"],
  fail: ["Non superato", "Failed", "未通过"],
  new: ["Nuovo", "New", "全新"],
  mint: ["Come nuovo", "Like new", "准新"],
  good: ["Buono", "Good", "良好"],
  fair: ["Discreto", "Fair", "一般"],
  poor: ["Usurato", "Poor", "较差"],
  cash: ["Contanti", "Cash", "现金"],
  card: ["Carta", "Card", "银行卡"],
  bancomat: ["Bancomat", "Debit card", "借记卡"],
  transfer: ["Bonifico", "Transfer", "转账"],
  other: ["Altro", "Other", "其他"],
  sale: ["Documento di vendita", "Sales document", "销售凭证"],
  payment: ["Ricevuta di pagamento", "Payment receipt", "收款凭证"],
  warrantyDoc: ["Certificato di garanzia", "Warranty certificate", "保修凭证"],
  history: ["Pagamenti registrati", "Payment history", "分笔收款记录"],
  historical: [
    "I dati del venditore salvati all'epoca sono incompleti. Il responsabile deve verificare i documenti originali; modificare le impostazioni attuali non ripara questo documento.",
    "The saved seller details are incomplete. Ask the manager to verify original records; current settings cannot repair this historical document.",
    "销售时的卖方资料不完整，请店铺负责人核对原始单据；修改当前设置不能修复这份历史凭证。",
  ],
  settings: ["Apri impostazioni", "Open settings", "打开设置"],
  printLanguage: [
    "Lingua predefinita documenti di vendita",
    "Default sales document language",
    "售卖凭证默认打印语言",
  ],
  prev: ["Precedente", "Previous", "上一页"],
  next: ["Successiva", "Next", "下一页"],
  noResults: ["Nessun prodotto", "No products", "暂无商品"],
  view: ["Apri prodotto", "Open product", "查看商品"],
} as const;
export type SalesCopyKey = keyof typeof messages;
export function salesCopy(locale: string, key: SalesCopyKey) {
  return messages[key][locale.startsWith("it") ? 0 : locale.startsWith("en") ? 1 : 2];
}
export function salesLanguage(locale: string): InventorySalesLanguage {
  return locale.startsWith("en") ? "en" : locale.startsWith("zh") ? "zh" : "it";
}
