const copy = {
  title: ["Gestione vendita", "Sale follow-up", "销售跟进"],
  fiscal: ["Documento fiscale esterno", "External fiscal document", "外部财政凭证"],
  record: ["Registra documento", "Link document", "关联凭证"],
  correct: ["Correggi collegamento", "Correct reference", "更正关联"],
  verify: ["Verifica documento", "Verify document", "核验凭证"],
  verified: ["Verificato", "Verified", "已核验"],
  unverified: ["Da verificare", "Awaiting verification", "待核验"],
  missing: ["Da registrare", "Not linked", "待关联"],
  documentType: ["Tipo documento", "Document type", "凭证类型"],
  receipt: ["Documento commerciale", "Commercial receipt", "商业凭证"],
  invoice: ["Fattura", "Invoice", "发票"],
  other: ["Altro", "Other", "其他"],
  reference: ["Numero documento", "Document number", "凭证编号"],
  issued: ["Data emissione · Roma", "Issued at · Rome", "开具时间 · 罗马"],
  reason: ["Motivo della correzione", "Correction reason", "更正原因"],
  previousReference: ["Riferimento precedente", "Previous reference", "原凭证编号"],
  fiscalHelp: [
    "Emetti il documento nel sistema di cassa esistente, poi registra qui il riferimento. La verifica è manuale.",
    "Issue the document in your existing cash register, then link its reference here. Verification is manual.",
    "在现有收银系统开具凭证后，在此登记编号。核验由负责人手动完成。",
  ],
  correctionHelp: [
    "La correzione conserva la versione precedente e richiede una nuova verifica.",
    "A correction preserves the previous version and requires verification again.",
    "更正会保留旧版本，并重新进入待核验。",
  ],
  followup: ["Responsabile e richiamo", "Owner and follow-up", "负责人及跟进"],
  assignee: ["Responsabile", "Responsible person", "负责人"],
  unassigned: ["Non assegnato", "Unassigned", "未分配"],
  due: ["Da seguire entro · Roma", "Follow up at · Rome", "跟进时间 · 罗马"],
  note: ["Nota operativa", "Operational note", "工作备注"],
  noteHelp: [
    "Non inserire dati di carte, documenti personali o informazioni sensibili.",
    "Do not enter card details, identity documents or sensitive information.",
    "请勿填写银行卡、证件号码或其他敏感资料。",
  ],
  issues: ["Eccezioni", "Exceptions", "异常事项"],
  openIssue: ["Registra eccezione", "Record exception", "登记异常"],
  resolve: ["Registra esito", "Record resolution", "登记处理结果"],
  issueKind: ["Tipo di eccezione", "Exception type", "异常类型"],
  payment_mismatch: ["Differenza pagamento", "Payment discrepancy", "收款差异"],
  fiscal_document: ["Documento fiscale", "Fiscal document", "财政凭证"],
  customer_request: ["Richiesta cliente", "Customer request", "客户请求"],
  delivery: ["Consegna", "Delivery", "交付"],
  summary: ["Descrizione", "Description", "情况说明"],
  resolution: ["Esito della gestione manuale", "Manual resolution", "人工处理结果"],
  issueHelp: [
    "Questa registrazione non esegue rimborsi, resi o rettifiche di cassa. Mantieni il riferimento alla gestione manuale.",
    "This record does not execute refunds, returns or cash adjustments. Include the reference to the manual handling.",
    "此记录仅跟进人工处理，不执行退款、退货入库或收银冲正。请填写人工处理的关联依据。",
  ],
  open: ["Aperta", "Open", "处理中"],
  resolved: ["Risolta", "Resolved", "已登记处理结果"],
  history: ["Cronologia operativa", "Operational history", "操作历史"],
  recentOnly: [
    "Sono mostrati solo gli ultimi record. La cronologia completa è conservata.",
    "Only recent records are shown. The complete history is retained.",
    "当前仅显示最近记录，完整历史仍保留。",
  ],
  report: ["Riepilogo e attività", "Daily summary and tasks", "日结与待办"],
  date: ["Giorno · Roma", "Business date · Rome", "营业日期 · 罗马"],
  sales: ["Vendite concordate", "Sales agreed", "当日成交额"],
  receipts: ["Incassi registrati", "Payments received", "当日实收"],
  count: ["Operazioni", "Transactions", "笔数"],
  noFinance: [
    "Riepiloghi finanziari riservati agli utenti autorizzati.",
    "Financial totals require aggregate finance permission.",
    "财务汇总仅向有汇总财务权限的账号开放。",
  ],
  ledger: [
    "Differenze attuali del registro del negozio",
    "Current store ledger differences",
    "当前全店内部账本差异",
  ],
  reportHelp: [
    "Incassi per data del pagamento; vendite per data dell'accordo. I documenti di cassa richiedono verifica manuale, senza riconciliazione automatica degli importi esterni.",
    "Payments use payment dates; sales use agreement dates. Cash-register documents require manual checks; external amounts are not reconciled automatically.",
    "实收按付款日期、成交额按销售约定日期统计。外部收银金额需人工核对，系统不会自动计算外部金额差异。",
  ],
  pending: ["Attività attuali", "Current outstanding tasks", "当前未结事项"],
  pendingHelp: [
    "Situazione attuale, indipendente dal giorno selezionato.",
    "Current state, independent of the selected business date.",
    "显示当前状态，不随所选营业日期回溯。",
  ],
  mine: ["Le mie vendite", "My sales", "我负责的销售"],
  store: ["Tutto il negozio", "Whole store", "全店销售"],
  missingFiscal: ["Documento da collegare", "Missing document", "凭证待关联"],
  unverifiedFiscal: ["Documento da verificare", "Unverified document", "凭证待核验"],
  overdue: ["Richiami scaduti", "Overdue follow-ups", "跟进已到期"],
  noTasks: ["Nessuna attività in sospeso", "No outstanding tasks", "暂无未结事项"],
  invalid: [
    "Controlla i campi richiesti e le date.",
    "Check required fields and dates.",
    "请核对必填内容及日期。",
  ],
  saved: ["Salvato", "Saved", "已保存"],
} as const;
export type SalesWorkflowCopyKey = keyof typeof copy;
export function salesWorkflowCopy(locale: string, key: SalesWorkflowCopyKey) {
  return copy[key][locale.startsWith("it") ? 0 : locale.startsWith("en") ? 1 : 2];
}
