\set ON_ERROR_STOP on
begin;
select no_plan();
grant select,update on public.synthetic_requests to service_role;
create function public.sw_order(n integer) returns uuid language sql security definer set search_path='' as $$ select id from public.inventory_sale_orders where inventory_item_id=public.synthetic_item_id(n) $$;
create function public.sw_member(n integer) returns uuid language sql security definer set search_path='' as $$ select id from public.store_memberships where store_id='10000000-0000-4000-8000-000000000001' and user_id=('20000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid $$;
create function public.sw_call(cmd text,payload jsonb,ver bigint default 0,actor integer default 1,n integer default 1,key uuid default gen_random_uuid()) returns jsonb language sql as $$
  select public.repairdesk_inventory_sales_workflow_command('10000000-0000-4000-8000-000000000001',('20000000-0000-4000-8000-'||lpad(actor::text,12,'0'))::uuid,public.sw_order(n),ver,key,cmd,payload) $$;
create function public.sw_read(actor integer default 1,n integer default 1) returns jsonb language sql as $$ select public.repairdesk_inventory_sales_workflow_read('10000000-0000-4000-8000-000000000001',('20000000-0000-4000-8000-'||lpad(actor::text,12,'0'))::uuid,public.sw_order(n)) $$;
create function public.sw_report(actor integer default 1,day date default '2024-02-29',skip integer default 0,take integer default 30) returns jsonb language sql as $$ select public.repairdesk_inventory_sales_workflow_report('10000000-0000-4000-8000-000000000001',('20000000-0000-4000-8000-'||lpad(actor::text,12,'0'))::uuid,day,skip,take) $$;
select is(public.synthetic_sales_call(1)->>'code','completed','fixture sale one');
select is(public.synthetic_sales_call(2,'sale.create',10000,true)->>'code','completed','fixture delivered sale');
select is((select count(*)::integer from pg_class where relname in ('inventory_sales_workflows','inventory_sales_workflow_events','inventory_sales_workflow_issues') and relrowsecurity),3,'workflow tables enable RLS');
select ok(not has_table_privilege('authenticated','public.inventory_sales_workflows','select,insert,update,delete'),'no browser table access');
select ok(not has_table_privilege('service_role','public.inventory_sales_workflows','select,insert,update,delete'),'no service direct workflow table access');
select ok(not has_table_privilege('service_role','public.inventory_sales_workflow_events','select,insert,update,delete'),'no service direct event table access');
select ok(not has_function_privilege('authenticated','public.repairdesk_inventory_sales_workflow_read(uuid,uuid,uuid)','execute'),'browser cannot call read RPC');
select ok(not has_function_privilege('anon','public.repairdesk_inventory_sales_workflow_command(uuid,uuid,uuid,bigint,uuid,text,jsonb)','execute'),'anonymous cannot call command RPC');
select ok(has_function_privilege('service_role','public.repairdesk_inventory_sales_workflow_command(uuid,uuid,uuid,bigint,uuid,text,jsonb)','execute'),'service command RPC enabled');
select is(public.sw_read()->'data'->'workflow'->>'version','0','new sale has implicit workflow version zero');
select is(public.sw_read(4)->>'code','actor_forbidden','technician cannot read workflow');
select is(public.sw_read(6)->>'code','actor_forbidden','inactive member cannot read workflow');
select is(public.sw_read(3)->>'ok','true','sales can read same store sale');
update public.staff_profiles set status='inactive' where id='20000000-0000-4000-8000-000000000001';
select is(public.sw_read()->>'code','actor_forbidden','inactive staff denied despite active membership');
update public.staff_profiles set status='active' where id='20000000-0000-4000-8000-000000000001';
update public.stores set status='suspended' where id='10000000-0000-4000-8000-000000000001';
select is(public.sw_report()->>'code','actor_forbidden','suspended store denies reporting');
update public.stores set status='active' where id='10000000-0000-4000-8000-000000000001';

select is(jsonb_array_length(public.sw_read()->'data'->'assignees'),3,'assignees only active eligible roles');
select is(public.sw_read(3)->'data'->'capabilities'->>'can_verify','false','sales cannot verify fiscal');
select is(public.sw_call('fiscal.verify','{"expected_fiscal_revision":1}',0,3)->>'code','actor_forbidden','sales fiscal verify denied');
select is(public.sw_call('fiscal.verify','{"expected_fiscal_revision":1}')->>'code','fiscal_required','cannot verify missing fiscal');
select is(public.sw_call('fiscal.record','{"document_type":"receipt","reference":"R1","issued_at":"2024-03-01T10:00:00Z","store_id":"injected"}')->>'code','invalid_payload','SQL denies extra payload keys');
select is(public.sw_call('fiscal.record','{"document_type":"receipt","reference":{},"issued_at":"2024-03-01T10:00:00Z"}')->>'code','invalid_payload','SQL enforces payload scalar types');
insert into public.synthetic_requests(name,key,payload) values('fiscal',gen_random_uuid(),'{"document_type":"receipt","reference":"R1","issued_at":"2024-03-01T10:00:00Z"}');
set local role service_role;
update public.synthetic_requests set result=public.sw_call('fiscal.record',payload,0,1,1,key) where name='fiscal';
reset role;
select is((select result->>'code' from public.synthetic_requests where name='fiscal'),'completed','service fiscal record succeeds');
select is((select public.sw_call('fiscal.record',payload,0,1,1,key)->>'code' from public.synthetic_requests where name='fiscal'),'idempotent_replay','same key replays prior result');
select is((select public.sw_call('fiscal.record',payload||'{"reference":"changed"}',0,1,1,key)->>'code' from public.synthetic_requests where name='fiscal'),'idempotency_conflict','same key changed request denied');
select is((select public.sw_call('fiscal.record',payload,0,2,1,key)->>'code' from public.synthetic_requests where name='fiscal'),'idempotency_conflict','same key changed actor denied');
update public.store_memberships set status='inactive' where id=public.sw_member(1);
select is((select public.sw_call('fiscal.record',payload,0,1,1,key)->>'code' from public.synthetic_requests where name='fiscal'),'actor_forbidden','revoked actor cannot replay');
update public.store_memberships set status='active' where id=public.sw_member(1);
select is(public.sw_call('fiscal.verify','{"expected_fiscal_revision":1}',0)->>'code','stale_version','workflow CAS checks existing version');
select is(public.sw_call('fiscal.verify','{"expected_fiscal_revision":2}',1)->>'code','stale_fiscal_revision','verify matches fiscal revision');
select is(public.sw_call('fiscal.verify','{"expected_fiscal_revision":1}',1,2)->>'code','completed','manager can verify fiscal');
select ok(public.sw_read()->'data'->'workflow'->'fiscal'->>'verified_at' is not null,'verified time saved');
select is(public.sw_call('fiscal.record','{"document_type":"invoice","reference":"R2","issued_at":"2024-03-01T10:00:00Z"}',2)->>'code','correction_reason_required','existing fiscal needs correction reason');
select is(public.sw_call('fiscal.record','{"document_type":"invoice","reference":"R2","issued_at":"2024-03-01T10:00:00Z","correction_reason":"Correct type"}',2)->>'code','completed','fiscal correction succeeds');
select is(public.sw_read()->'data'->'workflow'->'fiscal'->>'revision','2','correction increments fiscal revision');
select is(public.sw_read()->'data'->'workflow'->'fiscal'->'verified_at','null'::jsonb,'correction clears verification');
select is(public.sw_read()->'data'->'history'->0->'payload'->'previous_fiscal'->>'reference','R1','history retains former fiscal reference');
select is(public.sw_read()->'data'->'history'->0->'payload'->>'correction_reason','Correct type','history retains reason');
select is(public.sw_call('followup.set',jsonb_build_object('assignee_membership_id',public.sw_member(4),'follow_up_at',null),3)->>'code','invalid_assignee','technician not eligible assignee');
select is(public.sw_call('followup.set',jsonb_build_object('assignee_membership_id',public.sw_member(3),'follow_up_at','2020-01-01T10:00:00Z','note','Follow up'),3)->>'code','completed','assign sales followup');
select is(public.sw_report(3)->'data'->'pending'->>'scope','mine','sales report scope mine');
select is(public.sw_report(3)->'data'->'pending'->>'total','1','sales report includes only assigned orders');
select is(public.sw_report(3)->'data'->'finance','null'::jsonb,'sales no store finance');
select is(public.sw_report(2)->'data'->'finance','null'::jsonb,'manager needs finance grant');
insert into public.store_member_permission_grants(store_id,membership_id,user_id,action,granted_by) values('10000000-0000-4000-8000-000000000001',public.sw_member(2),'20000000-0000-4000-8000-000000000002','finance:aggregate_read','20000000-0000-4000-8000-000000000001');
select is(public.sw_report(2)->'data'->'finance'->>'collected_cents','13000','granted manager gets payment totals');
update public.store_member_permission_grants set revoked_at=now() where action='finance:aggregate_read';
select is(public.sw_report(2)->'data'->'finance','null'::jsonb,'revoked finance grant immediately hides totals');
select is(public.sw_call('issue.open','{"kind":"payment_mismatch","summary":"Reconcile payment"}',4)->>'code','completed','register payment exception');
select is(public.sw_call('issue.resolve',jsonb_build_object('issue_id',(public.sw_read()->'data'->'workflow'->'issues'->0->>'id'),'resolution','Checked original receipt'),5)->>'code','completed','resolve issue');
select is(public.sw_call('issue.resolve',jsonb_build_object('issue_id',(public.sw_read()->'data'->'workflow'->'issues'->0->>'id'),'resolution','Again'),6)->>'code','issue_not_open','resolved issue cannot resolve again');
select is((select paid_cents from inventory_sale_orders where id=public.sw_order(1)),3000::bigint,'exception handling preserves paid amount');
select is((select status from inventory_stock_units where legacy_inventory_item_id=public.synthetic_item_id(1)),'reserved','exception handling preserves stock state');
select is((select count(*)::integer from inventory_warranty_versions),1,'exception handling preserves warranty facts');
select is(public.sw_report()->'data'->'finance'->>'collected_cents','13000','report does not count mirrored transactions twice');
select is(public.sw_report()->'data'->'finance'->>'agreed_sale_count','0','sales use agreed date, not collection date');
select is(public.sw_report(1,'2024-02-28')->'data'->'finance'->>'agreed_sales_cents','20000','agreed amount by business date');
select is(public.sw_report()->'data'->'finance'->>'ledger_mismatch_count','0','balanced ledgers have no difference');
-- A deliberately unmatched payment entry inside this rolled-back fixture proves discrepancy reporting.
insert into public.inventory_sale_payment_entries(store_id,sale_order_id,sequence,receipt_number,amount_cents,paid_after_cents,balance_after_cents,method,occurred_at,actor_id,transaction_id)
values('10000000-0000-4000-8000-000000000001',public.sw_order(1),2,'SYN-MISMATCH',1,3001,6999,'cash','2020-01-01T00:00:00Z','20000000-0000-4000-8000-000000000001',gen_random_uuid());
select is(public.sw_report()->'data'->'finance'->>'ledger_mismatch_count','1','report detects fault-injected unmatched payment entry');
select is(public.sw_report()->'data'->'finance'->>'ledger_difference_cents','-1','difference is paid_cents minus payment entries');

select is(public.sw_report(1,'2024-02-29',1,1)->'data'->'pending'->>'total','2','pagination retains total');
select is(jsonb_array_length(public.sw_report(1,'2024-02-29',1,1)->'data'->'pending'->'rows'),1,'pending pagination bounded');
select throws_ok($$update public.inventory_sales_workflow_events set payload='{}'$$,'23514',null,'workflow audit events immutable');
select throws_ok($$insert into public.inventory_sales_workflows(sale_order_id,store_id,version) values(public.sw_order(1),'10000000-0000-4000-8000-000000000002',1)$$,'23503',null,'workflow cross-store order FK denies');
insert into public.store_memberships(store_id,user_id,email,role,status) values('10000000-0000-4000-8000-000000000002','20000000-0000-4000-8000-000000000001','owner@example.invalid','owner','active');
select is(public.repairdesk_inventory_sales_workflow_read('10000000-0000-4000-8000-000000000002','20000000-0000-4000-8000-000000000001',public.sw_order(1))->>'code','not_found','authorized other store cannot read sale');
select is(public.sw_call('followup.set',jsonb_build_object('assignee_membership_id',(select id from store_memberships where store_id='10000000-0000-4000-8000-000000000002'),'follow_up_at',null),6)->>'code','invalid_assignee','cross-store assignee denied');
-- A failed event write rolls back workflow and its inventory revision together.
create function public.sw_fault() returns trigger language plpgsql as $$ begin raise exception using errcode='23514',message='synthetic workflow fault'; end $$;
create trigger sw_fault before insert on public.inventory_sales_workflow_events for each row execute function public.sw_fault();
insert into public.synthetic_requests(name,result) select 'before-workflow-fault',jsonb_build_object('revision',version) from public.repairdesk_store_domain_versions where store_id='10000000-0000-4000-8000-000000000001' and domain='inventory';
select throws_ok($$select public.sw_call('issue.open','{"kind":"other","summary":"fault"}',6)$$,'23514',null,'late event failure rejects command');
select is(public.sw_read()->'data'->'workflow'->>'version','6','event failure rolls back workflow');
select is((select version from repairdesk_store_domain_versions where store_id='10000000-0000-4000-8000-000000000001' and domain='inventory'),(select (result->>'revision')::bigint from synthetic_requests where name='before-workflow-fault'),'event failure rolls back inventory revision');
drop trigger sw_fault on public.inventory_sales_workflow_events;
-- Read limit is explicit, not silently complete.
do $$ declare n integer;r jsonb;begin for n in 1..101 loop r:=public.sw_call('issue.open',jsonb_build_object('kind','other','summary','Synthetic issue '||n),5+n); if r->>'ok'<>'true' then raise exception '%',r;end if;end loop;end $$;
select is(jsonb_array_length(public.sw_read()->'data'->'workflow'->'issues'),100,'issues bounded at 100');
select is(jsonb_array_length(public.sw_read()->'data'->'history'),50,'history bounded at 50');
select is(public.sw_read()->'data'->'truncated','{"issues":true,"history":true}'::jsonb,'bounded response explicitly signals truncation');
-- DST edges: clocks change inside the Rome business day.
create function public.sw_dst_sale(n integer,at_time timestamptz) returns jsonb language sql as $$ select public.repairdesk_inventory_sales_command('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','sale.create',gen_random_uuid(),public.synthetic_sales_payload(n)||jsonb_build_object('agreed_at',at_time,'payment',jsonb_build_object('amount_cents',3000,'method','card','occurred_at',at_time))) $$;
select is(public.sw_dst_sale(3,'2026-03-28T23:00:00Z')->>'ok','true','spring midnight fixture');
select is(public.sw_dst_sale(4,'2026-03-29T21:59:59Z')->>'ok','true','spring last second fixture');
select is(public.sw_dst_sale(5,'2026-03-29T22:00:00Z')->>'ok','true','next spring day fixture');
select is(public.sw_report(1,'2026-03-29')->'data'->'finance'->>'collected_payment_count','2','23 hour spring date boundaries');
select is(public.sw_report(1,'2026-03-29')->'data'->'finance'->'collected_by_method'->>'card','6000','method totals respect spring date');
select is(public.sw_dst_sale(6,'2025-10-25T22:00:00Z')->>'ok','true','autumn midnight fixture');
select is(public.sw_dst_sale(7,'2025-10-26T22:59:59Z')->>'ok','true','autumn last second fixture');
select is(public.sw_dst_sale(8,'2025-10-26T23:00:00Z')->>'ok','true','next autumn day fixture');
select is(public.sw_report(1,'2025-10-26')->'data'->'finance'->>'collected_payment_count','2','25 hour autumn date boundaries');
select is(public.repairdesk_inventory_sales_command('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000003','sale.create',gen_random_uuid(),public.synthetic_sales_payload(9))->>'code','completed','sales creates own unassigned sale');
select is(public.sw_report(3)->'data'->'pending'->>'total','2','sales sees own unassigned plus assigned orders only');
select is(public.sw_report(2)->'data'->'pending'->>'scope','store','manager without finance grant retains store pending scope');

grant select on public.inventory_sales_workflows,public.inventory_sales_workflow_events,public.inventory_sales_workflow_issues to authenticated;
set local role authenticated;
select is((select count(*)::integer from public.inventory_sales_workflows),0,'RLS still denies if table SELECT accidentally granted');
reset role;
select * from finish();
rollback;
