"use client";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { ImagePlus, Trash2 } from "lucide-react";
import { PhotoCapture } from "@/components/photo-capture";
import { useStaff } from "@/components/staff/use-staff";
import { intakeRecordTime } from "@/lib/repair-intake-record";
import type { RetailUnit } from "@/lib/retail";
import { useRetail } from "./retail-provider";
import { UnitIcon } from "./unit-icon";
import styles from "./retail-gallery.module.css";
export function RetailGallery({unit}:{unit:RetailUnit}) {
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const staff=useStaff();const {dispatch}=useRetail();const [selected,setSelected]=useState(0);const [toolsOpen,setToolsOpen]=useState(false);const [enlarged,setEnlarged]=useState(false);const [pending,setPending]=useState<{photos:string[];version:number;removed?:string}|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);const busy=useRef(false);const input=useRef<HTMLInputElement>(null);const alive=useRef(true);const editable=staff.can("retail.edit") && ["inspecting","hold","available"].includes(unit.status);
 async function select(file:File) {if(busy.current)return;setError("");if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size===0||file.size>12*1024*1024){setError("请选择12MB以内的JPG、PNG或WebP照片。");return;}const version=unit.version;busy.current=true;setLoading(true);try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const context=canvas.getContext("2d");if(!context){bitmap.close();throw new Error("照片无法处理。");}context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let value=canvas.toDataURL("image/jpeg",.8);if(value.length>340000)value=canvas.toDataURL("image/jpeg",.5);if(value.length>340000)throw new Error("压缩后照片仍过大，请选择较小的照片。");if(alive.current)setPending({photos:[...unit.photos,value],version});}catch(reason){if(alive.current)setError(reason instanceof Error?reason.message:"照片无法读取。");}finally{busy.current=false;if(alive.current)setLoading(false);}}
 async function save(){if(!pending)return;if(unit.version!==pending.version){setError("档案已变化，请取消后重选照片。");return;}if(await dispatch({type:"command",id:unit.id,version:pending.version,command:{type:"photos",photos:pending.photos},event:{id:crypto.randomUUID(),time:intakeRecordTime(),title:"实物照片更正",detail:"本台照片 "+pending.photos.length+" 张"}})){setSelected(0);setPending(null);setError("");}else setError("照片未保存，请核对档案和本地存储容量。");}
 return <div className={styles.gallery} data-photo-tools={toolsOpen} role="region" aria-label="本台实物照片"><div className={`${styles.main}${enlarged ? " " + styles.enlarged : ""}`}>{unit.photos[selected]?<Image src={unit.photos[selected]} alt={unit.model+"实物照片"} fill unoptimized sizes="(max-width: 767px) calc(100vw - 48px), 230px"/>:<div className={styles.empty}><UnitIcon category={unit.category} size={58}/><small>本台实物照片</small></div>}</div><button className={styles.mobileToggle} type="button" aria-expanded={toolsOpen} onClick={()=>setToolsOpen(value=>!value)}>{toolsOpen?"收起照片":`照片 ${unit.photos.length}`}</button><div className={styles.tools}>{unit.photos.length?<button className="button button--secondary button--compact" type="button" aria-expanded={enlarged} onClick={()=>setEnlarged(value=>!value)}>{enlarged?"收起大图":"放大实物照片"}</button>:null}{unit.photos.length?<div className={styles.thumbnails}>{unit.photos.map((photo,index)=><button type="button" key={index} aria-label={"查看实物照片 "+(index+1)} aria-pressed={selected===index} onClick={()=>setSelected(index)}><Image src={photo} alt={"实物照片 "+(index+1)} width={44} height={44} unoptimized/></button>)}</div>:null}{editable?<><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" aria-label="上传本台实物照片" hidden onChange={event=>{const file=event.target.files?.[0];if(file)void select(file);event.target.value="";}}/><div className={styles.actions}><button className="button button--secondary button--compact" type="button" disabled={loading||!!pending||unit.photos.length>=6} onClick={()=>input.current?.click()}><ImagePlus size={16}/>{loading?"处理中":"上传"}</button><PhotoCapture label="本台实物照片" onConfirm={select} disabled={loading||!!pending||unit.photos.length>=6} triggerClassName="button button--secondary button--compact"/>{unit.photos.length?<button className="icon-button" type="button" aria-label="移除当前实物照片" disabled={loading||!!pending} onClick={()=>setPending({photos:unit.photos.filter((_,index)=>index!==selected),version:unit.version,removed:unit.photos[selected]})}><Trash2 size={16}/></button>:null}</div></>:null}{pending?<div className={styles.review}>{pending.removed?<><span>待移除照片</span><Image src={pending.removed} alt="待移除照片" width={140} height={100} unoptimized/></>:null}<strong>核对照片变更 · {unit.photos.length} → {pending.photos.length} 张</strong>{pending.photos.at(-1)&&pending.photos.length>unit.photos.length?<Image src={pending.photos.at(-1)!} alt="待保存照片" width={140} height={100} unoptimized/>:null}<div className={styles.actions}><button className="button button--secondary" type="button" onClick={()=>setPending(null)}>取消</button><button className="button button--primary" type="button" onClick={save}>确认保存照片</button></div></div>:null}{error?<p className="form-error" role="alert">{error}</p>:null}</div></div>;
}
