export const INVENTORY_IMAGE_MAX_ORIGINAL_BYTES = 4 * 1024 * 1024;
export const INVENTORY_IMAGE_MAX_DERIVED_BYTES = 2_400_000;
export const INVENTORY_IMAGE_MAX_EDGE = 4096;
export const INVENTORY_IMAGE_MAX_PIXELS = 16_000_000;
export const INVENTORY_IMAGE_MAX_DATA_URL_CHARACTERS =
  Math.ceil(INVENTORY_IMAGE_MAX_DERIVED_BYTES / 3) * 4 + 64;
export const INVENTORY_VISION_REQUEST_MAX_BYTES = 3_400_000;
