package in.chinatech.phoneassistant;

import android.content.*;
import android.database.Cursor;
import android.net.*;
import android.os.*;
import android.provider.*;
import java.io.*;
import java.lang.ref.WeakReference;
import java.net.*;
import java.security.*;
import java.util.*;
import java.util.concurrent.*;
import javax.net.ssl.*;

/** Disk-indexed source -> new-phone TLS server, with durable verified whole-object recovery. */
final class TransferEngine {
 interface Listener{void changed();}
 private static TransferEngine instance;
 static synchronized TransferEngine get(Context c){if(instance==null)instance=new TransferEngine(c.getApplicationContext());return instance;}
 private final Context context;final WifiLink wifi;final TransferStore store;
 private final ExecutorService worker=Executors.newSingleThreadExecutor(),cleanup=Executors.newFixedThreadPool(3);
 private final java.util.concurrent.atomic.AtomicInteger tasks=new java.util.concurrent.atomic.AtomicInteger(),cleanupTasks=new java.util.concurrent.atomic.AtomicInteger();
 private final Handler main=new Handler(Looper.getMainLooper());
 private volatile CancellationScope io=new CancellationScope(cleanup,this::cleanupChanged);
 private volatile WeakReference<Listener> listener=new WeakReference<>(null);
 private final Set<Socket> sockets=ConcurrentHashMap.newKeySet();
 private volatile CompletableFuture<Boolean> foreground,confirmation;
 private volatile boolean senderExistingWifi,active,cancelled,releasing,servicePending,hotspotStarting,routerSelected,finishing;
 private volatile int terminalStatus;
 private volatile SessionTls identity;private volatile SSLServerSocket server;
 private volatile byte[] approvedNonce,clientNonce;
 private volatile long joinMonotonic;
 private volatile long completedGrace;private volatile long completedObjects;private volatile byte[] completedDigest;private volatile boolean finalConfirmed;
 private volatile String approvedTransfer;private volatile long approvedCount;
 volatile ProtocolCore.Pairing serverPair,clientPair;
 volatile String pendingConfirmation;private volatile String currentObjectName;
 volatile String diagnostic="";
 volatile int status=R.string.ready;volatile Object[] statusArgs=new Object[0];
 volatile Uri directory;volatile long receivedCount,expectedCount,scanFailures;
 volatile boolean scanPartial,scanMediaMissing,scanContactsMissing,scanCalendarMissing,scanFinished;
 private volatile Uri sourceTree;
 TransferEngine(Context c){context=c;wifi=new WifiLink(c,this::wifiFailed);store=new TransferStore(c);store.retainAbandoned();String dir=store.get("directory");if(dir!=null)directory=Uri.parse(dir);refreshScanFacts();if(ScanState.INCOMPLETE.equals(store.scanState().state()))status=R.string.scan_interrupted;try{SessionTls.cleanupAbandoned();}catch(Exception e){status=R.string.key_cleanup_warning;}}
 private void refreshScanFacts(){ScanState state=store.scanState();scanFinished=state.finished();scanPartial=Boolean.parseBoolean(store.get("scanPartial"));scanMediaMissing=!"false".equals(store.get("scanMediaMissing"));scanContactsMissing=!"false".equals(store.get("scanContactsMissing"));scanCalendarMissing=!"false".equals(store.get("scanCalendarMissing"));try{scanFailures=Long.parseLong(store.get("scanFailures"));}catch(Exception ignored){scanFailures=0;}}
 String scanState(){return store.scanState().state();}String phoneScanState(){return store.scanState().phone();}long residualCount(){return store.residualCount();}
 void attach(Listener l){listener=new WeakReference<>(l);signal();}void detach(Listener l){if(listener.get()==l)listener=new WeakReference<>(null);}
 private void signal(){main.post(()->{Listener l=listener.get();if(l!=null)l.changed();});}
 /** Wake the current socket immediately while retaining the existing bounded reconnect policy. */
 private void wifiFailed(IOException error){if(!active||cancelled)return;setStatus(errorResource(error));List<Socket> old=new ArrayList<>(sockets);if(old.isEmpty())return;cleanupTasks.incrementAndGet();cleanup.execute(()->{try{for(Socket socket:old)try{socket.close();}catch(IOException ignored){}}finally{cleanupTasks.decrementAndGet();cleanupChanged();}});}
 private synchronized void setStatus(int id,Object... args){if(cancelled&&terminalStatus!=0)return;status=id;statusArgs=args;signal();}
 boolean isActive(){return active||hotspotStarting||tasks.get()>0||cleanupTasks.get()>0||io.hasResources()||releasing||servicePending;}
 boolean isStopping(){return cancelled&&releasing;}
 long selectedCount(){return store.count(true);}long scannedCount(){return store.count(false);}
 boolean chooseCategory(String category,boolean yes){return chooseCategory(category,yes,()->{});}
 boolean chooseCategory(String category,boolean yes,Runnable refresh){if(isActive())return false;passive();execute(()->{try{store.select(category,yes);signal();}finally{main.post(refresh);}});return true;}
 boolean isSelected(long n){return store.isSelected(n);}
 boolean chooseItem(long n,boolean yes){if(isActive())return false;boolean saved=store.select(n,yes);signal();return saved;}
 List<TransferStore.Row> page(String category,long after){return store.page(category,after);}
 void clearSelection(){if(!isActive()){passive();execute(()->{store.clear();long failures=cleanupExports();refreshScanFacts();if(failures>0)setStatus(R.string.scan_errors,failures);else setStatus(R.string.ready);});}}
 void setDirectory(Uri uri){if(!isActive()){directory=uri;store.put("directory",uri.toString());signal();}}
 void decide(boolean yes){CompletableFuture<Boolean> f=confirmation;if(f!=null)f.complete(yes);}
 private void execute(Runnable action){tasks.incrementAndGet();signal();worker.execute(()->{try{if(active){CompletableFuture<Boolean> ready=foreground;if(ready==null||!ready.get(10,TimeUnit.SECONDS))return;checkCancel();}action.run();}catch(Exception e){if(!cancelled)fail(e);}finally{tasks.decrementAndGet();cleanupChanged();}});}
 private boolean begin(){if(isActive())return false;currentObjectName=null;completedGrace=0;completedObjects=0;completedDigest=null;finalConfirmed=false;cancelled=false;terminalStatus=0;io=new CancellationScope(cleanup,this::cleanupChanged);foreground=new CompletableFuture<>();active=true;servicePending=true;setStatus(R.string.service_starting);return StartGuard.run(()->TransferService.start(context),()->{servicePending=false;serviceStartFailed();});}
 boolean foregroundReady(){CompletableFuture<Boolean> f=foreground;if(f==null||cancelled||!active)return false;f.complete(true);return true;}
 void serviceStartFailed(){if(active)release(R.string.service_start_failed);}
 private void passive(){cancelled=false;terminalStatus=0;io=new CancellationScope(cleanup,this::cleanupChanged);}
 void addUris(List<Uri> uris){if(isActive())return;passive();execute(()->{long failed=0;for(Uri uri:uris){try{checkCancel();if(!"content".equals(uri.getScheme()))continue;String name="file",mime=context.getContentResolver().getType(uri);long size=0;try(ProviderIo.Query q=ProviderIo.query(context.getContentResolver(),uri,new String[]{OpenableColumns.DISPLAY_NAME,OpenableColumns.SIZE},null,null,io)){if(q.cursor!=null&&q.cursor.moveToFirst()){name=q.cursor.getString(0);size=Math.max(0,q.cursor.getLong(1));}}store.add(uri,"files",name,mime,size,true);}catch(Exception e){try{checkCancel();}catch(IOException stop){return;}failed++;}}scanFailures+=failed;setStatus(R.string.selected_count,selectedCount());});}
 void scanPhone(boolean media,boolean contacts,boolean calendar){if(isActive())return;passive();scanFinished=false;scanFailures=0;scanPartial=media&&Build.VERSION.SDK_INT>=34&&granted("android.permission.READ_MEDIA_VISUAL_USER_SELECTED")&&!(granted("android.permission.READ_MEDIA_IMAGES")&&granted("android.permission.READ_MEDIA_VIDEO"));scanMediaMissing=!media|| (Build.VERSION.SDK_INT<=32?!granted("android.permission.READ_EXTERNAL_STORAGE"):!granted("android.permission.READ_MEDIA_IMAGES")||!granted("android.permission.READ_MEDIA_VIDEO")||!granted("android.permission.READ_MEDIA_AUDIO"));scanContactsMissing=!contacts||!granted("android.permission.READ_CONTACTS");scanCalendarMissing=!calendar||!granted("android.permission.READ_CALENDAR");execute(()->{try{store.beginScan(ScanState.PHONE,true,scanDetails());scanFailures=cleanupExports();setStatus(R.string.scanning,scannedCount(),0L);PhoneScanner s=new PhoneScanner(context,store,io,(n,f)->setStatus(R.string.scanning,n,f),media,contacts,calendar);s.scan();checkCancel();scanFailures+=s.failures;store.completeScan(ScanState.PHONE,scanDetails(),this::checkCancel);refreshScanFacts();setStatus(R.string.scan_complete,scannedCount(),scanFailures);}catch(Exception e){fail(e);}});}
 private Map<String,String> scanDetails(){Map<String,String> details=new LinkedHashMap<>();details.put("scanFailures",Long.toString(scanFailures));details.put("scanPartial",Boolean.toString(scanPartial));details.put("scanMediaMissing",Boolean.toString(scanMediaMissing));details.put("scanContactsMissing",Boolean.toString(scanContactsMissing));details.put("scanCalendarMissing",Boolean.toString(scanCalendarMissing));return details;}
 private long cleanupExports(){long failed=0;File directory=new File(context.getNoBackupFilesDir(),"exports");File[] files=directory.listFiles();if(files!=null)for(File file:files)if(file.isFile()&&file.getName().startsWith("ctpa-")&&!file.delete())failed++;return failed;}
 private boolean granted(String p){return context.checkSelfPermission(p)==android.content.pm.PackageManager.PERMISSION_GRANTED;}
 void scanTree(Uri uri){if(isActive())return;passive();sourceTree=uri;scanFinished=false;execute(()->{try{String scope="tree:"+uri.toString();store.beginScan(scope,false,scanDetails());setStatus(R.string.scanning,scannedCount(),0L);PhoneScanner s=new PhoneScanner(context,store,io,(n,f)->setStatus(R.string.scanning,n,f));s.tree(uri);checkCancel();scanFailures+=s.failures;store.completeScan(scope,scanDetails(),this::checkCancel);refreshScanFacts();setStatus(scanFinished?R.string.scan_complete:R.string.scan_append_incomplete,scannedCount(),scanFailures);}catch(Exception e){fail(e);}});}
 void createHotspot(){
  synchronized(this){if(isActive())return;if(directory==null){setStatus(R.string.folder_not_selected);return;}routerSelected=false;cancelled=false;terminalStatus=0;hotspotStarting=true;setStatus(R.string.hotspot_starting);}
  try{wifi.startHotspot(new WifiLink.Callback(){
   public void ready(){synchronized(TransferEngine.this){hotspotStarting=false;if(cancelled){wifi.close();return;}setStatus(R.string.hotspot_ready);prepareReceiver();}}
   public void failed(){synchronized(TransferEngine.this){hotspotStarting=false;if(cancelled)return;if(active)release(R.string.hotspot_failed);else setStatus(R.string.hotspot_failed);}}
  });}catch(Exception error){hotspotStarting=false;wifi.close();setStatus(error instanceof SecurityException?R.string.permission_denied:R.string.hotspot_failed);}
 }
 void configureManualHotspot(String ssid,String password){synchronized(this){if(isActive())return;if(directory==null){setStatus(R.string.folder_not_selected);return;}try{wifi.configureExternalHotspot(ssid,password);routerSelected=false;prepareReceiver();}catch(IOException invalid){setStatus(R.string.manual_hotspot_invalid);}}}
 void setHotspotHost(String host){try{wifi.setHostManually(host.trim());setStatus(R.string.hotspot_ready);}catch(Exception e){setStatus(R.string.hotspot_ip_invalid);}}
 void useRouter(){if(!isActive()){routerSelected=true;cancelled=false;terminalStatus=0;wifi.close();setStatus(R.string.router_selected);}}
 private String wifiHost()throws IOException {ConnectivityManager manager=context.getSystemService(ConnectivityManager.class);String found=null;if(manager==null)throw new IOException("WIFI");for(Network network:manager.getAllNetworks()){NetworkCapabilities caps=manager.getNetworkCapabilities(network);LinkProperties properties=manager.getLinkProperties(network);if(caps==null||properties==null||!caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)||caps.hasTransport(NetworkCapabilities.TRANSPORT_VPN))continue;String local=null;for(LinkAddress address:properties.getLinkAddresses()){String host=address.getAddress().getHostAddress();try{ProtocolCore.validateHost(host);local=host;break;}catch(IOException ignored){}}if(local!=null){if(found!=null&&!found.equals(local))throw new IOException("WIFI");found=local;}}if(found==null)throw new IOException("WIFI");return found;}
 void prepareReceiver(){
  synchronized(this){if(isActive())return;if(directory==null){setStatus(R.string.folder_not_selected);return;}if(!wifi.hotspotActive()&&!routerSelected){setStatus(R.string.hotspot_required);return;}if(!begin())return;}
  execute(()->{try{
   boolean hotspot=wifi.hotspotActive();String host=hotspot?ProtocolCore.GATEWAY_HOST:wifiHost();
   store.retainAbandoned();SessionTls id=new SessionTls(System.currentTimeMillis()+10L*365*24*60*60*1000);io.track(id);checkCancel();
   SSLServerSocket s=(SSLServerSocket)id.context.getServerSocketFactory().createServerSocket();io.track(s);s.setEnabledProtocols(SessionTls.protocols(s.getSupportedProtocols()));s.bind(new InetSocketAddress(0),2);s.setSoTimeout(1000);
   long expiry=System.currentTimeMillis()+ProtocolCore.PAIR_TTL_MS;joinMonotonic=SystemClock.elapsedRealtime()+ProtocolCore.PAIR_TTL_MS;
   synchronized(this){checkCancel();identity=id;server=s;serverPair=new ProtocolCore.Pairing(host,s.getLocalPort(),ProtocolCore.token(16),expiry,ProtocolCore.random(32),id.pin,hotspot?wifi.ssid:"",hotspot?wifi.password:"",hotspot?wifi.security:"");}
   setStatus(R.string.receiver_waiting);tasks.incrementAndGet();new Thread(()->{try{serve();}finally{tasks.decrementAndGet();cleanupChanged();}},"ctss-new-phone-server").start();
  }catch(Exception error){fail(error);}});
 }
 private void serve(){try{while(!cancelled){if(completedGrace!=0&&SystemClock.elapsedRealtime()>=completedGrace){release(R.string.receiver_complete_unconfirmed,completedObjects);return;}checkJoin();try{SSLSocket socket=(SSLSocket)server.accept();sockets.add(socket);socket.setSoTimeout(30000);try(SSLSocket peer=socket){peer.setEnabledProtocols(SessionTls.protocols(peer.getSupportedProtocols()));peer.startHandshake();handlePeer(peer);}catch(Exception e){if(!cancelled){if(completedGrace==0)setStatus(errorResource(e));else setStatus(R.string.receiver_complete_pending,completedObjects);}}finally{sockets.remove(socket);}}catch(SocketTimeoutException poll){}}}catch(Exception e){if(!cancelled)fail(e);}}
 private boolean confirm(String challenge)throws Exception {CompletableFuture<Boolean> f=new CompletableFuture<>();confirmation=f;pendingConfirmation=challenge;setStatus(R.string.sender_confirm);try{return f.get(120,TimeUnit.SECONDS);}finally{pendingConfirmation=null;confirmation=null;signal();}}
 private void handlePeer(SSLSocket socket)throws Exception {checkJoin();DataInputStream in=new DataInputStream(new BufferedInputStream(socket.getInputStream(),65536));DataOutputStream out=new DataOutputStream(new BufferedOutputStream(socket.getOutputStream(),65536));String magic=ProtocolCore.readString(in,10),sid=ProtocolCore.readString(in,30);byte[] secret=new byte[32],nonce=new byte[32];in.readFully(secret);in.readFully(nonce);ProtocolCore.Pairing p=serverPair;String transfer=ProtocolCore.readString(in,30);ProtocolCore.validateObjectId(transfer);long count=in.readLong();ProtocolCore.validateCount(count);boolean authenticated=p!=null&&p.acceptsMagic(magic)&&p.session.equals(sid)&&ProtocolCore.equal(secret,p.secret);Arrays.fill(secret,(byte)0);if(!authenticated)throw new IOException("AUTH");checkJoin();if(approvedNonce==null){expectedCount=count;if(!confirm(ProtocolCore.confirmation(p.secret,nonce)))throw new IOException("DECLINED");checkJoin();approvedNonce=nonce.clone();approvedTransfer=transfer;approvedCount=count;}else if(!ProtocolCore.equal(approvedNonce,nonce)||!transfer.equals(approvedTransfer)||count!=approvedCount)throw new IOException("PEER_LOCKED");ProtocolCore.writeString(out,"APPROVED",20);out.flush();if(!in.readBoolean())throw new IOException("DECLINED");socket.setSoTimeout(30000);long done=0,total=0;ManifestDigest manifest=new ManifestDigest();store.beginIncoming();while(done<count){checkCancel();String frame=ProtocolCore.readString(in,20);if("WAIT".equals(frame)){ProtocolCore.writeString(out,"READY",20);out.flush();continue;}if(!"OBJECT".equals(frame))throw new IOException("OBJECT");ProtocolCore.Item item=ProtocolCore.readItem(in);store.incoming(item.id);manifest.add(item);currentObjectName=item.name;total=ProtocolCore.addBytes(total,item.size); // Each object is bounded; SQLite enforces durable unique object identities.
   TransferStore.Receipt receipt=store.receipt(transfer,item,directory);boolean skip=false;if(receipt!=null){try{skip=verify(receipt.uri,item,out);}catch(IOException e){skip=false;}if(!skip)store.forget(transfer,item.id);}ProtocolCore.writeString(out,skip?"SKIP":"WRITE",20);out.flush();if(!skip){Uri dest=null;try{dest=createDestination(item);store.pending(transfer,item.id,dest,directory);try(OutputStream output=ProviderIo.output(context.getContentResolver(),dest,io)){byte[] hash=ChunkTransport.receive(in,output,out,item.size,this::checkCancel);if(!ProtocolCore.equal(hash,item.hash))throw new IOException("HASH");}byte[] tail=new byte[32];in.readFully(tail);if(!ProtocolCore.equal(tail,item.hash)||!verify(dest,item,out))throw new IOException("DISK_VERIFY");checkCancel();store.received(transfer,item,dest,directory);}catch(Exception e){ResidualPolicy.Evidence evidence=dest==null?ResidualPolicy.Evidence.MISSING:deleteCurrent(dest);boolean removed=ResidualPolicy.resolved(evidence);if(dest==null)store.removePending(transfer,item.id);else store.retainResidual(transfer,item.id,dest,directory,evidence);signal();try{ProtocolCore.writeString(out,"FAILED",20);out.write(new byte[32]);ProtocolCore.writeString(out,removed?"WRITE":"PARTIAL_REMAINS",100);out.flush();}catch(IOException ignored){}if(!removed)throw new IOException("PARTIAL_REMAINS");throw e;}}checkCancel();ProtocolCore.writeString(out,"SAVED",20);out.write(item.hash);out.flush();receivedCount=++done;setStatus(R.string.receiver_progress,done,count);}
  if(!"COMPLETE".equals(ProtocolCore.readString(in,20))||in.readLong()!=count||in.readLong()!=total)throw new IOException("INCOMPLETE");byte[] declared=new byte[32];in.readFully(declared);byte[] digest=manifest.finish();if(!ProtocolCore.equal(declared,digest)||manifest.count()!=count)throw new IOException("MANIFEST_CHANGED");checkCancel();if(completedDigest!=null&&(completedObjects!=done||!ProtocolCore.equal(completedDigest,digest)))throw new IOException("MANIFEST_CHANGED");completedObjects=done;completedDigest=digest.clone();if(completedGrace==0)completedGrace=SystemClock.elapsedRealtime()+180000;setStatus(R.string.receiver_complete_pending,done);ProtocolCore.writeString(out,"COMPLETE",20);out.writeLong(done);out.write(digest);out.flush();ProtocolCore.readFinish(in,done,digest);checkCancel();finalConfirmed=true;release(R.string.receiver_complete,done);
 }
 void send(String code){send(code,false);}
 void sendUsingExisting(String code){send(code,true);}
 private void send(String code,boolean existing){synchronized(this){if(isActive()||selectedCount()==0)return;try{clientPair=ProtocolCore.Pairing.parse(code,System.currentTimeMillis());if(!begin())return;senderExistingWifi=existing;clientNonce=ProtocolCore.random(32);joinMonotonic=SystemClock.elapsedRealtime()+Math.max(1,clientPair.expires-System.currentTimeMillis());}catch(Exception e){setStatus(errorResource(e));return;}}execute(()->{try{if(!senderExistingWifi&&!clientPair.ssid.isEmpty()&&Build.VERSION.SDK_INT>=29)wifi.connect(clientPair,this::checkJoin);else wifi.useExistingNetwork(clientPair);sendWithRecovery();}catch(Exception e){fail(e);}});}
 private void sendWithRecovery()throws Exception {int attempts=0;boolean confirmed=false;while(true){checkCancel();try(Client c=client()){if(!confirmed){if(!confirm(ProtocolCore.confirmation(clientPair.secret,clientNonce))){c.out.writeBoolean(false);c.out.flush();throw new IOException("DECLINED");}confirmed=true;}c.out.writeBoolean(true);c.out.flush();prepareSnapshot(c);long done=0,total=0,after=0;ManifestDigest manifest=new ManifestDigest();TransferStore.Row row;while((row=store.nextSending(after))!=null){checkCancel();SourceAccess.check(context,row);ProtocolCore.Item item=row.item();currentObjectName=item.name;manifest.add(item);total=ProtocolCore.addBytes(total,item.size);ProtocolCore.writeString(c.out,"OBJECT",20);ProtocolCore.writeItem(c.out,item);String disposition=readVerifiedControl(c.in);if(!disposition.equals("SKIP")&&!disposition.equals("WRITE"))throw new IOException("OBJECT");boolean skip=disposition.equals("SKIP");if(!skip){try(InputStream source=ProviderIo.input(context.getContentResolver(),AppArchive.source(context,row.uri,row.id,io,this::checkCancel),io)){byte[] hash=ChunkTransport.send(source,c.out,c.in,item.size,sourceCheck(row));checkCancel();int extra=source.read();checkCancel();if(extra!=-1||!ProtocolCore.equal(hash,item.hash))throw new IOException("SOURCE_CHANGED");}c.out.write(item.hash);c.out.flush();}String committedFrame=readVerifiedControl(c.in);if(!committedFrame.equals("SAVED")&&!committedFrame.equals("FAILED"))throw new IOException("OBJECT");boolean committed=committedFrame.equals("SAVED");byte[] ack=new byte[32];c.in.readFully(ack);if(!committed)throw new IOException("REMOTE_"+ProtocolCore.readString(c.in,100));if(!ProtocolCore.equal(ack,item.hash))throw new IOException("RECEIVE_FAILED");after=row.n;setStatus(R.string.sender_progress,++done,store.sendingCount());}ProtocolCore.writeString(c.out,"COMPLETE",20);c.out.writeLong(done);c.out.writeLong(total);byte[] digest=manifest.finish();c.out.write(digest);c.out.flush();if(!"COMPLETE".equals(ProtocolCore.readString(c.in,20))||c.in.readLong()!=done)throw new IOException("INCOMPLETE");byte[] remote=new byte[32];c.in.readFully(remote);if(!ProtocolCore.equal(digest,remote))throw new IOException("MANIFEST_CHANGED");checkCancel();ProtocolCore.writeFinish(c.out,done,digest);release(R.string.sender_complete,done);return;}catch(Exception e){checkCancel();if(!RecoveryPolicy.retryable(e)||++attempts>RecoveryPolicy.MAX_RETRIES)throw e;setStatus(R.string.retrying,attempts,RecoveryPolicy.MAX_RETRIES);long until=SystemClock.elapsedRealtime()+RecoveryPolicy.delay(attempts);while(SystemClock.elapsedRealtime()<until){checkCancel();Thread.sleep(200);}if(wifi.currentNetwork()==null){if(!senderExistingWifi&&Build.VERSION.SDK_INT>=29&&!clientPair.ssid.isEmpty())wifi.connect(clientPair,this::checkJoin);else wifi.useExistingNetwork(clientPair);}}}}
 private void prepareSnapshot(Client c)throws Exception {long after=0,done=0,count=selectedCount();TransferStore.Row row;while((row=store.nextSelected(after))!=null){SourceAccess.check(context,row);checkCancel();SourceAccess.check(context,row);currentObjectName=row.name;ProtocolCore.writeString(c.out,"WAIT",20);c.out.flush();if(!"READY".equals(ProtocolCore.readString(c.in,20)))throw new IOException("OBJECT");MessageDigest h=MessageDigest.getInstance("SHA-256");long size=0;final long[] next={SystemClock.elapsedRealtime()+2000};ProtocolCore.Check heartbeat=()->{checkCancel();if(SystemClock.elapsedRealtime()>=next[0]){ProtocolCore.writeString(c.out,"WAIT",20);c.out.flush();if(!"READY".equals(ProtocolCore.readString(c.in,20)))throw new IOException("OBJECT");next[0]=SystemClock.elapsedRealtime()+2000;}};Uri resolved=AppArchive.source(context,row.uri,row.id,io,heartbeat);byte[] buffer=new byte[65536];try(InputStream source=ProviderIo.input(context.getContentResolver(),resolved,io)){int n;while((n=source.read(buffer))!=-1){checkCancel();SourceAccess.check(context,row);size=ProtocolCore.addBytes(size,n);h.update(buffer,0,n);heartbeat.check();}}byte[] hash=h.digest();if(row.hash!=null&&(row.size!=size||!ProtocolCore.equal(row.hash,hash)))throw new IOException("SOURCE_CHANGED");store.prepared(row,size,hash);after=row.n;setStatus(R.string.preparing_progress,++done,count);}checkCancel();store.freeze();}
 private Client client()throws Exception {checkJoin();ProtocolCore.Pairing p=clientPair;Socket underlying=null;SSLSocket socket=null;try{Network n=wifi.currentNetwork();if(n==null)throw new IOException("WIFI");String target=wifi.resolvedHost(p);underlying=n.getSocketFactory().createSocket();sockets.add(underlying);underlying.connect(new InetSocketAddress(InetAddress.getByName(target),p.port),15000);socket=(SSLSocket)SessionTls.pinned(p.pin).getSocketFactory().createSocket(underlying,target,p.port,true);sockets.remove(underlying);sockets.add(socket);socket.setEnabledProtocols(SessionTls.protocols(socket.getSupportedProtocols()));socket.setSoTimeout(150000);socket.startHandshake();checkJoin();Client c=new Client(socket);ProtocolCore.writeString(c.out,p.magic(),10);ProtocolCore.writeString(c.out,p.session,30);c.out.write(p.secret);c.out.write(clientNonce);ProtocolCore.writeString(c.out,store.transfer(),30);c.out.writeLong(selectedCount());c.out.flush();if(!"APPROVED".equals(ProtocolCore.readString(c.in,20)))throw new IOException("DECLINED");approvedNonce=clientNonce.clone();socket.setSoTimeout(150000);return c;}catch(Exception e){if(socket!=null){sockets.remove(socket);try{socket.close();}catch(Exception ignored){}}if(underlying!=null){sockets.remove(underlying);try{underlying.close();}catch(Exception ignored){}}throw e;}}
 private Uri createDestination(ProtocolCore.Item item)throws Exception {checkCancel();Uri parent=DocumentsContract.buildDocumentUriUsingTree(directory,DocumentsContract.getTreeDocumentId(directory));String name=ProtocolCore.uniqueDestinationName(item.name,item.id,ProtocolCore.token(6));Uri dest=DocumentsContract.createDocument(context.getContentResolver(),parent,item.mime,name);if(dest==null)throw new IOException("WRITE");return dest;}
 private ResidualPolicy.Evidence deleteCurrent(Uri uri){return ResidualPolicy.cleanupCurrent(new ResidualPolicy.Access(){public boolean delete()throws Exception{return DocumentsContract.deleteDocument(context.getContentResolver(),uri);}public Boolean exists()throws Exception{try(ProviderIo.Query q=ProviderIo.query(context.getContentResolver(),uri,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID},null,null,io)){return q.cursor==null?null:q.cursor.moveToFirst();}}});}
 private String readVerifiedControl(DataInputStream input)throws IOException{return ProtocolCore.readVerifiedControl(input,this::checkCancel);}
 private boolean verify(Uri uri,ProtocolCore.Item item,DataOutputStream progress)throws Exception {final long[] next={SystemClock.elapsedRealtime()+2000};DigestSize d=digest(uri,item.size,()->{if(SystemClock.elapsedRealtime()>=next[0]){ProtocolCore.writeString(progress,"VERIFY_PROGRESS",20);progress.flush();next[0]=SystemClock.elapsedRealtime()+2000;}});return d.size==item.size&&ProtocolCore.equal(d.hash,item.hash);}
 private DigestSize digest(Uri uri,long limit,ProtocolCore.Check progress)throws Exception {MessageDigest h=MessageDigest.getInstance("SHA-256");long size=0;byte[] b=new byte[65536];try(InputStream in=ProviderIo.input(context.getContentResolver(),uri,io)){int n;while(true){checkCancel();n=in.read(b);checkCancel();if(n==-1)break;size=ProtocolCore.addBytes(size,n);if(size>limit)throw new IOException("SOURCE_CHANGED");h.update(b,0,n);if(n>0)progress.check();}}return new DigestSize(size,h.digest());}
 private ProtocolCore.Check sourceCheck(TransferStore.Row row){return ()->{checkCancel();SourceAccess.check(context,row);};}
 private void checkCancel()throws IOException {if(cancelled)throw new IOException("CANCELLED");io.check();}
 private void checkJoin()throws IOException {checkCancel();ProtocolCore.Pairing p=serverPair!=null?serverPair:clientPair;if(p==null)throw new IOException("EXPIRED");JoinPolicy.check(approvedNonce!=null,p.expires,joinMonotonic,System.currentTimeMillis(),SystemClock.elapsedRealtime());}
 long galleryCount(){return store.mediaCount(directory);}
 void importGallery(){if(isActive()||directory==null)return;Uri target=directory;passive();execute(()->{try{MediaImporter.Result result=new MediaImporter(context,io).run(store,target,(n,k,f)->setStatus(R.string.gallery_progress,n,k,f));setStatus(R.string.gallery_result,result.imported,result.skipped,result.failed);}catch(Exception error){fail(error);}});}
 Uri lastVcf(){return store.lastVcf(directory);}
 private int errorResource(Exception e){String code=e.getMessage();if("PARTIAL_REMAINS".equals(code))return R.string.partial_remains;if(cancelled||"CANCELLED".equals(code))return terminalStatus!=0?terminalStatus:R.string.cancelled;if("EXPIRED".equals(code))return R.string.session_expired;if("HOTSPOT_HOST".equals(code))return R.string.hotspot_ip_required;if("WIFI".equals(code)||"WIFI_GATEWAY".equals(code)||"MANUAL_WIFI".equals(code))return R.string.wifi_required;if(e instanceof SecurityException)return R.string.permission_denied;if(e instanceof SSLException||"PIN_MISMATCH".equals(code))return R.string.tls_failed;if("SOURCE_CHANGED".equals(code)||"HASH".equals(code)||"DISK_VERIFY".equals(code))return R.string.integrity_failed;if("DECLINED".equals(code))return R.string.pair_declined;return R.string.transfer_failed;}
 private void fail(Exception e){StringBuilder diagnosis=new StringBuilder();for(Throwable reason=e;reason!=null&&diagnosis.length()<300;reason=reason.getCause()){String message=reason.getMessage();diagnosis.append(reason.getClass().getSimpleName()).append(":").append(message!=null&&message.matches("[A-Z0-9_]{1,80}")?message:"").append(";");}diagnostic=diagnosis.toString();if(!cancelled){int reason=errorResource(e);if(currentObjectName!=null&&reason!=R.string.pair_declined&&reason!=R.string.session_expired&&reason!=R.string.service_start_failed)release(R.string.file_failed,currentObjectName,reason);else release(reason);}}void stop(){release(R.string.cancelled);}void timeout(){release(R.string.service_timeout);}void serviceEnded(){servicePending=false;if(active)release(R.string.service_timeout);else cleanupChanged();}
 private synchronized void release(int reason,Object... args){if(releasing){signal();return;}releasing=true;cancelled=true;active=false;hotspotStarting=false;terminalStatus=StopReason.keep(terminalStatus,reason,R.string.cancelled);status=terminalStatus;statusArgs=args;CompletableFuture<Boolean> f=foreground;if(f!=null)f.complete(false);f=confirmation;if(f!=null)f.complete(false);pendingConfirmation=null;confirmation=null;SSLServerSocket oldServer=server;server=null;List<Socket> oldSockets=new ArrayList<>(sockets);sockets.clear();SessionTls oldIdentity=identity;identity=null;if(serverPair!=null)serverPair.erase();serverPair=null;if(clientPair!=null)clientPair.erase();clientPair=null;if(approvedNonce!=null)Arrays.fill(approvedNonce,(byte)0);approvedNonce=null;if(clientNonce!=null)Arrays.fill(clientNonce,(byte)0);clientNonce=null;approvedTransfer=null;approvedCount=0;cleanupTasks.incrementAndGet();io.cancel();cleanup.execute(()->{try{wifi.close();if(oldServer!=null)try{oldServer.close();}catch(Exception ignored){}for(Socket socket:oldSockets)try{socket.close();}catch(Exception ignored){}if(oldIdentity!=null)oldIdentity.close();}finally{cleanupTasks.decrementAndGet();cleanupChanged();}});try{if(!context.stopService(new Intent(context,TransferService.class)))servicePending=false;}catch(RuntimeException ignored){}signal();}
 private synchronized void cleanupChanged(){if(releasing&&!servicePending&&tasks.get()==0&&cleanupTasks.get()==0&&!io.hasResources()){releasing=false;}signal();}
 private static final class DigestSize{final long size;final byte[] hash;DigestSize(long size,byte[] hash){this.size=size;this.hash=hash;}}
 private final class Client implements AutoCloseable{final SSLSocket socket;final DataInputStream in;final DataOutputStream out;Client(SSLSocket socket)throws IOException{this.socket=socket;in=new DataInputStream(new BufferedInputStream(socket.getInputStream(),65536));out=new DataOutputStream(new BufferedOutputStream(socket.getOutputStream(),65536));}public void close(){sockets.remove(socket);try{socket.close();}catch(IOException ignored){}}}
}
