package in.chinatech.phoneassistant;

import android.content.*;
import android.database.*;
import android.database.sqlite.*;
import android.net.Uri;
import java.io.*;
import java.util.*;

/** Private disk-backed scan, immutable send snapshot and persisted completed-object receipts. */
final class TransferStore extends SQLiteOpenHelper {
 static final int PAGE=TransferSchema.PAGE;
 private final Context context;private volatile long totalCount,selectedCount;private final java.util.concurrent.ConcurrentHashMap<String,Long> categoryCounts=new java.util.concurrent.ConcurrentHashMap<>();
 TransferStore(Context c){super(c,"transfer-v2.sqlite",null,TransferSchema.VERSION);context=c;setWriteAheadLoggingEnabled(true);refreshCounts();}
 @Override public void onCreate(SQLiteDatabase d){d.execSQL(TransferSchema.ITEMS);d.execSQL(TransferSchema.SELECTION);d.execSQL(TransferSchema.CATEGORIES);d.execSQL("CREATE TABLE sending(n INTEGER PRIMARY KEY,uri TEXT NOT NULL,object TEXT UNIQUE NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,size INTEGER NOT NULL,hash BLOB NOT NULL)");d.execSQL(TransferSchema.RECEIPTS);d.execSQL("CREATE TABLE pending(transfer TEXT NOT NULL,object TEXT NOT NULL,dest TEXT NOT NULL,directory TEXT NOT NULL,PRIMARY KEY(transfer,object))");d.execSQL("CREATE TABLE directories(uri TEXT PRIMARY KEY,done INTEGER NOT NULL DEFAULT 0)");d.execSQL(TransferSchema.RESIDUALS);d.execSQL(TransferSchema.SCOPES);d.execSQL("CREATE TABLE incoming(object TEXT PRIMARY KEY)");d.execSQL("CREATE TABLE meta(k TEXT PRIMARY KEY,v TEXT NOT NULL)");ContentValues initial=new ContentValues();initial.put("k","transfer");initial.put("v",ProtocolCore.token(16));d.insertOrThrow("meta",null,initial);}
 @Override public void onUpgrade(SQLiteDatabase d,int old,int next){if(old==1&&next==TransferSchema.VERSION){for(String sql:TransferSchema.FROM_ONE)d.execSQL(sql);}else throw new IllegalStateException("Unsupported transfer schema");}
 private synchronized void refreshCounts(){long all=0,chosen=0;categoryCounts.clear();try(Cursor cur=getReadableDatabase().rawQuery(TransferSchema.COUNTS,null)){while(cur.moveToNext()){String category=cur.getString(0);long n=cur.getLong(1);categoryCounts.put(category,n);all+=n;chosen+=cur.getLong(2);}}totalCount=all;selectedCount=chosen;}
 synchronized void put(String key,String value){ContentValues v=new ContentValues();v.put("k",key);v.put("v",value);getWritableDatabase().insertWithOnConflict("meta",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 synchronized String get(String key){try(Cursor c=getReadableDatabase().rawQuery("SELECT v FROM meta WHERE k=?",new String[]{key})){return c.moveToFirst()?c.getString(0):null;}}
 synchronized String transfer(){String id=get("transfer");if(id==null){id=ProtocolCore.token(16);put("transfer",id);}return id;}
 private void clearIndex(SQLiteDatabase d){d.delete("items",null,null);d.delete("sending",null,null);d.delete("directories",null,null);d.delete("scan_scopes",null,null);put("transfer",ProtocolCore.token(16));}
 synchronized void clear(){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{clearIndex(d);saveScanState(new ScanState(Collections.emptyMap()),emptyScanDetails());d.setTransactionSuccessful();}finally{d.endTransaction();}refreshCounts();}
 static Map<String,String> emptyScanDetails(){Map<String,String> v=new LinkedHashMap<>();v.put("scanFailures","0");v.put("scanPartial","false");v.put("scanMediaMissing","true");v.put("scanContactsMissing","true");v.put("scanCalendarMissing","true");return v;}
 synchronized ScanState scanState(){Map<String,String> scopes=new LinkedHashMap<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT scope,state FROM scan_scopes",null)){while(c.moveToNext())scopes.put(c.getString(0),c.getString(1));}return new ScanState(scopes);}
 private void saveScanState(ScanState state,Map<String,String> details){SQLiteDatabase d=getWritableDatabase();d.delete("scan_scopes",null,null);for(Map.Entry<String,String> e:state.scopes().entrySet()){ContentValues v=new ContentValues();v.put("scope",e.getKey());v.put("state",e.getValue());d.insertOrThrow("scan_scopes",null,v);}put("scanState",state.state());for(Map.Entry<String,String> e:details.entrySet())put(e.getKey(),e.getValue());}
 synchronized void beginScan(String scope,boolean replace,Map<String,String> details){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{ScanState next=scanState().begin(scope,replace);if(replace)clearIndex(d);saveScanState(next,details);d.setTransactionSuccessful();}finally{d.endTransaction();}if(replace)refreshCounts();}
 synchronized void completeScan(String scope,Map<String,String> details,ProtocolCore.Check check)throws IOException {SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{saveScanState(scanState().finish(scope,check),details);check.check();d.setTransactionSuccessful();}finally{d.endTransaction();}}
 synchronized void add(Uri uri,String category,String name,String mime,long size,boolean selected)throws IOException {ProtocolCore.validateSize(size);ContentValues v=new ContentValues();v.put("uri",uri.toString());v.put("object",ProtocolCore.token(16));v.put("category",category);v.put("name",ProtocolCore.safeName(name));v.put("mime",mime==null?"application/octet-stream":mime);v.put("size",size);v.put("selected",selected?1:0);long inserted=getWritableDatabase().insertWithOnConflict("items",null,v,SQLiteDatabase.CONFLICT_IGNORE);if(inserted>=0){totalCount++;if(selected)selectedCount++;categoryCounts.merge(category,1L,Long::sum);}if(inserted<0){try(Cursor c=getReadableDatabase().rawQuery("SELECT selected FROM items WHERE uri=?",new String[]{uri.toString()})){if(!c.moveToFirst())throw new IOException("SCAN_STORE");if(selected&&c.getInt(0)==0)selectedCount++;}if(selected){ContentValues chosen=new ContentValues();chosen.put("selected",1);getWritableDatabase().update("items",chosen,"uri=?",new String[]{uri.toString()});}}}
 long count(boolean selected){return selected?selectedCount:totalCount;}
 long countCategory(String category){Long n=categoryCounts.get(category);return n==null?0:n;}
 synchronized void select(String category,boolean value){getWritableDatabase().execSQL(category==null?TransferSchema.SELECT_ALL:TransferSchema.SELECT_CATEGORY,category==null?new Object[]{value?1:0}:new Object[]{value?1:0,category});refreshCounts();}
 synchronized boolean isSelected(long n){try(Cursor c=getReadableDatabase().rawQuery("SELECT selected FROM items WHERE n=?",new String[]{Long.toString(n)})){return c.moveToFirst()&&c.getInt(0)!=0;}}
 synchronized boolean select(long n,boolean value){int old;try(Cursor c=getReadableDatabase().rawQuery("SELECT selected FROM items WHERE n=?",new String[]{Long.toString(n)})){if(!c.moveToFirst())return false;old=c.getInt(0);}ContentValues v=new ContentValues();v.put("selected",value?1:0);if(getWritableDatabase().update("items",v,"n=?",new String[]{Long.toString(n)})!=1)return false;selectedCount+=(value?1:0)-old;return true;}
 synchronized List<Row> page(String category,long after){List<Row> out=new ArrayList<>();String sql=TransferSchema.pageSql(category!=null);try(Cursor c=getReadableDatabase().rawQuery(sql,category==null?new String[]{Long.toString(after)}:new String[]{Long.toString(after),category})){while(c.moveToNext())out.add(row(c));}return out;}
 synchronized Row nextSelected(long after){try(Cursor c=getReadableDatabase().rawQuery("SELECT n,uri,object,name,mime,size,hash,selected,category FROM items WHERE selected=1 AND n>? ORDER BY n LIMIT 1",new String[]{Long.toString(after)})){return c.moveToFirst()?row(c):null;}}
 synchronized void prepared(Row r,long size,byte[] hash){ContentValues v=new ContentValues();v.put("size",size);v.put("hash",hash);getWritableDatabase().update("items",v,"n=?",new String[]{Long.toString(r.n)});}
 synchronized void freeze(){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{d.delete("sending",null,null);d.execSQL("INSERT INTO sending SELECT n,uri,object,name,mime,size,hash FROM items WHERE selected=1 AND hash IS NOT NULL");if(DatabaseUtils.longForQuery(d,"SELECT count(*) FROM sending",null)!=count(true))throw new IllegalStateException("Preparation incomplete");d.setTransactionSuccessful();}finally{d.endTransaction();}}
 synchronized long sendingCount(){return DatabaseUtils.longForQuery(getReadableDatabase(),"SELECT count(*) FROM sending",null);}
 synchronized Row nextSending(long after){try(Cursor c=getReadableDatabase().rawQuery("SELECT s.n,s.uri,s.object,s.name,s.mime,s.size,s.hash,1,coalesce(i.category,'files') FROM sending s LEFT JOIN items i ON i.n=s.n WHERE s.n>? ORDER BY s.n LIMIT 1",new String[]{Long.toString(after)})){return c.moveToFirst()?row(c):null;}}
 private static Row row(Cursor c){return new Row(c.getLong(0),Uri.parse(c.getString(1)),c.getString(2),c.getString(3),c.getString(4),c.getLong(5),c.isNull(6)?null:c.getBlob(6),c.getInt(7)!=0,c.getString(8));}
 synchronized Receipt receipt(String transfer,ProtocolCore.Item item,Uri directory){try(Cursor c=getReadableDatabase().rawQuery("SELECT name,mime,size,hash,dest FROM receipts WHERE transfer=? AND object=? AND directory=?",new String[]{transfer,item.id,directory.toString()})){if(!c.moveToFirst())return null;if(!item.name.equals(c.getString(0))||!item.mime.equals(c.getString(1))||item.size!=c.getLong(2)||!ProtocolCore.equal(item.hash,c.getBlob(3)))return null;return new Receipt(Uri.parse(c.getString(4)));}}
 synchronized void received(String transfer,ProtocolCore.Item item,Uri dest,Uri directory){ContentValues v=new ContentValues();v.put("transfer",transfer);v.put("object",item.id);v.put("name",item.name);v.put("mime",item.mime);v.put("size",item.size);v.put("hash",item.hash);v.put("dest",dest.toString());v.put("directory",directory.toString());SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{if(d.insertWithOnConflict("receipts",null,v,SQLiteDatabase.CONFLICT_REPLACE)<0)throw new SQLiteException("Receipt save failed");d.delete("pending","transfer=? AND object=?",new String[]{transfer,item.id});d.setTransactionSuccessful();}finally{d.endTransaction();}}
 synchronized void forget(String transfer,String object){getWritableDatabase().delete("receipts","transfer=? AND object=?",new String[]{transfer,object});}
 synchronized void pending(String transfer,String object,Uri dest,Uri directory){ContentValues v=new ContentValues();v.put("transfer",transfer);v.put("object",object);v.put("dest",dest.toString());v.put("directory",directory.toString());getWritableDatabase().insertOrThrow("pending",null,v);}
 synchronized void removePending(String transfer,String object){getWritableDatabase().delete("pending","transfer=? AND object=?",new String[]{transfer,object});}
 synchronized void retainResidual(String transfer,String object,Uri dest,Uri directory,ResidualPolicy.Evidence evidence){if(ResidualPolicy.resolved(evidence)){removePending(transfer,object);return;}SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{ContentValues v=new ContentValues();v.put("token",ProtocolCore.token(16));v.put("transfer",transfer);v.put("object",object);v.put("dest",dest.toString());v.put("directory",directory.toString());v.put("reason",ResidualPolicy.reason(evidence));d.insertOrThrow("residuals",null,v);d.delete("pending","transfer=? AND object=?",new String[]{transfer,object});d.setTransactionSuccessful();}finally{d.endTransaction();}}
 synchronized void retainAbandoned(){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{d.execSQL(TransferSchema.RETAIN_ABANDONED);d.delete("pending",null,null);d.setTransactionSuccessful();}finally{d.endTransaction();}}
 synchronized long residualCount(){return DatabaseUtils.longForQuery(getReadableDatabase(),"SELECT count(*) FROM residuals",null);}
 synchronized void beginIncoming(){getWritableDatabase().delete("incoming",null,null);}
 synchronized void incoming(String object)throws IOException {ContentValues v=new ContentValues();v.put("object",object);try{getWritableDatabase().insertOrThrow("incoming",null,v);}catch(SQLiteConstraintException e){throw new IOException("DUPLICATE_OBJECT");}}
 synchronized long mediaCount(Uri directory){if(directory==null)return 0;return DatabaseUtils.longForQuery(getReadableDatabase(),"SELECT count(*) FROM receipts WHERE directory=? AND (mime LIKE 'image/%' OR mime LIKE 'video/%')",new String[]{directory.toString()});}
 synchronized MediaReceipt nextMedia(Uri directory,long after)throws IOException {if(directory==null)return null;try(Cursor c=getReadableDatabase().rawQuery("SELECT rowid,object,name,mime,size,hash,dest FROM receipts WHERE directory=? AND rowid>? AND (mime LIKE 'image/%' OR mime LIKE 'video/%') ORDER BY rowid LIMIT 1",new String[]{directory.toString(),Long.toString(after)})){return c.moveToFirst()?new MediaReceipt(c.getLong(0),new ProtocolCore.Item(c.getString(1),c.getString(2),c.getString(3),c.getLong(4),c.getBlob(5)),Uri.parse(c.getString(6))):null;}}
 static final class MediaReceipt {final long n;final ProtocolCore.Item item;final Uri source;MediaReceipt(long n,ProtocolCore.Item item,Uri source){this.n=n;this.item=item;this.source=source;}}
 synchronized Uri lastVcf(Uri directory){if(directory==null)return null;try(Cursor c=getReadableDatabase().rawQuery("SELECT dest FROM receipts WHERE directory=? AND (mime='text/x-vcard' OR name LIKE '%.vcf') ORDER BY rowid DESC LIMIT 1",new String[]{directory.toString()})){return c.moveToFirst()?Uri.parse(c.getString(0)):null;}}
 synchronized void queueDirectory(Uri uri){ContentValues v=new ContentValues();v.put("uri",uri.toString());getWritableDatabase().insertWithOnConflict("directories",null,v,SQLiteDatabase.CONFLICT_IGNORE);}
 synchronized Uri nextDirectory(){try(Cursor c=getReadableDatabase().rawQuery("SELECT uri FROM directories WHERE done=0 LIMIT 1",null)){return c.moveToFirst()?Uri.parse(c.getString(0)):null;}}
 synchronized void directoryDone(Uri uri){ContentValues v=new ContentValues();v.put("done",1);getWritableDatabase().update("directories",v,"uri=?",new String[]{uri.toString()});}
 synchronized void resetDirectories(){getWritableDatabase().delete("directories",null,null);}
 static final class Row {final long n,size;final Uri uri;final String id,name,mime,category;final byte[] hash;final boolean selected;Row(long n,Uri uri,String id,String name,String mime,long size,byte[] hash,boolean selected,String category){this.n=n;this.uri=uri;this.id=id;this.name=name;this.mime=mime;this.size=size;this.hash=hash;this.selected=selected;this.category=category;}ProtocolCore.Item item()throws IOException{return new ProtocolCore.Item(id,name,mime,size,hash);}}
 static final class Receipt {final Uri uri;Receipt(Uri uri){this.uri=uri;}}
}
