import { emptyRetailUnit, type RetailUnit } from "./retail";

// Adapted from the package's fictional unit examples, not its localStorage adapter.
function seed(index: number, values: Partial<RetailUnit>): RetailUnit {
  return { ...emptyRetailUnit(), id: `demo-unit-${index}`, code: `CT-26-${String(index).padStart(4, "0")}`, category: "phone", brand: "Apple", model: "iPhone 13", color: "蓝色", serial: `DEMO-SN-${String(index).padStart(4, "0")}`, condition: "翻新机", grade: "A", bodyStorage: { capacity: 128, unit: "GB" }, batteryPercent: 89, accessories: "充电线", knownIssues: "轻微使用痕迹；虚构演示资料。", storeOwned: true, costCents: 15000, refurbCents: 1500, priceCents: 26000, source: "个人回收 · 演示", location: "手机柜 A-01", intakeDate: "2026-09-27", status: "available", inspection: { functional: true, ownership: true, data: true }, events: [{ id: `seed-${index}`, title: "独立单机档案已建立", detail: "每条档案对应一件自有实物；全部资料均为演示。", time: "2026-09-27 10:00" }], ...values };
}

export const retailUnits: RetailUnit[] = [
  seed(1, { imei1: "000000000000101", imei2: "000000000000102", productCode: "DEMO-BOX-IPH13" }),
  seed(2, { color: "午夜色", batteryPercent: 78, grade: "B", costCents: 12000, refurbCents: null, priceCents: 22000, location: "待检测区", intakeDate: "2026-09-29", productCode: "DEMO-BOX-IPH13", status: "inspecting", inspection: { functional: false, ownership: true, data: false } }),
  seed(3, { category: "tablet", model: "iPad 9", color: "银色", bodyStorage: { capacity: 64, unit: "GB" }, batteryPercent: null, costCents: 11000, refurbCents: 0, priceCents: 21000, location: "平板柜 B-01", edition: "Wi-Fi", intakeDate: "2026-09-24" }),
  seed(4, { category: "laptop", brand: "Lenovo", model: "ThinkPad T14", color: "黑色", ramGb: 16, bodyStorage: null, disks: [{ type: "SSD", capacity: 512, unit: "GB" }], cpu: "Intel Core i5 · 代际待核实", gpu: "集成显卡", keyboard: "意大利语 IT", batteryPercent: 86, accessories: "原装充电器", status: "reserved", reservation: { name: "演示预留", until: "2026-10-01" }, costCents: 19000, refurbCents: 2000, priceCents: 35000, location: "电脑架 C-01", intakeDate: "2026-09-22" }),
  seed(5, { category: "console", brand: "Sony", model: "PS5 Digital", color: "白色", bodyStorage: { capacity: 825, unit: "GB" }, ramGb: null, batteryPercent: null, controllers: 0, edition: "数字版", accessories: "电源线；不含手柄", costCents: 18000, refurbCents: 0, priceCents: 28000, location: "游戏机架 D-01", intakeDate: "2026-09-20" }),
  seed(6, { category: "console", brand: "Nintendo", model: "Switch OLED", color: "白色", bodyStorage: { capacity: 64, unit: "GB" }, batteryPercent: null, controllers: 2, edition: "OLED", accessories: "Joy-Con 一对、底座、电源", costCents: 12500, refurbCents: 0, priceCents: 21000, location: "游戏机架 D-02", intakeDate: "2026-09-18" }),
  seed(7, { category: "desktop", brand: "组装", model: "台式电脑", color: "黑色", ramGb: 16, bodyStorage: null, disks: [{ type: "SSD", capacity: 512, unit: "GB" }, { type: "HDD", capacity: 1, unit: "TB" }], cpu: "Intel Core i5-10400", gpu: "NVIDIA GTX 1650", batteryPercent: null, accessories: "电源线", costCents: 14000, refurbCents: 2500, priceCents: 28000, location: "隔离区", status: "hold", inspection: { functional: false, ownership: true, data: true }, knownIssues: "USB 接口待排查，暂停销售。", intakeDate: "2026-09-15" }),
  seed(8, { brand: "Samsung", model: "Galaxy S21", color: "紫色", ramGb: 8, batteryPercent: null, costCents: 11000, refurbCents: 0, priceCents: 23000, location: "已交付", intakeDate: "2026-09-10", status: "sold", sales: [{ id: "DEMO-SALE-001", time: "2026-09-28 16:00", priceCents: 23000, paidCents: 23000, delivered: true, note: "虚构历史销售，不代表实际收款或交付。" }] }),
];
