// Keep released versions stable: sales record the version agreed at registration.
export const retailWarrantyTerms = [
  { title: "保修范围", zh: "商家保修覆盖正常使用中发生的硬件故障，核实后免费维修或更换相应部件。期限从实际交付日起计算，适用于本单所列实物，在意大利门店办理。", it: "Guasti hardware in uso normale: riparazione o sostituzione dei componenti interessati senza spese, previa verifica. Assistenza presso il negozio in Italia.", en: "Hardware faults during normal use: repair or replacement of affected parts without charge, following verification. Support is provided at the shop in Italy." },
  { title: "意外与人为损坏", zh: "由跌落、碰撞、挤压、弯折、进水、液体侵入、腐蚀、使用不当或疏忽造成的故障，不属于商家保修；须核实损坏原因，不能仅凭损坏标记否定其他故障的保障。", it: "Esclusi i guasti causati da cadute, urti, schiacciamento, piegature, acqua o altri liquidi, corrosione, uso improprio o negligenza. La causa deve essere verificata; i difetti indipendenti conservano la propria tutela.", en: "Faults caused by drops, impacts, crushing, bending, water or other liquids, corrosion, misuse or negligence are excluded. The cause must be checked; unrelated defects retain their protection." },
  { title: "其他除外情况", zh: "正常损耗、外观磨损以及与第三方拆修或不当改装存在因果关系的故障，不属于额外商家保修。数据恢复、账号服务不在此保修服务范围；法定符合性权利仍适用。", it: "Esclusi dalla sola garanzia commerciale normale usura, danni estetici e guasti causati da interventi di terzi o modifiche improprie; non inclusi recupero dati e servizi account. Restano salvi i diritti di conformità.", en: "Normal wear, cosmetic damage and faults caused by third-party work or improper modifications are excluded from the commercial warranty only. Data recovery and account services are not included. Statutory conformity rights remain unaffected." },
  { title: "办理售后", zh: "联系本单所列门店，携带设备及购买证明说明故障；请先备份个人数据。经核实不在保修范围的维修，须在客户确认报价后进行。", it: "Contattare il garante indicato, presentando il bene, una prova d'acquisto e la descrizione del difetto. Effettuare prima un backup dei dati. Interventi fuori copertura solo con preventivo accettato dal cliente.", en: "Contact the stated warranty provider, presenting the device, proof of purchase and a description of the fault. Back up data first. Work outside cover requires a quote accepted by the customer." },
] as const;

export const retailStatutoryRights = {
  zh: "商家保修不影响消费者免费享有的法定符合性救济。意大利新商品法定保障通常为交付起 2 年；翻新商品不因名称或本页的 1 年商家保修设置而自动缩短法定期限。",
  it: "Il consumatore ha rimedi gratuiti per i difetti di conformità nei confronti del venditore: la garanzia commerciale non li limita. La garanzia legale è di due anni dalla consegna; questo documento non la riduce per il bene ricondizionato.",
  en: "Consumers have free remedies against the seller for lack of conformity; the commercial warranty does not limit them. The legal warranty lasts two years from delivery; this receipt does not shorten it for refurbished goods.",
} as const;
