package in.chinatech.mimoverengine;

import android.Manifest;
import android.content.*;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.provider.CalendarContract;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** Imports ordinary ICS events into a user-selected writable calendar, without editing existing events. */
final class CalendarImporter {
 static final class Calendar {final long id;final String name;Calendar(long i,String n){id=i;name=n;}}
 static List<Calendar> calendars(Context c){List<Calendar> rows=new ArrayList<>();try(Cursor q=c.getContentResolver().query(CalendarContract.Calendars.CONTENT_URI,new String[]{"_id","calendar_displayName"},"calendar_access_level>=?",new String[]{Integer.toString(CalendarContract.Calendars.CAL_ACCESS_CONTRIBUTOR)},null)){if(q!=null)while(q.moveToNext())rows.add(new Calendar(q.getLong(0),q.getString(1)));}return rows;}
 static ContactImporter.Result run(Context c,CancellationScope io,RestoreLedger journal,File file,String hash,long calendar,RestoreCoordinator.Progress progress)throws Exception {
  ContactImporter.Result result=new ContactImporter.Result();long index=0;Map<String,Integer> occurrences=new HashMap<>();
  try(RestoreText.Reader reader=new RestoreText.Reader(new FileInputStream(file))){RestoreText.Record r;while((r=reader.next("VEVENT"))!=null){index++;String fingerprint=r.fingerprint();int occurrence=occurrences.getOrDefault(fingerprint,0)+1;occurrences.put(fingerprint,occurrence);String key="calendar:"+fingerprint+":"+calendar+":"+occurrence;io.check();if(c.checkSelfPermission(Manifest.permission.READ_CALENDAR)!=PackageManager.PERMISSION_GRANTED||c.checkSelfPermission(Manifest.permission.WRITE_CALENDAR)!=PackageManager.PERMISSION_GRANTED)throw new SecurityException("CALENDAR_PERMISSION");try{
   if(!writable(c,calendar))throw new IOException("CALENDAR_TARGET");String marker="chinatech-restore:"+key;try(ProviderIo.Query q=ProviderIo.query(c.getContentResolver(),CalendarContract.Events.CONTENT_URI,new String[]{"_id"},CalendarContract.Events.CUSTOM_APP_PACKAGE+"=? AND "+CalendarContract.Events.CUSTOM_APP_URI+"=?",new String[]{c.getPackageName(),marker},io)){if(q.cursor==null)throw new IOException("CALENDAR_QUERY");if(q.cursor.moveToFirst()){long id=q.cursor.getLong(0);if(q.cursor.moveToNext())throw new IOException("CALENDAR_AMBIGUOUS");result.existing++;RestoreLedger.Entry previous=journal.get(key);boolean wasPartial=r.skippedComponents>0||(previous!=null&&previous.state.equals("partial"));for(RestoreText.Property p:r.fields)if(!Arrays.asList("SUMMARY","DESCRIPTION","LOCATION","STATUS","UID","DTSTAMP","DTSTART","DTEND","DURATION").contains(p.name))wasPartial=true;if(wasPartial)result.partial++;journal.put(key,"calendar",Long.toString(id),wasPartial?"partial":"done",-1,"");continue;}}
   if(r.first("RRULE")!=null||r.first("RDATE")!=null||r.first("EXDATE")!=null||r.first("RECURRENCE-ID")!=null)throw new IOException("CALENDAR_RECURRENCE");RestoreText.Property start=r.first("DTSTART"),end=r.first("DTEND");if(start==null)throw new IOException("CALENDAR_START");boolean day="DATE".equalsIgnoreCase(start.params.get("VALUE"));long begin=date(start,day),finish=end==null?begin+(day?86400000L:0):date(end,day);RestoreText.Property duration=r.first("DURATION");if(end==null&&duration!=null){java.util.regex.Matcher m=java.util.regex.Pattern.compile("P(?:(\\d+)D)?(?:T(?:(\\d+)H)?(?:(\\d+)M)?(?:(\\d+)S)?)?").matcher(duration.value);if(!m.matches())throw new IOException("CALENDAR_DURATION");long delta=0;long[] scale={86400000,3600000,60000,1000};for(int j=0;j<4;j++)if(m.group(j+1)!=null)delta=Math.addExact(delta,Math.multiplyExact(Long.parseLong(m.group(j+1)),scale[j]));finish=Math.addExact(begin,delta);}if(finish<begin)throw new IOException("CALENDAR_END");
   ContentValues v=new ContentValues();v.put(CalendarContract.Events.CALENDAR_ID,calendar);v.put(CalendarContract.Events.DTSTART,begin);v.put(CalendarContract.Events.DTEND,finish);v.put(CalendarContract.Events.ALL_DAY,day?1:0);v.put(CalendarContract.Events.EVENT_TIMEZONE,zone(start,day));v.put(CalendarContract.Events.CUSTOM_APP_PACKAGE,c.getPackageName());v.put(CalendarContract.Events.CUSTOM_APP_URI,marker);int partial=r.skippedComponents;for(RestoreText.Property p:r.fields){switch(p.name){case "SUMMARY":v.put(CalendarContract.Events.TITLE,p.text());break;case "DESCRIPTION":v.put(CalendarContract.Events.DESCRIPTION,p.text());break;case "LOCATION":v.put(CalendarContract.Events.EVENT_LOCATION,p.text());break;case "STATUS":v.put(CalendarContract.Events.STATUS,p.value.equalsIgnoreCase("CANCELLED")?CalendarContract.Events.STATUS_CANCELED:p.value.equalsIgnoreCase("TENTATIVE")?CalendarContract.Events.STATUS_TENTATIVE:CalendarContract.Events.STATUS_CONFIRMED);break;case "UID":case "DTSTAMP":case "DTSTART":case "DTEND":case "DURATION":break;default:partial++;}}
   io.check();android.net.Uri saved=c.getContentResolver().insert(CalendarContract.Events.CONTENT_URI,v);if(saved==null)throw new IOException("CALENDAR_WRITE");journal.put(key,"calendar",saved.toString(),partial>0?"partial":"done",-1,"");result.imported++;if(partial>0)result.partial++;
  }catch(SecurityException denied){throw denied;}catch(Exception error){result.failed++;}finally{progress.update("calendar",result.imported,result.existing,result.partial,result.failed);}}}if(index==0)throw new IOException("RESTORE_FORMAT");return result;
 }
 private static boolean writable(Context c,long id){try(Cursor q=c.getContentResolver().query(ContentUris.withAppendedId(CalendarContract.Calendars.CONTENT_URI,id),new String[]{CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL},null,null,null)){return q!=null&&q.moveToFirst()&&q.getInt(0)>=CalendarContract.Calendars.CAL_ACCESS_CONTRIBUTOR;}}
 private static String zone(RestoreText.Property p,boolean day)throws IOException {if(day||p.value.endsWith("Z"))return "UTC";String zone=p.params.get("TZID");if(zone==null||!Arrays.asList(TimeZone.getAvailableIDs()).contains(zone))throw new IOException("CALENDAR_ZONE");return zone;}
 static long date(RestoreText.Property p,boolean day)throws IOException {String pattern=day?"yyyyMMdd":p.value.endsWith("Z")?"yyyyMMdd'T'HHmmss'Z'":"yyyyMMdd'T'HHmmss";if(!p.value.matches(day?"[0-9]{8}":p.value.endsWith("Z")?"[0-9]{8}T[0-9]{6}Z":"[0-9]{8}T[0-9]{6}"))throw new IOException("CALENDAR_DATE");SimpleDateFormat f=new SimpleDateFormat(pattern,Locale.US);f.setLenient(false);f.setTimeZone(TimeZone.getTimeZone(zone(p,day)));try{return f.parse(p.value).getTime();}catch(Exception error){throw new IOException("CALENDAR_DATE");}}
}
