package in.chinatech.mimoverengine;
import android.Manifest;
import android.app.Activity;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.ImageFormat;
import android.graphics.SurfaceTexture;
import android.hardware.camera2.*;
import android.hardware.camera2.params.StreamConfigurationMap;
import android.media.*;
import android.os.*;
import android.util.Size;
import android.view.*;
import android.widget.*;
import java.nio.ByteBuffer;
import java.util.*;
import in.chinatech.mimoverzxing.*;
import in.chinatech.mimoverzxing.common.HybridBinarizer;
/** Camera frames stay in memory; no external camera or photo persistence. */
public final class LiveQrActivity extends Activity {
 private TextureView preview;private TextView feedback;private CameraDevice camera;private CameraCaptureSession session;private ImageReader images;private Surface display;private HandlerThread worker;private Handler background;private final Handler main=new Handler(Looper.getMainLooper());private volatile int epoch;private volatile boolean resumed,completed;private long nextFrame;private volatile long processedFrames;
 @Override protected void attachBaseContext(Context base){super.attachBaseContext(new BridgeContext(base));}
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE|WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,48,24,24);feedback=new TextView(this);feedback.setText(R.string.scan_live_title);feedback.setTextSize(20);feedback.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);root.addView(feedback);preview=new TextureView(this);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));Button cancel=new Button(this);cancel.setText(R.string.cancel);cancel.setMinHeight(56);cancel.setOnClickListener(v->finish());root.addView(cancel);setContentView(root);worker=new HandlerThread("ctss-camera");worker.start();background=new Handler(worker.getLooper());preview.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){open();}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){close();return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}});}
 @Override protected void onResume(){super.onResume();resumed=true;if(preview.isAvailable())open();}
 private synchronized void open(){if(!resumed||completed||camera!=null||!preview.isAvailable())return;if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){feedback.setText(R.string.camera_denied);return;}final int attempt=++epoch;CameraManager manager=getSystemService(CameraManager.class);try{String chosen=null;for(String id:manager.getCameraIdList()){CameraCharacteristics c=manager.getCameraCharacteristics(id);Integer facing=c.get(CameraCharacteristics.LENS_FACING);if(chosen==null)chosen=id;if(facing!=null&&facing==CameraCharacteristics.LENS_FACING_BACK){chosen=id;break;}}if(chosen==null)throw new IllegalStateException();StreamConfigurationMap map=manager.getCameraCharacteristics(chosen).get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);if(map==null)throw new IllegalStateException();Size size=null;for(Size s:map.getOutputSizes(ImageFormat.YUV_420_888))if(s.getWidth()<=1280&&s.getHeight()<=1280&&(long)s.getWidth()*s.getHeight()<=1280*720){if(size==null||Math.abs((long)s.getWidth()*s.getHeight()-640*480)<Math.abs((long)size.getWidth()*size.getHeight()-640*480))size=s;}if(size==null)throw new IllegalStateException();final Size selected=size;manager.openCamera(chosen,new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){synchronized(LiveQrActivity.this){if(attempt!=epoch||!resumed||completed){c.close();return;}camera=c;configure(c,selected,attempt);}}public void onDisconnected(CameraDevice c){c.close();failure(attempt);}public void onError(CameraDevice c,int error){c.close();failure(attempt);}},background);}catch(Exception e){failure(attempt);}}
 private void configure(CameraDevice c,Size size,int attempt){try{SurfaceTexture texture=preview.getSurfaceTexture();if(texture==null)throw new IllegalStateException();texture.setDefaultBufferSize(size.getWidth(),size.getHeight());display=new Surface(texture);images=ImageReader.newInstance(size.getWidth(),size.getHeight(),ImageFormat.YUV_420_888,2);images.setOnImageAvailableListener(reader->frame(reader,attempt),background);List<Surface> surfaces=Arrays.asList(display,images.getSurface());c.createCaptureSession(surfaces,new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession s){synchronized(LiveQrActivity.this){if(attempt!=epoch||!resumed||completed){s.close();return;}session=s;try{CaptureRequest.Builder request=c.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);for(Surface target:surfaces)request.addTarget(target);int[] af=getSystemService(CameraManager.class).getCameraCharacteristics(c.getId()).get(CameraCharacteristics.CONTROL_AF_AVAILABLE_MODES);if(af!=null)for(int mode:af)if(mode==CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE){request.set(CaptureRequest.CONTROL_AF_MODE,mode);break;}s.setRepeatingRequest(request.build(),null,background);}catch(Exception e){failure(attempt);}}}public void onConfigureFailed(CameraCaptureSession s){s.close();failure(attempt);}},background);}catch(Exception e){failure(attempt);}}
 private void frame(ImageReader reader,int attempt){Image image=null;try{image=reader.acquireLatestImage();if(image==null||attempt!=epoch||!resumed||completed)return;long now=SystemClock.elapsedRealtime();if(now<nextFrame)return;nextFrame=now+350;int width=image.getWidth(),height=image.getHeight();Image.Plane plane=image.getPlanes()[0];ByteBuffer bytes=plane.getBuffer();int row=plane.getRowStride(),pixel=plane.getPixelStride(),origin=bytes.position();byte[] luminance=new byte[width*height];for(int y=0;y<height;y++)for(int x=0;x<width;x++)luminance[y*width+x]=bytes.get(origin+y*row+x*pixel);processedFrames++;LuminanceSource source=new PlanarYUVLuminanceSource(luminance,width,height,0,0,width,height,false);Map<DecodeHintType,Object> hints=new EnumMap<>(DecodeHintType.class);hints.put(DecodeHintType.POSSIBLE_FORMATS,Collections.singletonList(BarcodeFormat.QR_CODE));hints.put(DecodeHintType.TRY_HARDER,true);String code=null;for(int rotation=0;rotation<4;rotation++){try{code=new MultiFormatReader().decode(new BinaryBitmap(new HybridBinarizer(source)),hints).getText();break;}catch(NotFoundException ignored){byte[] rotated=new byte[width*height];for(int y=0;y<height;y++)for(int x=0;x<width;x++)rotated[(width-1-x)*height+y]=luminance[y*width+x];luminance=rotated;int swap=width;width=height;height=swap;source=new PlanarYUVLuminanceSource(luminance,width,height,0,0,width,height,false);}}if(code==null)return;try{ProtocolCore.Pairing.parse(code,System.currentTimeMillis());}catch(Exception invalid){main.post(()->{if(attempt==epoch&&resumed&&!completed)feedback.setText(R.string.qr_invalid);});return;}final String valid=code;main.post(()->{if(attempt!=epoch||!resumed||completed)return;completed=true;setResult(RESULT_OK,new Intent().putExtra("code",valid));finish();});}catch(Exception ignored){}finally{if(image!=null)image.close();}}
 private void failure(int attempt){main.post(()->{if(attempt!=epoch||!resumed||completed)return;close();feedback.setText(R.string.qr_failed);});}
 private synchronized void close(){epoch++;if(session!=null){session.close();session=null;}if(camera!=null){camera.close();camera=null;}if(images!=null){images.close();images=null;}if(display!=null){display.release();display=null;}}
 @Override protected void onPause(){resumed=false;close();super.onPause();}
 @Override protected void onDestroy(){close();if(worker!=null)worker.quitSafely();super.onDestroy();}
}
