package in.chinatech.smartswitchbridge;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.*;
import android.provider.DocumentsContract;
import android.text.format.Formatter;
import android.view.*;
import android.widget.*;
import java.util.*;

/** Original Samsung resources, driven by the authenticated local transfer controller. */
public final class OriginalFlowActivity extends Activity implements OriginalViews.Callbacks,TransferEngine.Listener,QrReader.Listener {
 private static final int FOLDER=410,IMAGE=411,FILES=412,WIFI=413,LAN=414,NOTIFY=415,CAMERA=416;
 private static final String PREF="chinatech-original-flow-ui";
 private OriginalViews views; private View root; private OriginalViews.Stage stage;
 private TransferEngine engine; private QrReader reader; private OriginalScanner scanner;
 private boolean receiving,started,destroyed,completed,foreground; private String detail,renderedCode,dialogKey;
 private long after,minimumSession,observedSession; private final ArrayList<Long> pages=new ArrayList<>();
 private AlertDialog dialog; private int permissionAction,queuedNetwork; private String pendingCode,lastCode;
 private final Handler handler=new Handler(Looper.getMainLooper());
 private final Runnable refresh=new Runnable(){public void run(){if(destroyed)return;changed();handler.postDelayed(this,1000);}};
 @Override protected void attachBaseContext(Context c){super.attachBaseContext(new BridgeContext(c));}
 @Override public void onCreate(Bundle saved){setTheme(0x7f1201c6);super.onCreate(saved);getWindow().requestFeature(Window.FEATURE_NO_TITLE);
  receiving=getIntent().getBooleanExtra("receiving",getSharedPreferences(PREF,MODE_PRIVATE).getBoolean("receiving",false));getSharedPreferences(PREF,MODE_PRIVATE).edit().putBoolean("receiving",receiving).apply();
  if(saved!=null){started=saved.getBoolean("started");completed=saved.getBoolean("completed");permissionAction=saved.getInt("permissionAction");queuedNetwork=saved.getInt("queuedNetwork");pendingCode=saved.getString("pendingCode");lastCode=saved.getString("lastCode");detail=saved.getString("detail");after=saved.getLong("after");long[] h=saved.getLongArray("pages");if(h!=null)for(long n:h)pages.add(n);}
  engine=TransferEngine.get(this);if(engine.hasTransferSession())receiving=engine.receivingMode;observedSession=engine.uiSession;minimumSession=saved!=null?saved.getLong("minimumSession",observedSession):getIntent().getBooleanExtra("fresh",false)&&!engine.hasTransferSession()?observedSession+1:observedSession;if(saved!=null&&saved.getLong("observedSession",-1)!=observedSession)completed=false;reader=QrReader.get(this,this);views=new OriginalViews(this,this);engine.attach(this);if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,this::back);changed();
  if(!started&&!engine.isActive()){started=true;handler.post(()->{if(receiving)startReceiver();else startScanner();});}
 }
 private void show(OriginalViews.Stage desired){if(stage==desired&&root!=null)return;stopScanner();stage=desired;renderedCode=null;root=views.render(stage);setContentView(root);
  root.setOnApplyWindowInsetsListener((v,i)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets b=i.getInsets(WindowInsets.Type.systemBars());v.setPadding(b.left,b.top,b.right,b.bottom);}else v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});
 }
 private String tr(String zh,String it,String en){String l=getResources().getConfiguration().getLocales().get(0).getLanguage();return "zh".equals(l)?zh:"it".equals(l)?it:en;}
 private String size(long n){return Formatter.formatShortFileSize(this,n);}
 private String label(String type){int i=new ArrayList<>(FlowCatalogCodec.TYPES).indexOf(type);int[] ids={R.string.category_photos,R.string.category_videos,R.string.category_audio,R.string.category_files,R.string.category_contacts,R.string.category_calendar,R.string.category_apps};return i>=0?getString(ids[i]):type;}
 private String status(){if(engine.uiSession<minimumSession&&(engine.status==R.string.sender_complete||engine.status==R.string.receiver_complete||engine.status==R.string.receiver_complete_unconfirmed))return getString(R.string.ready);Object[] args=engine.statusArgs;if(engine.status==R.string.file_failed&&args.length==2&&args[1] instanceof Integer)args=new Object[]{args[0],getString((Integer)args[1])};return getString(engine.status,args);}
 @Override public void changed(){if(destroyed||engine==null)return;
  if(observedSession!=engine.uiSession){observedSession=engine.uiSession;completed=false;}boolean bound=observedSession>=minimumSession&&receiving==engine.receivingMode;if(queuedNetwork!=0&&foreground&&!engine.isActive()){int queued=queuedNetwork;queuedNetwork=0;handler.post(()->network(queued));}boolean complete=bound&&(completed||engine.status==R.string.sender_complete||engine.status==R.string.receiver_complete||engine.status==R.string.receiver_complete_unconfirmed);if(complete)completed=true;
  String phase=bound?engine.flow.phase:"idle";
  OriginalViews.Stage desired=complete?(receiving?OriginalViews.Stage.COMPLETE_RECEIVER:OriginalViews.Stage.COMPLETE_SENDER):"select".equals(phase)&&receiving||"review".equals(phase)&&!receiving?OriginalViews.Stage.SELECT:"transfer".equals(phase)||"prepare".equals(phase)?(receiving?OriginalViews.Stage.RECEIVING:OriginalViews.Stage.SENDING):engine.serverPair!=null||!receiving&&!engine.isActive()?OriginalViews.Stage.QR:OriginalViews.Stage.CONNECTING;
  show(desired);getWindow().setFlags(engine.isActive()?WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON:0,WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
  if(complete){renderComplete();return;}
  if(desired==OriginalViews.Stage.SELECT){renderSelection();}
  else if(desired==OriginalViews.Stage.SENDING||desired==OriginalViews.Stage.RECEIVING){views.text("text_header_title",tr("正在传输","Trasferimento in corso","Transferring"));views.text("text_header_description",status());views.text("text_remaining_time",tr("正在校验并保存资料","Verifica e salvataggio dei dati","Verifying and saving data"));views.text("text_sending_item_1",engine.currentName());views.text("text_sending_item_count",receiving?Long.toString(engine.receivedCount):getString(R.string.scan_selection,engine.scannedCount(),engine.selectedCount()));views.progress(engine.totalBytes>0?100f*engine.transferredBytes/engine.totalBytes:Float.NaN);views.text("button_footer_left",getString(R.string.stop));}
  else {views.text("text_header_title",tr("开始连接","Avvia connessione","Start connecting"));views.text("text_header_description",engine.isActive()?status():receiving?getString(R.string.receiver_title):tr("扫描新手机上的二维码","Scansiona il codice QR sul nuovo telefono","Scan the QR code on the new phone"));
   if(desired==OriginalViews.Stage.CONNECTING){views.text("text_searching_progress",status());views.text("text_connecting_state",status());views.text("text_connecting_help",getString(R.string.recovery_notice));}
   else {ProtocolCore.Pairing p=engine.serverPair;String code=p==null?null:p.encode();if(receiving){if(code!=null&&!code.equals(renderedCode)){try{views.qr(QrCodec.encode(code));renderedCode=code;}catch(Exception e){error(R.string.qr_failed);}}}else if(!engine.isActive()&&scanner==null&&checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED&&(engine.status==R.string.ready||engine.uiSession<minimumSession))startScanner();else if(!receiving&&scanner==null)views.qrIdle();
    View options=root.findViewById(0x7f09046a);if(options!=null)options.setOnClickListener(v->connectionOptions());views.text("text_qr_bottom_description",receiving?getString(R.string.code_notice):getString(R.string.qr_sensitive_photo));}
   views.text("button_footer_left",engine.isActive()?getString(R.string.stop):getString(R.string.close));views.text("button_footer_right",engine.isActive()&&engine.serverPair==null?"":tr("连接选项","Opzioni di connessione","Connection options"));
  }
  String challenge=engine.pendingConfirmation;
  if(challenge!=null)confirmation("peer:"+challenge,getString(R.string.confirm_peer),getString(R.string.peer_explanation,challenge),()->engine.decide(true),()->engine.decide(false));
  else if(dialogKey!=null&&dialogKey.startsWith("peer:")){dialog.dismiss();dialog=null;dialogKey=null;}
 }
 private void renderSelection(){boolean editable=receiving&&"select".equals(engine.flow.phase);List<OriginalViews.Row> rows=new ArrayList<>();
  try{if(detail!=null&&editable){for(FlowCatalogStore.Row r:engine.flow.catalog.page(detail,after))rows.add(new OriginalViews.Row(r.entry.id,r.entry.name,1,r.entry.size,r.selected,true,false));views.details(rows);}
   else {detail=null;for(String type:FlowCatalogCodec.TYPES){long count=receiving?engine.flow.catalog.count(type,false):engine.store.countSelectedCategory(type);if(count==0)continue;long chosen=receiving?engine.flow.catalog.count(type,true):count;long bytes=receiving?engine.flow.catalog.bytes(type,false):engine.store.bytesSelectedCategory(type);rows.add(new OriginalViews.Row(type,label(type),count,bytes,count>0&&chosen==count,editable&&count>0,false));}views.categories(rows);}
   long chosen=receiving?engine.flow.catalog.count(null,true):engine.selectedCount();long bytes=receiving?engine.flow.catalog.bytes(null,true):engine.store.bytesSelectedCategory(null);
   views.text("text_header_title",detail!=null?label(detail):editable?tr("选择要传输的资料","Scegli i dati da trasferire","Choose data to transfer"):tr("确认发送资料","Conferma i dati da inviare","Confirm data to send"));
   String scope=receiving?tr("仅显示旧机已授权的资料。点击查看扫描范围。","Sono mostrati i dati autorizzati. Tocca per vedere l’ambito della scansione.","Only authorized data is shown. Tap to view the scan scope."):tr("新手机已选择以下资料，请核对后发送。","Il nuovo telefono ha selezionato questi dati. Verifica prima dell’invio.","The new phone selected these items. Review before sending.");
   views.text("text_header_description",scope);View scopeView=root.findViewById(0x7f0903e3);if(scopeView!=null&&receiving)scopeView.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(getString(R.string.scan_phone)).setMessage(tr("以下权限用于手机扫描；通过系统文件选择器授权的文件单独计入。\n","Questi permessi riguardano la scansione. I file autorizzati dal selettore di sistema sono conteggiati separatamente.\n","These permissions cover phone scanning. Files authorized through the system picker are counted separately.\n")+scopeText(engine.flow.scope)).setPositiveButton(R.string.close,null).show());views.text("text_selected_item_count",Long.toString(chosen));views.text("text_selected_item_size",size(bytes));views.text("button_footer_left",detail!=null?getString(R.string.previous_page):getString(R.string.stop));views.text("button_footer_right",detail!=null?getString(R.string.next_page):getString(R.string.start_transfer));
   View next=root.findViewById(0x7f090094);if(next!=null)next.setEnabled(detail!=null?!rows.isEmpty()&&engine.flow.catalog.next(engine.flow.catalog.page(detail,after).get(rows.size()-1).n,detail,false)!=null:chosen>0);
  }catch(Exception e){error(R.string.action_failed);}
 }
 private String scopeText(int flags){StringBuilder b=new StringBuilder();String[] names={"photos","videos","audio","contacts","calendar"};int[] bits={1,2,4,8,16};for(int i=0;i<bits.length;i++)if((flags&bits[i])==0)b.append(label(names[i])).append(": ").append(getString(R.string.permission_denied)).append('\n');if((flags&32)!=0)b.append(getString(R.string.partial_media)).append('\n');if((flags&64)==0)b.append(getString(R.string.phone_not_scanned));if(engine.flow.scanFailures>0)b.append('\n').append(getString(R.string.scan_errors,engine.flow.scanFailures));return b.toString();}
 private void renderComplete(){views.text("text_header_title",engine.status==R.string.receiver_complete_unconfirmed?tr("资料已保存，完成确认中断","Dati salvati, conferma finale interrotta","Data saved; final confirmation interrupted"):tr("传输完成","Trasferimento completato","Transfer complete"));views.text("text_header_description",engine.status==R.string.receiver_complete?tr("已保存 "+engine.receivedCount+" 项资料，导入请单独核对。","Salvati "+engine.receivedCount+" elementi. Verifica separatamente l’importazione.","Saved "+engine.receivedCount+" items. Check imports separately."):engine.status==R.string.sender_complete?tr("已发送 "+engine.selectedCount()+" 项资料。原手机资料保留。","Inviati "+engine.selectedCount()+" elementi. Gli originali sono conservati.","Sent "+engine.selectedCount()+" items. Originals kept."):status());views.text("button_footer_right",getString(R.string.close));views.text("button_footer_left",receiving?tr("恢复选项","Opzioni di ripristino","Restore options"):"");
  long count=receiving?engine.receivedCount:engine.selectedCount();if(receiving){views.text("text_total_count",Long.toString(count));views.text("text_total_size",size(engine.totalBytes));List<OriginalViews.Row> rows=new ArrayList<>();for(String t:FlowCatalogCodec.TYPES){long n=engine.flow.catalog.count(t,true);if(n>0)rows.add(new OriginalViews.Row(t,label(t),n,engine.flow.catalog.bytes(t,true),false,false,false));}views.results(rows);}else{views.text("text_data_transferred",count+" · "+size(engine.totalBytes));views.text("text_galaxy_device",getString(R.string.receiver_title));views.text("text_this_phone",Build.MODEL);}}
 public boolean toggleAll(boolean selected){if(!receiving||!"select".equals(engine.flow.phase))return false;boolean ok=engine.flow.catalog.select(detail,selected);if(ok)changed();return ok;}
 public boolean toggle(String key,boolean selected){if(!receiving||!"select".equals(engine.flow.phase))return false;boolean ok=FlowCatalogCodec.TYPES.contains(key)?engine.flow.catalog.select(key,selected):engine.flow.catalog.selectObject(key,selected);if(ok)changed();return ok;}
 public void open(String key){if(FlowCatalogCodec.TYPES.contains(key)&&receiving&&"select".equals(engine.flow.phase)){detail=key;after=0;pages.clear();changed();}}
 public void next(){if(stage==OriginalViews.Stage.SELECT){if(detail!=null){try{List<FlowCatalogStore.Row> rows=engine.flow.catalog.page(detail,after);if(!rows.isEmpty()&&engine.flow.catalog.next(rows.get(rows.size()-1).n,detail,false)!=null){pages.add(after);after=rows.get(rows.size()-1).n;changed();}}catch(Exception e){error(R.string.action_failed);}return;}if(receiving){try{engine.flow.submit();changed();}catch(Exception e){error(R.string.action_failed);}}else engine.flow.approve(true);return;}
  if(stage==OriginalViews.Stage.COMPLETE_SENDER||stage==OriginalViews.Stage.COMPLETE_RECEIVER){finish();return;}connectionOptions();}
 public void back(){if(stage==OriginalViews.Stage.SELECT&&detail!=null){if(!pages.isEmpty())after=pages.remove(pages.size()-1);else{detail=null;after=0;}changed();return;}
  if(stage==OriginalViews.Stage.COMPLETE_RECEIVER){restoreOptions();return;}if(engine.isActive()){confirmation("stop",getString(R.string.stop),getString(R.string.recovery_notice),()->{queuedNetwork=0;engine.stop();finish();},()->{});}else finish();}
 @Override public void onBackPressed(){back();}
 private void connectionOptions(){if(dialog!=null)return;String[] options=receiving?new String[]{getString(R.string.create_hotspot),getString(R.string.router_fallback),getString(R.string.manual_hotspot_pairing),getString(R.string.copy_code),getString(R.string.choose_folder)}:new String[]{getString(R.string.qr_camera),getString(R.string.qr_image),getString(R.string.paste_code),getString(R.string.choose_files),getString(R.string.scan_phone),tr("已手动连接 Wi-Fi，继续","Wi-Fi collegato manualmente: continua","Wi-Fi joined manually: continue")};
  dialog=new AlertDialog.Builder(this).setTitle(tr("连接选项","Opzioni di connessione","Connection options")).setItems(options,(d,i)->{dialog=null;if(receiving){if(i==3){copy();return;}if(engine.isActive()){engine.stop();error(R.string.cancelled);return;}if(i==0)network(1);else if(i==1)network(2);else if(i==2)manual();else folder();}else{if(i==5&&!engine.isActive()){if(lastCode==null){error(R.string.paste_code);return;}pendingCode=lastCode;network(4);}else if(i==0)startScanner();else if(i==1)startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),IMAGE);else if(i==2)paste();else if(i==4&&!engine.isActive())new AlertDialog.Builder(this).setMessage(R.string.rescan_notice).setNegativeButton(R.string.cancel,null).setPositiveButton(R.string.continue_action,(again,w)->{completed=false;minimumSession=engine.uiSession+1;engine.clearSelection();OriginalPermissionController.launch(this,new Intent(this,OriginalFlowActivity.class).putExtra("receiving",false).putExtra("fresh",true));}).show();else if(i==3&&!engine.isActive())startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),FILES);}}).setNegativeButton(R.string.cancel,null).create();dialog.setOnDismissListener(d->{dialog=null;dialogKey=null;});dialog.show();}
 private void startReceiver(){if(engine.directory==null)folder();else network(1);}
 private void folder(){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),FOLDER);}
 private void network(int action){permissionAction=action;if((action==1||action==3&&autoWifi())&&checkSelfPermission(Build.VERSION.SDK_INT>=33?Manifest.permission.NEARBY_WIFI_DEVICES:Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(WifiPermissions.requestFor(Build.VERSION.SDK_INT),WIFI);return;}if(Build.VERSION.SDK_INT>=37&&checkSelfPermission("android.permission.ACCESS_LOCAL_NETWORK")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.ACCESS_LOCAL_NETWORK"},LAN);return;}if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},NOTIFY);return;}runNetwork();}
 private boolean autoWifi(){try{return pendingCode!=null&&Build.VERSION.SDK_INT>=29&&!ProtocolCore.Pairing.parse(pendingCode,System.currentTimeMillis()).ssid.isEmpty();}catch(Exception e){return false;}}
 private void runNetwork(){int action=permissionAction;permissionAction=0;if(engine.isActive()&&!engine.hasTransferSession()){queuedNetwork=action;return;}try{if(action==1)engine.createHotspot();else if(action==2){engine.useRouter();engine.prepareReceiver();}else if((action==3||action==4)&&pendingCode!=null){String code=pendingCode;pendingCode=null;if(action==4)engine.sendUsingExisting(code);else engine.send(code);}}catch(Exception e){error(R.string.action_failed);}}
 private void startScanner(){if(receiving||engine.isActive())return;if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},CAMERA);return;}show(OriginalViews.Stage.QR);if(scanner==null)try{scanner=new OriginalScanner(root.findViewById(0x7f090329),this::read);scanner.resume();views.qrScanner();}catch(Exception e){scanner=null;error(R.string.qr_failed);}}
 private void stopScanner(){if(scanner!=null){scanner.close();scanner=null;}}
 public void read(String code){if(destroyed||!foreground||receiving||engine.isActive())return;try{ProtocolCore.Pairing p=ProtocolCore.Pairing.parse(code,System.currentTimeMillis());stopScanner();lastCode=code;if(!p.ssid.isEmpty()&&Build.VERSION.SDK_INT<29){new AlertDialog.Builder(this).setTitle(R.string.manual_wifi_title).setMessage(getString(R.string.manual_wifi_instructions,p.ssid,p.password)).setNegativeButton(R.string.cancel,null).setPositiveButton(R.string.open_wifi_settings,(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_WIFI_SETTINGS))).show();return;}pendingCode=code;network(3);}catch(Exception e){error(R.string.qr_failed);}}
 public void state(int id){error(id);}
 private void paste(){EditText input=new EditText(this);input.setMinHeight(48);input.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD);new AlertDialog.Builder(this).setTitle(R.string.paste_code).setView(input).setNegativeButton(R.string.cancel,null).setPositiveButton(R.string.continue_action,(d,w)->{String c=input.getText().toString();input.setText("");read(c);}).show();}
 private void manual(){LinearLayout box=new LinearLayout(this);box.setOrientation(1);EditText ssid=new EditText(this),pass=new EditText(this);ssid.setHint(R.string.manual_hotspot_ssid);pass.setHint(R.string.manual_hotspot_password);pass.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);box.addView(ssid);box.addView(pass);new AlertDialog.Builder(this).setTitle(R.string.manual_hotspot_pairing).setMessage(R.string.manual_hotspot_notice).setView(box).setNegativeButton(R.string.open_wifi_settings,(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_WIRELESS_SETTINGS))).setPositiveButton(R.string.continue_action,(d,w)->{String n=ssid.getText().toString(),p=pass.getText().toString();ssid.setText("");pass.setText("");engine.configureManualHotspot(n,p);}).show();}
 private void copy(){ProtocolCore.Pairing p=engine.serverPair;if(p==null)return;ClipData clip=ClipData.newPlainText(getString(R.string.pairing_code),p.encode());if(Build.VERSION.SDK_INT>=33){PersistableBundle extras=new PersistableBundle();extras.putBoolean(ClipDescription.EXTRA_IS_SENSITIVE,true);clip.getDescription().setExtras(extras);}getSystemService(ClipboardManager.class).setPrimaryClip(clip);Toast.makeText(this,R.string.code_copied,Toast.LENGTH_SHORT).show();}
 private void restoreOptions(){String[] options={getString(R.string.gallery_import),getString(R.string.import_vcf)};new AlertDialog.Builder(this).setTitle(tr("恢复选项","Opzioni di ripristino","Restore options")).setItems(options,(d,i)->{if(i==0)engine.importGallery();else{Uri uri=engine.lastVcf();if(uri!=null)try{Intent intent=new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"text/x-vcard").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);intent.setClipData(ClipData.newRawUri("VCF",uri));startActivity(intent);}catch(RuntimeException e){error(R.string.import_unavailable);}}}).setNegativeButton(R.string.close,null).show();}
 private void confirmation(String key,String title,String message,Runnable yes,Runnable no){if(key.equals(dialogKey))return;if(dialog!=null)dialog.dismiss();dialogKey=key;dialog=new AlertDialog.Builder(this).setTitle(title).setMessage(message).setCancelable(false).setNegativeButton(R.string.reject,(d,w)->{dialog=null;dialogKey=null;no.run();}).setPositiveButton(R.string.approve,(d,w)->{dialog=null;dialogKey=null;yes.run();}).show();}
 private void error(int id){Toast.makeText(this,id,Toast.LENGTH_LONG).show();}
 @Override public void onRequestPermissionsResult(int code,String[] p,int[] r){super.onRequestPermissionsResult(code,p,r);if(code==CAMERA){if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)startScanner();else error(R.string.camera_denied);return;}if(code==WIFI||code==LAN||code==NOTIFY){boolean granted=true;for(String x:p)granted&=checkSelfPermission(x)==PackageManager.PERMISSION_GRANTED;if(!granted&&code!=NOTIFY){permissionAction=0;pendingCode=null;error(R.string.permission_denied);return;}if(code==NOTIFY)runNetwork();else network(permissionAction);}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;try{if(request==FOLDER&&data.getData()!=null){Uri u=data.getData();if(!DocumentsContract.isTreeUri(u))throw new SecurityException();getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);engine.setDirectory(u);network(1);}else if(request==IMAGE&&data.getData()!=null)reader.image(data.getData());else if(request==FILES){List<Uri> uris=new ArrayList<>();if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());for(Uri u:uris)try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}engine.addUris(uris);}}catch(RuntimeException e){error(R.string.permission_denied);}}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(!intent.hasExtra("receiving"))return;boolean role=intent.getBooleanExtra("receiving",receiving);if(role!=receiving&&engine.isActive()){error(R.string.cancelled);return;}if(role!=receiving){receiving=role;minimumSession=intent.getBooleanExtra("fresh",false)&&!engine.hasTransferSession()?engine.uiSession+1:engine.uiSession;completed=false;detail=null;pages.clear();after=0;started=true;getSharedPreferences(PREF,MODE_PRIVATE).edit().putBoolean("receiving",receiving).apply();stopScanner();stage=null;changed();if(receiving)startReceiver();else startScanner();}}
 @Override protected void onSaveInstanceState(Bundle b){b.putBoolean("started",started);b.putBoolean("completed",completed);b.putLong("minimumSession",minimumSession);b.putLong("observedSession",observedSession);b.putInt("permissionAction",permissionAction);b.putInt("queuedNetwork",queuedNetwork);b.putString("pendingCode",pendingCode);b.putString("lastCode",lastCode);b.putString("detail",detail);b.putLong("after",after);long[] h=new long[pages.size()];for(int i=0;i<h.length;i++)h[i]=pages.get(i);b.putLongArray("pages",h);super.onSaveInstanceState(b);}
 @Override protected void onResume(){super.onResume();foreground=true;if(views!=null)views.resume();if(scanner!=null)scanner.resume();handler.post(refresh);}
 @Override protected void onPause(){foreground=false;handler.removeCallbacks(refresh);if(scanner!=null)scanner.pause();if(views!=null)views.pause();super.onPause();}
 @Override protected void onDestroy(){destroyed=true;handler.removeCallbacks(refresh);stopScanner();if(dialog!=null)dialog.dismiss();if(reader!=null)reader.detach(this);if(engine!=null)engine.detach(this);super.onDestroy();}
}
