#!/usr/bin/env python3
"""Inventory exact duplicate PNG evidence; optionally replace copies with APFS COW clones.

All paths and bytes remain unchanged. Unlike hard links, subsequent edits stay independent.
No branches, references, JSON exports, customer records or historical evidence are deleted.
"""
import argparse
import ctypes
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile


def digest(path):
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def signature(path):
    stat = path.stat()
    return stat.st_ino, stat.st_size, stat.st_mtime_ns


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--report", required=True)
    parser.add_argument("--exclude", action="append", default=[], help="Project-relative evidence directory currently in use")
    args = parser.parse_args()
    root = Path.cwd().resolve()
    git_root = Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()).resolve()
    if root != git_root:
        parser.error("Run from the canonical project root.")
    report = Path(args.report).resolve()
    if not report.is_relative_to(root):
        parser.error("Keep the report inside the current project.")
    if args.apply and sys.platform != "darwin":
        parser.error("APFS clone mode requires macOS; inventory is available elsewhere.")
    excluded = [(root / name).resolve() for name in args.exclude]
    if any(not path.is_relative_to(root) for path in excluded):
        parser.error("Exclusions must remain inside the project.")
    groups = {}
    for directory in (root / "screenshots", root / "artifacts"):
        for path in sorted(directory.rglob("*.png")):
            if path.is_symlink() or not path.is_file() or not path.resolve().is_relative_to(root):
                continue
            # Keep evidence currently being generated by other work out of the batch.
            if any(path.is_relative_to(prefix) for prefix in excluded):
                continue
            groups.setdefault(digest(path), []).append(path)
    results = []
    clonefile = ctypes.CDLL(None, use_errno=True).clonefile if args.apply else None
    if clonefile:
        clonefile.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]
        clonefile.restype = ctypes.c_int
    for sha, paths in groups.items():
        if len(paths) < 2:
            continue
        source = paths[0]
        for duplicate in paths[1:]:
            row = {"source": str(source.relative_to(root)), "path": str(duplicate.relative_to(root)),
                   "sha256": sha, "bytes": duplicate.stat().st_size, "status": "candidate"}
            if args.apply:
                before = signature(duplicate)
                descriptor, temporary = tempfile.mkstemp(prefix=".evidence-clone-", dir=duplicate.parent)
                os.close(descriptor)
                os.unlink(temporary)  # clonefile requires an absent destination.
                try:
                    if digest(source) != sha or digest(duplicate) != sha:
                        raise RuntimeError("Evidence changed since inventory; skipped")
                    if clonefile(os.fsencode(source), os.fsencode(temporary), 0):
                        raise OSError(ctypes.get_errno(), "clonefile unavailable on this volume")
                    if digest(Path(temporary)) != sha or signature(duplicate) != before:
                        raise RuntimeError("Concurrent modification or clone mismatch; skipped")
                    shutil.copystat(duplicate, temporary, follow_symlinks=False)
                    os.replace(temporary, duplicate)
                    row["status"] = "cloned_and_verified"
                except (OSError, RuntimeError) as error:
                    row.update(status="skipped", reason=str(error))
                finally:
                    if os.path.exists(temporary):
                        os.unlink(temporary)
            results.append(row)
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(json.dumps({"mode": "apply" if args.apply else "inventory", "files": results}, indent=2) + "\n")
    print(json.dumps({"duplicates": len(results), "cloned": sum(r["status"] == "cloned_and_verified" for r in results),
                      "logical_redundant_bytes": sum(r["bytes"] for r in results),
                      "physical_space_reclaimed": "not measured; APFS accounting differs from logical file sizes"}))


if __name__ == "__main__":
    main()
