package in.chinatech.phoneassistant;
import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
/** Real production stream helpers over bounded pipes; not Android/SQLite/provider runtime evidence. */
public final class TransferV2Test {
 static int assertions;static void ok(boolean yes,String message){if(!yes)throw new AssertionError(message);assertions++;}
 static void rejects(ProtocolTest.Checked action,String message)throws Exception{try{action.run();throw new AssertionError(message);}catch(IOException expected){assertions++;}}
 public static void main(String[] args)throws Exception {
  long start=1_000_000,expires=start+ProtocolCore.PAIR_TTL_MS;
  JoinPolicy.check(false,expires,expires,start,start);ok(true,"fresh admission accepted");
  rejects(()->JoinPolicy.check(false,expires,expires,expires,expires),"unpaired credential expires");
  JoinPolicy.check(true,expires,expires,start+24*60*60*1000L,start+24*60*60*1000L);ok(true,"confirmed transfer exceeds old two-hour deadline");
  rejects(()->JoinPolicy.check(false,expires,expires,start,expires),"monotonic admission expires despite wall-clock change");
  ProtocolCore.validateCount(10001);ProtocolCore.validateCount(1000000);ProtocolCore.validateCount(Long.MAX_VALUE);ok(true,"no total-file business threshold");rejects(()->ProtocolCore.validateCount(0),"zero manifest rejected");rejects(()->ProtocolCore.validateCount(-1),"negative count rejected");
  ok(ProtocolCore.addBytes(100,200)==300,"long size sum");rejects(()->ProtocolCore.addBytes(Long.MAX_VALUE,1),"total overflow fails closed");
  ManifestDigest left=new ManifestDigest(),right=new ManifestDigest();ByteArrayOutputStream perItem=new ByteArrayOutputStream();
  for(int i=0;i<10017;i++){ProtocolCore.Item item=new ProtocolCore.Item(ProtocolCore.token(16),"fixture-"+i+".txt","text/plain",i,ProtocolCore.sha256(new byte[]{(byte)i}));left.add(item);perItem.reset();ProtocolCore.writeItem(new DataOutputStream(perItem),item);right.add(ProtocolCore.readItem(new DataInputStream(new ByteArrayInputStream(perItem.toByteArray()))));}
  ok(left.count()==10017&&right.count()==10017,"streaming more than old ten-thousand file ceiling");ok(left.total()==(10016L*10017/2),"all-object long totals exact");ok(ProtocolCore.equal(left.finish(),right.finish()),"complete canonical streamed manifest digest matches");
  ProtocolCore.Item a=new ProtocolCore.Item(ProtocolCore.token(16),"a.txt","text/plain",1,new byte[32]),b=new ProtocolCore.Item(ProtocolCore.token(16),"b.txt","text/plain",2,new byte[32]);ManifestDigest ab=new ManifestDigest(),ba=new ManifestDigest();ab.add(a);ab.add(b);ba.add(b);ba.add(a);ok(!ProtocolCore.equal(ab.finish(),ba.finish()),"manifest order changes final digest");
  ProtocolCore.Pairing pairing=new ProtocolCore.Pairing("192.168.88.1",40000,ProtocolCore.token(16),System.currentTimeMillis()+60000,ProtocolCore.random(32),ProtocolCore.hex(ProtocolCore.random(32)));rejects(()->ProtocolCore.Pairing.parse(pairing.encode().replace(ProtocolCore.LAN_MAGIC+"|","CTPA1|"),System.currentTimeMillis()),"old alpha pairing refused");rejects(()->ProtocolCore.Pairing.parse(pairing.encode().replace(ProtocolCore.LAN_MAGIC+"|","CTPA3|"),System.currentTimeMillis()),"0.2 pairing refused after protocol upgrade");
  byte[] payload=new byte[201333];new Random(31).nextBytes(payload);chunkRoundTrip(payload,false);chunkRoundTrip(payload,true);
  ByteArrayOutputStream malicious=new ByteArrayOutputStream();new DataOutputStream(malicious).writeInt(ChunkTransport.CHUNK+1);rejects(()->ChunkTransport.receive(new DataInputStream(new ByteArrayInputStream(malicious.toByteArray())),new ByteArrayOutputStream(),new DataOutputStream(new ByteArrayOutputStream()),100000,()->{}),"oversized anonymous chunk refused");
  AtomicBoolean cancelled=new AtomicBoolean();InputStream finalRead=new ByteArrayInputStream(new byte[]{1}){public synchronized int read(byte[] bytes,int off,int length){int n=super.read(bytes,off,length);cancelled.set(true);return n;}};ByteArrayOutputStream wire=new ByteArrayOutputStream();rejects(()->ChunkTransport.send(finalRead,new DataOutputStream(wire),new DataInputStream(new ByteArrayInputStream(new byte[]{1})),1,()->{if(cancelled.get())throw new IOException("CANCELLED");}),"cancellation after final source read");ok(wire.size()==0,"cancelled final read does not publish a chunk");
  ok(RecoveryPolicy.retryable(new SocketException())&&RecoveryPolicy.retryable(new EOFException()),"broken transport retries");ok(!RecoveryPolicy.retryable(new FileNotFoundException())&&!RecoveryPolicy.retryable(new IOException("REMOTE_WRITE"))&&!RecoveryPolicy.retryable(new SecurityException()),"source/target/permission failures do not auto-retry");ok(RecoveryPolicy.MAX_RETRIES==5&&RecoveryPolicy.delay(5)<=10000,"bounded recovery avoids infinite stalls");
  ok(ScanPermissions.media(32).length==1&&ScanPermissions.media(33).length==3&&ScanPermissions.media(34).length==4,"scan permissions follow legacy/granular/selected-media versions");ok(Arrays.asList(ScanPermissions.media(37)).contains("android.permission.READ_MEDIA_VISUAL_USER_SELECTED"),"partial-photo permission remains explicit");
  ok(CalendarText.rule("FREQ=WEEKLY;BYDAY=MO,FR").equals("FREQ=WEEKLY;BYDAY=MO,FR"),"recurrence punctuation preserved");rejects(()->CalendarText.rule("FREQ=DAILY\r\nBEGIN:VEVENT"),"calendar line injection refused");
  System.out.println("{\"kind\":\"production v2 admission/10017-object manifest/chunk ACK/scan-permission/recovery helpers JVM evidence; not Android SQLite/phone evidence\",\"assertions\":"+assertions+",\"status\":\"passed\"}");
 }
 static void chunkRoundTrip(byte[] payload,boolean rejectWrite)throws Exception {
  PipedInputStream receiver=new PipedInputStream(ChunkTransport.CHUNK*3),sender=new PipedInputStream(4096);PipedOutputStream sendWire=new PipedOutputStream(receiver),replyWire=new PipedOutputStream(sender);ExecutorService worker=Executors.newSingleThreadExecutor();ByteArrayOutputStream destination=new ByteArrayOutputStream();try{Future<byte[]> received=worker.submit(()->{try(PipedInputStream in=receiver;PipedOutputStream out=replyWire){OutputStream target=rejectWrite?new OutputStream(){public void write(int b)throws IOException{throw new IOException("disk-full fixture");}public void write(byte[] b,int o,int n)throws IOException{throw new IOException("disk-full fixture");}}:destination;return ChunkTransport.receive(new DataInputStream(in),target,new DataOutputStream(out),payload.length,()->{});}});if(rejectWrite){try{ChunkTransport.send(new ByteArrayInputStream(payload),new DataOutputStream(sendWire),new DataInputStream(sender),payload.length,()->{});throw new AssertionError("Rejected disk reported success");}catch(IOException e){ok("REMOTE_WRITE".equals(e.getMessage()),"disk rejection propagated without reconnecting");}try{received.get(3,TimeUnit.SECONDS);throw new AssertionError("Disk failure accepted");}catch(ExecutionException expected){ok(expected.getCause() instanceof IOException,"receiver disk failure remains failure");}}else{byte[] sourceHash=ChunkTransport.send(new ByteArrayInputStream(payload),new DataOutputStream(sendWire),new DataInputStream(sender),payload.length,()->{});ok(ProtocolCore.equal(sourceHash,received.get(3,TimeUnit.SECONDS)),"real bounded-pipe chunk checksum");ok(Arrays.equals(payload,destination.toByteArray()),"all chunks persisted to synthetic target");}}finally{sendWire.close();sender.close();worker.shutdownNow();ok(worker.awaitTermination(3,TimeUnit.SECONDS),"synthetic chunk workers exited");}
 }
}
