package in.chinatech.mimoverengine;
import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.*;
import android.provider.DocumentsContract;
import java.io.*;
import java.net.*;
import java.util.*;
/** Separate APK; synthetic fixtures and isolated cache DB. No production test components. */
public final class RuntimeTests extends Instrumentation {
 private Bundle options; private TransferEngine engine; private Context target; private UniversalActivity activity; private int checks; private String phase="begin";
 @Override public void onCreate(Bundle args){options=args==null?new Bundle():args;start();}
 private void require(boolean yes,String label){if(!yes)throw new AssertionError(label);checks++;}
 private void waitFor(java.util.concurrent.Callable<Boolean> test,long timeout,String label)throws Exception{long until=SystemClock.elapsedRealtime()+timeout;while(SystemClock.elapsedRealtime()<until){if(test.call())return;Thread.sleep(100);}throw new AssertionError(label+" status="+(engine==null?0:engine.status));}
 @Override public void onStart(){Bundle result=new Bundle();try{
  if(options.containsKey("language"))getTargetContext().getSharedPreferences("mimover-universal-ui",Context.MODE_PRIVATE).edit().putString("language",options.getString("language")).commit();target=new BridgeContext(getTargetContext());String mode=options.getString("mode","store");
  if(mode.equals("store")){store(result);}else if(mode.equals("projection")){projection(result);}else if(mode.equals("tls")){tls(result);}else if(mode.equals("entry")||mode.equals("entrytouch")){entryOld(result);}else if(mode.equals("entrynew")){entryNew(result);}else{
   Intent intent=new Intent(target,UniversalActivity.class).putExtra("receiving",!(mode.equals("sender")||mode.equals("selection")||mode.equals("uiprojection"))).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_MULTIPLE_TASK);
   ActivityMonitor monitor=addMonitor(UniversalActivity.class.getName(),null,false);runOnMainSync(()->target.startActivity(intent));activity=(UniversalActivity)monitor.waitForActivityWithTimeout(10000);removeMonitor(monitor);require(activity!=null,"owned original UI activity starts");Thread.sleep(1000);engine=TransferEngine.get(target);
   target.startActivity(new Intent().setClassName("in.chinatech.mimoverruntimetest","in.chinatech.mimoverengine.GrantActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));
   waitFor(()->{try(Cursor c=target.getContentResolver().query(DocumentsContract.buildDocumentUriUsingTree(tree(),"root"),new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID},null,null,null)){return c!=null&&c.moveToFirst();}catch(SecurityException unavailable){return false;}},10000,"synthetic folder grant");
   target.getContentResolver().takePersistableUriPermission(tree(),Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
   runOnMainSync(()->engine.stop());waitFor(()->!engine.isActive(),10000,"stop existing synthetic test");
   if(mode.equals("receiver"))receiver(result);else if(mode.equals("sender"))sender(result);else if(mode.equals("fault"))faults(result);else if(mode.equals("gallery"))gallery(result);else if(mode.equals("selection"))selection(result);else if(mode.equals("uiprojection"))uiProjection(result);else if(mode.equals("hotspot"))hotspot(result);else if(mode.equals("screenshot"))captureSynthetic(result,"host");else throw new AssertionError("known mode required");
  }
  result.putInt("checks",checks);result.putString("phase","complete");finish(Activity.RESULT_OK,result);
 }catch(Throwable failure){result.putString("failure",failure.getClass().getSimpleName()+":"+(failure instanceof AssertionError?failure.getMessage():"runtime failure - inspect phase"));result.putString("phase",phase);result.putInt("checks",checks);finish(Activity.RESULT_CANCELED,result);}}
 private byte[] imageBytes(int color)throws Exception {Bitmap image=Bitmap.createBitmap(64,64,Bitmap.Config.ARGB_8888);image.eraseColor(color);ByteArrayOutputStream out=new ByteArrayOutputStream();require(image.compress(Bitmap.CompressFormat.PNG,100,out),"synthetic PNG created");image.recycle();return out.toByteArray();}
 private boolean mediaExists(Uri uri)throws Exception {try(android.database.Cursor c=target.getContentResolver().query(uri,new String[]{android.provider.MediaStore.MediaColumns._ID},null,null,null)){return c!=null&&c.moveToFirst();}}
 private String mediaKey(ProtocolCore.Item item){return ProtocolCore.hex(item.hash)+":"+item.size+":"+item.mime;}
 private ProtocolCore.Item mediaSource(byte[] bytes,Uri directory)throws Exception {Uri parent=DocumentsContract.buildDocumentUriUsingTree(tree(),"root");Uri file=DocumentsContract.createDocument(target.getContentResolver(),parent,"image/png","synthetic-photo.png");try(OutputStream out=target.getContentResolver().openOutputStream(file,"w")){out.write(bytes);}ProtocolCore.Item item=new ProtocolCore.Item(ProtocolCore.token(16),"synthetic-photo.png","image/png",bytes.length,ProtocolCore.sha256(bytes));engine.store.received(ProtocolCore.token(16),item,file,directory);return item;}
 private void gallery(Bundle result)throws Exception {
  phase="gallery-create";Uri directory=tree().buildUpon().appendQueryParameter("synthetic-run",ProtocolCore.token(16)).build();runOnMainSync(()->engine.setDirectory(tree()));byte[] bytes=imageBytes(0xff000000|new java.util.Random().nextInt(0xffffff));ProtocolCore.Item one=mediaSource(bytes,directory);CancellationScope scope=new CancellationScope(Runnable::run,()->{});
  MediaImporter.Result first=new MediaImporter(target,scope).run(engine.store,directory,(n,k,f)->{});require(first.imported==1&&first.failed==0,"actual MediaStore image import");MediaImportStore journal=new MediaImportStore(target);Uri dest=journal.get(mediaKey(one)).dest;require(mediaExists(dest),"gallery row visible");try(android.database.Cursor c=target.getContentResolver().query(dest,new String[]{android.provider.MediaStore.MediaColumns.IS_PENDING},null,null,null)){require(c!=null&&c.moveToFirst()&&c.getInt(0)==0,"pending cleared only after verification");}
  MediaImporter.Result repeat=new MediaImporter(target,scope).run(engine.store,directory,(n,k,f)->{});require(repeat.imported==0&&repeat.skipped==1&&repeat.failed==0,"retry no duplicate copy");require(dest.equals(journal.get(mediaKey(one)).dest),"same gallery URI after retry");
  // A journal may still say pending after publication. Editing this public copy must never cause deletion.
  journal.put(mediaKey(one),dest,"pending");try(OutputStream out=target.getContentResolver().openOutputStream(dest,"w")){out.write(new byte[]{9,8,7});}
  MediaImporter.Result edited=new MediaImporter(target,scope).run(engine.store,directory,(n,k,f)->{});require(edited.failed==1&&edited.imported==0,"changed visible copy reports failure");require(mediaExists(dest),"changed public copy retained");
  phase="gallery-intent-recovery";byte[] next=imageBytes(0xff000000|new java.util.Random().nextInt(0xffffff));ProtocolCore.Item two=mediaSource(next,directory);String name="CT-"+ProtocolCore.token(16)+"-synthetic-recovery.png";journal.intent(mediaKey(two),name);android.content.ContentValues values=new android.content.ContentValues();values.put(android.provider.MediaStore.MediaColumns.DISPLAY_NAME,name);values.put(android.provider.MediaStore.MediaColumns.MIME_TYPE,"image/png");values.put(android.provider.MediaStore.MediaColumns.RELATIVE_PATH,"Pictures/ChinaTech/");values.put(android.provider.MediaStore.MediaColumns.IS_PENDING,1);Uri interrupted=target.getContentResolver().insert(android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI,values);require(interrupted!=null,"fixture created between insert and URI journal");try(OutputStream out=target.getContentResolver().openOutputStream(interrupted,"w")){out.write(next);}
  MediaImporter.Result recovered=new MediaImporter(target,scope).run(engine.store,directory,(n,k,f)->{});result.putString("recoveryResult",recovered.imported+"/"+recovered.skipped+"/"+recovered.failed+" "+recovered.lastFailure);require(recovered.imported==0&&recovered.skipped==1&&recovered.failed==1,"creation intent recovered without another copy");require(interrupted.equals(journal.get(mediaKey(two)).dest),"creation intent resolves exact URI");require("published".equals(journal.get(mediaKey(two)).state),"recovered row committed");
  // Journal lives independently of the scan index and a newly constructed importer.
  journal.close();MediaImportStore reopened=new MediaImportStore(target);require(reopened.get(mediaKey(two)).dest.equals(interrupted),"journal persists across helper recreation");reopened.close();result.putBoolean("actualMediaStoreImportAndRecovery",true);result.putInt("galleryChecks",checks);phase="complete";
 }
 private void tls(Bundle result)throws Exception {SessionTls id=new SessionTls(System.currentTimeMillis()+600000);try(javax.net.ssl.SSLServerSocket server=(javax.net.ssl.SSLServerSocket)id.context.getServerSocketFactory().createServerSocket(0,1,InetAddress.getLoopbackAddress())){server.setSoTimeout(10000);java.util.concurrent.CompletableFuture<Boolean> remote=new java.util.concurrent.CompletableFuture<>();new Thread(()->{try(javax.net.ssl.SSLSocket peer=(javax.net.ssl.SSLSocket)server.accept()){peer.setSoTimeout(10000);peer.startHandshake();peer.getOutputStream().write(42);peer.getOutputStream().flush();remote.complete(true);}catch(Throwable e){result.putString("serverFailure",e.getClass().getSimpleName());remote.completeExceptionally(e);}}).start();try(javax.net.ssl.SSLSocket socket=(javax.net.ssl.SSLSocket)SessionTls.pinned(id.pin).getSocketFactory().createSocket(InetAddress.getLoopbackAddress(),server.getLocalPort())){socket.setSoTimeout(10000);socket.startHandshake();require(socket.getInputStream().read()==42,"actual AndroidKeyStore TLS pinned handshake");require(remote.get(10,java.util.concurrent.TimeUnit.SECONDS),"server handshake");result.putBoolean("pinnedAndroidTls",true);}catch(Exception clientError){try{remote.get(10,java.util.concurrent.TimeUnit.SECONDS);}catch(Exception ignored){}throw clientError;}}finally{id.close();}}
 private int destinationCount()throws Exception {Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(tree(),"root");try(android.database.Cursor c=target.getContentResolver().query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID},null,null,null)){return c==null?0:c.getCount();}}
 private void faults(Bundle result)throws Exception {
  phase="manual-hotspot-qr";runOnMainSync(()->{engine.setDirectory(tree());engine.configureManualHotspot("TEST-ONLY-MANUAL","test-only-password");});waitFor(()->engine.serverPair!=null,15000,"manual hotspot QR without local MAC");require(engine.wifi.manuallyConfigured(),"manual mode explicit");require(QrCodec.decode(QrCodec.encode(engine.serverPair.encode())).equals(engine.serverPair.encode()),"manual hotspot QR decode");runOnMainSync(()->engine.stop());waitFor(()->!engine.isActive(),10000,"manual mode close");
  phase="lost-complete";String previousReady=engine.store.get("restore-ready");int before=destinationCount();runOnMainSync(()->{engine.useRouter();engine.prepareReceiver();});waitFor(()->engine.serverPair!=null,15000,"fault receiver");ProtocolCore.Pairing pair=engine.serverPair;String task=ProtocolCore.token(16),object=ProtocolCore.token(16);byte[] nonce=ProtocolCore.random(32),bytes=new byte[65537];Arrays.fill(bytes,(byte)17);ProtocolCore.Item item=new ProtocolCore.Item(object,"synthetic-fault.bin","application/octet-stream",bytes.length,ProtocolCore.sha256(bytes));
  Thread approve=new Thread(()->{while(engine.isActive()){if(engine.pendingConfirmation!=null)runOnMainSync(()->engine.decide(true));try{Thread.sleep(50);}catch(InterruptedException stop){return;}}});approve.start();
  try(FaultPeer p=new FaultPeer(pair,task,nonce)){require(!p.object(item,bytes),"first object written");p.complete(item);}
  Thread.sleep(200);require(engine.isActive(),"lost COMPLETE retains listener");require(destinationCount()==before+1,"one saved object");assertPendingOriginal();require(java.util.Objects.equals(previousReady,engine.store.get("restore-ready")),"lost COMPLETE cannot authorize new restoration");
  phase="bad-finish";try(FaultPeer p=new FaultPeer(pair,task,nonce)){require(p.object(item,bytes),"reconnect verifies and skips saved object");p.complete(item);p.readComplete(item);ProtocolCore.writeFinish(p.out,2,ProtocolCore.sha256(bytes));}Thread.sleep(200);require(engine.isActive(),"wrong FINISH count refused");require(destinationCount()==before+1,"replay no duplicate");assertPendingOriginal();require(java.util.Objects.equals(previousReady,engine.store.get("restore-ready")),"bad FINISH cannot authorize new restoration");
  phase="finish-recover";try(FaultPeer p=new FaultPeer(pair,task,nonce)){require(p.object(item,bytes),"second replay skips");p.complete(item);byte[] digest=p.readComplete(item);ProtocolCore.writeFinish(p.out,1,digest);}waitFor(()->engine.status==R.string.receiver_complete,10000,"valid FINISH completes");waitFor(()->!engine.isActive(),10000,"completion cleanup");require(destinationCount()==before+1,"exactly one fixture after recovery");require(task.equals(engine.store.get("restore-ready")),"only legal FINISH publishes restore-ready");assertOriginalFinished(true,1);
  phase="lost-finish";renderOriginal(UniversalActivity.HOST);runOnMainSync(()->{engine.useRouter();engine.prepareReceiver();});waitFor(()->engine.serverPair!=null,15000,"new fault session");pair=engine.serverPair;task=ProtocolCore.token(16);nonce=ProtocolCore.random(32);Thread approve2=new Thread(()->{while(engine.isActive()){if(engine.pendingConfirmation!=null)runOnMainSync(()->engine.decide(true));try{Thread.sleep(50);}catch(InterruptedException stop){return;}}});approve2.start();try(FaultPeer p=new FaultPeer(pair,task,nonce)){require(!p.object(item,bytes),"new task writes distinct destination");p.complete(item);p.readComplete(item);}Thread.sleep(200);require(engine.isActive(),"lost FINISH retains confirmed saved files");java.lang.reflect.Field grace=TransferEngine.class.getDeclaredField("completedGrace");grace.setAccessible(true);grace.setLong(engine,SystemClock.elapsedRealtime()+500);waitFor(()->engine.status==R.string.receiver_complete_unconfirmed,5000,"scaled final grace expires honestly");require(destinationCount()==before+2,"unconfirmed final receipt keeps saved file");require(engine.receiptProjection.category("files")==1,"retry receiver count never double counts");assertPendingOriginal();result.putBoolean("nativeFinalRecovery",true);result.putString("graceTest","500ms scaled deadline; production is 180000ms");phase="complete";
 }
 private final class FaultPeer implements AutoCloseable {
  final javax.net.ssl.SSLSocket socket;final DataInputStream in;final DataOutputStream out;
  FaultPeer(ProtocolCore.Pairing pair,String task,byte[] nonce)throws Exception {socket=(javax.net.ssl.SSLSocket)SessionTls.pinned(pair.pin).getSocketFactory().createSocket(pair.host,pair.port);socket.setSoTimeout(10000);socket.startHandshake();in=new DataInputStream(new BufferedInputStream(socket.getInputStream()));out=new DataOutputStream(new BufferedOutputStream(socket.getOutputStream()));ProtocolCore.writeString(out,pair.magic(),10);ProtocolCore.writeString(out,pair.session,30);out.write(pair.secret);out.write(nonce);ProtocolCore.writeString(out,task,30);out.writeLong(1);out.flush();require("APPROVED".equals(ProtocolCore.readString(in,20)),"fault peer approved");out.writeBoolean(true);out.flush();}
  boolean object(ProtocolCore.Item item,byte[] bytes)throws Exception {ProtocolCore.writeString(out,"OBJECT",20);ProtocolCore.writeItem(out,item);String action=ProtocolCore.readVerifiedControl(in,()->{});boolean skipped=action.equals("SKIP");require(skipped||action.equals("WRITE"),"object disposition");if(!skipped){require(ProtocolCore.equal(ChunkTransport.send(new ByteArrayInputStream(bytes),out,in,item.size,()->{}),item.hash),"chunk hash");out.write(item.hash);out.flush();}require("SAVED".equals(ProtocolCore.readVerifiedControl(in,()->{})),"saved frame");byte[] hash=new byte[32];in.readFully(hash);require(ProtocolCore.equal(hash,item.hash),"disk hash acknowledgement");return skipped;}
  void complete(ProtocolCore.Item item)throws Exception {ManifestDigest digest=new ManifestDigest();digest.add(item);ProtocolCore.writeString(out,"COMPLETE",20);out.writeLong(1);out.writeLong(item.size);out.write(digest.finish());out.flush();}
  byte[] readComplete(ProtocolCore.Item item)throws Exception {require("COMPLETE".equals(ProtocolCore.readString(in,20))&&in.readLong()==1,"final complete count");byte[] actual=new byte[32];in.readFully(actual);ManifestDigest expected=new ManifestDigest();expected.add(item);require(ProtocolCore.equal(actual,expected.finish()),"final digest");return actual;}
  public void close()throws IOException{socket.close();}
 }
 private Uri tree(){return DocumentsContract.buildTreeDocumentUri("in.chinatech.mimoverruntimetest.documents","root");}
 private boolean wifiReady(){android.net.ConnectivityManager manager=target.getSystemService(android.net.ConnectivityManager.class);for(android.net.Network n:manager.getAllNetworks()){android.net.NetworkCapabilities caps=manager.getNetworkCapabilities(n);android.net.LinkProperties p=manager.getLinkProperties(n);if(caps!=null&&p!=null&&caps.hasTransport(android.net.NetworkCapabilities.TRANSPORT_WIFI)&&!caps.hasTransport(android.net.NetworkCapabilities.TRANSPORT_VPN))for(android.net.LinkAddress address:p.getLinkAddresses())try{ProtocolCore.validateHost(address.getAddress().getHostAddress());return true;}catch(IOException invalid){}}return false;}
 private static final String[] CATEGORIES={"photos","videos","audio","contacts","calendar","apps","files"};
 private final class IsolatedContext extends ContextWrapper {
  IsolatedContext(){super(target);}
  private String name(String n){return "mimover-runtime-"+n;}
  @Override public File getDatabasePath(String n){return super.getDatabasePath(name(n));}
  @Override public SQLiteDatabase openOrCreateDatabase(String n,int mode,SQLiteDatabase.CursorFactory factory){return super.openOrCreateDatabase(name(n),mode,factory);}
  @Override public SQLiteDatabase openOrCreateDatabase(String n,int mode,SQLiteDatabase.CursorFactory factory,android.database.DatabaseErrorHandler handler){return super.openOrCreateDatabase(name(n),mode,factory,handler);}
  @Override public boolean deleteDatabase(String n){return super.deleteDatabase(name(n));}
 }
 private void checkCounts(TransferStore s){
  long all=0,chosen=0;Map<String,long[]> expected=new HashMap<>();
  try(Cursor c=s.getReadableDatabase().rawQuery(TransferSchema.COUNTS,null)){while(c.moveToNext()){long count=c.getLong(1),selected=c.getLong(2);expected.put(c.getString(0),new long[]{count,selected});all+=count;chosen+=selected;}}
  require(s.count(false)==all,"cached total matches SQL");require(s.count(true)==chosen,"cached selected matches SQL");
  for(String kind:CATEGORIES){long[] pair=expected.get(kind);require(s.countCategory(kind)==(pair==null?0:pair[0]),"category count matches SQL "+kind);require(s.selectedCategoryCount(kind)==(pair==null?0:pair[1]),"category selected matches SQL "+kind);}
 }
 private void store(Bundle result)throws Exception {
  phase="store-isolation";Context isolated=new IsolatedContext();isolated.deleteDatabase("transfer-v2.sqlite");TransferStore s=new TransferStore(isolated);
  try{
   checkCounts(s);phase="store-add-237";long revision=s.uiRevision();
   for(int i=0;i<237;i++){s.add(Uri.parse("content://synthetic-runtime/fixture-"+i),CATEGORIES[i%7],"synthetic-"+i+".bin","application/octet-stream",i,i%3==0);require(s.uiRevision()>revision,"insert publishes revision");revision=s.uiRevision();}
   checkCounts(s);require(s.count(false)==237&&s.count(true)==79,"237 fixtures with exact initial selection");
   phase="store-pagination";Set<Long> ids=new HashSet<>();long after=0;int pages=0;List<TransferStore.Row> page;
   while(!(page=s.page(null,after)).isEmpty()){require(page.size()<=TransferStore.PAGE,"bounded page");for(TransferStore.Row row:page){require(row.n>after,"ordered non-overlap page");require(ids.add(row.n),"no duplicate paged ID");after=row.n;}pages++;}
   require(ids.size()==237&&pages>=3,"100 plus pagination is complete");
   for(String category:CATEGORIES){long n=0,cursor=0;while(!(page=s.page(category,cursor)).isEmpty()){for(TransferStore.Row row:page){require(row.category.equals(category),"category page never leaks other rows");cursor=row.n;n++;}}require(n==s.countCategory(category),"category page covers full count");}
   phase="store-single-choice";TransferStore.Row first=s.page(null,0).get(0);revision=s.uiRevision();require(s.select(first.n,false),"single deselect commits");require(!s.isSelected(first.n),"single deselect persisted");require(s.uiRevision()>revision,"single deselect publishes revision");checkCounts(s);
   long previous=s.count(true);require(s.select(first.n,false),"repeat single deselect accepted");require(s.count(true)==previous,"repeat single choice no count drift");checkCounts(s);
   require(!s.select(Long.MAX_VALUE,true),"missing row cannot claim mutation");checkCounts(s);
   for(int i=0;i<80;i++){TransferStore.Row row=s.page(null,i%2==0?0:100).get(i%10);revision=s.uiRevision();require(s.select(row.n,!s.isSelected(row.n)),"toggle commits");require(s.uiRevision()>revision,"toggle publishes revision");checkCounts(s);}
   phase="store-duplicate";revision=s.uiRevision();s.add(first.uri,"calendar","different-name.ics","text/calendar",999,true);require(s.count(false)==237,"duplicate URI cannot add row");require(s.isSelected(first.n),"duplicate selected flag promotes existing row");require(s.uiRevision()>revision,"duplicate selection publishes revision");require(s.page("photos",0).get(0).name.equals(first.name),"duplicate retains original identity and metadata");checkCounts(s);
   previous=s.count(true);s.add(first.uri,"files","different.bin","application/octet-stream",2,false);require(s.isSelected(first.n)&&s.count(true)==previous,"duplicate unchecked add cannot deselect existing row");checkCounts(s);
   phase="store-bulk";for(String category:CATEGORIES){revision=s.uiRevision();s.select(category,false);require(s.selectedCategoryCount(category)==0,"category deselect includes every page");require(s.uiRevision()>revision,"bulk publishes revision");checkCounts(s);s.select(category,true);require(s.selectedCategoryCount(category)==s.countCategory(category),"category select includes every page");checkCounts(s);}
   s.select((String)null,false);require(s.count(true)==0,"select none clears all pages");checkCounts(s);s.select((String)null,true);require(s.count(true)==237,"select all includes all pages");checkCounts(s);
   phase="store-freeze";after=0;while(!(page=s.selectedRows(after)).isEmpty()){List<TransferStore.Row> prepared=new ArrayList<>();for(TransferStore.Row row:page){prepared.add(new TransferStore.Row(row.n,row.uri,row.id,row.name,row.mime,row.size,ProtocolCore.sha256(new byte[0]),row.selected,row.category));after=row.n;}s.preparedRows(prepared);}s.freeze();require(s.sendingCount()==237,"immutable snapshot includes full selection");s.select((String)null,false);require(s.sendingCount()==237,"selection changes cannot alter frozen sending snapshot");checkCounts(s);
   phase="store-reopen";s.close();s=new TransferStore(isolated);checkCounts(s);require(s.count(false)==237&&s.count(true)==0,"reopened cache recovers SQL facts");require(s.sendingCount()==237,"frozen snapshot survives helper recreation");
   phase="store-clear";String transfer=s.transfer();revision=s.uiRevision();s.clear();require(s.count(false)==0&&s.count(true)==0&&s.sendingCount()==0,"clear removes index and snapshot");require(!s.transfer().equals(transfer),"clear creates a new transfer identity");require(s.uiRevision()>revision,"clear invalidates rendered rows");checkCounts(s);
   s.add(Uri.parse("content://synthetic-runtime/after-clear"),"files","synthetic-after-clear.bin","application/octet-stream",0,true);checkCounts(s);require(s.countCategory("files")==1&&s.selectedCategoryCount("photos")==0,"clear removes stale category cache");
   phase="store-incoming";s.beginIncoming();for(int i=0;i<TransferStore.TRANSFER_BATCH+1;i++)s.incoming("synthetic-object-"+i);try{s.incoming("synthetic-object-0");throw new AssertionError("persisted incoming duplicate accepted");}catch(IOException expected){require("DUPLICATE_OBJECT".equals(expected.getMessage()),"duplicate across scratch flush rejected");}try{s.incoming("synthetic-object-64");throw new AssertionError("scratch incoming duplicate accepted");}catch(IOException expected){require("DUPLICATE_OBJECT".equals(expected.getMessage()),"duplicate in current scratch batch rejected");}s.beginIncoming();s.incoming("synthetic-object-0");require(true,"new pass resets incoming scratch");
   result.putInt("fixtureRows",237);result.putInt("pageLimit",TransferStore.PAGE);result.putBoolean("categoryCacheAndRevision",true);
  }finally{s.close();isolated.deleteDatabase("transfer-v2.sqlite");}
 }
 private void projection(Bundle result)throws Exception {
  phase="receipt-projection";ReceiptProjection p=new ReceiptProjection();require(p.acknowledged()==0,"no preparation ACKs");for(int i=0;i<137;i++){p.acknowledged("synthetic-object-"+i);p.acknowledged("synthetic-object-"+i);}require(p.acknowledged()==137,"sender ACK object identity dedup");
  String[] names={"photo.png","video.mp4","audio.ogg","contacts.VCF","events.ICS","app-chinatech-apk.zip","file.bin"};String[] mimes={"image/png","video/mp4","audio/ogg","application/octet-stream","application/octet-stream","application/zip","application/octet-stream"};
  for(int i=0;i<7;i++){ProtocolCore.Item item=new ProtocolCore.Item(ProtocolCore.token(16),names[i],mimes[i],0,ProtocolCore.sha256(new byte[0]));p.received(item);p.received(item);require(p.category(CATEGORIES[i])==1,"received classification and identity dedup "+CATEGORIES[i]);}
  require(p.category("unknown")==0,"unknown category is zero");p.receivingPass();for(String category:CATEGORIES)require(p.category(category)==0,"reconnect resets receiver pass category "+category);require(p.acknowledged()==137,"receiver pass preserves sender ACK history");
  ProtocolCore.Item item=new ProtocolCore.Item(ProtocolCore.token(16),"new.png","image/png",0,ProtocolCore.sha256(new byte[0]));p.received(item);require(p.category("photos")==1,"new pass accepts fresh verified receiver item");p.clear();require(p.acknowledged()==0,"role reset clears sender ACK");for(String category:CATEGORIES)require(p.category(category)==0,"role reset clears receiver category "+category);result.putBoolean("receiptProjectionDedupAndClassification",true);
 }
 private void receiver(Bundle result)throws Exception {
  phase="lan-listen";Uri runDirectory=tree().buildUpon().appendQueryParameter("synthetic-run",ProtocolCore.token(16)).build();waitFor(this::wifiReady,30000,"emulator Wi-Fi route available");runOnMainSync(()->{engine.setDirectory(runDirectory);engine.useRouter();engine.prepareReceiver();});waitFor(()->engine.serverPair!=null,15000,"LAN receiver QR");ProtocolCore.Pairing pair=engine.serverPair;require(pair.ssid.isEmpty(),"LAN pairing");require(!pair.host.equals("gateway"),"LAN actual address");
  try(ServerSocket ipc=new ServerSocket(10081,5,InetAddress.getLoopbackAddress())){ipc.setSoTimeout(60000);boolean handed=false;while(!handed){try(Socket host=ipc.accept()){host.setSoTimeout(10000);DataInputStream request=new DataInputStream(host.getInputStream());if(!"PAIR".equals(ProtocolCore.readString(request,20)))continue;DataOutputStream out=new DataOutputStream(host.getOutputStream());ProtocolCore.writeString(out,pair.encode(),512);out.flush();handed=true;}catch(IOException retry){}}}
  phase="receive";long until=SystemClock.elapsedRealtime()+180000;while(SystemClock.elapsedRealtime()<until){if(engine.pendingConfirmation!=null)runOnMainSync(()->engine.decide(true));if(engine.status==R.string.receiver_complete)break;if(!engine.isActive())throw new AssertionError("receiver ended status="+engine.status);Thread.sleep(100);}require(engine.status==R.string.receiver_complete,"receiver legal FINISH completion");waitFor(()->!engine.isActive(),10000,"receiver cleanup");require(engine.receivedCount==3,"all three saved");require(engine.receiptProjection.category("files")==3,"real saved receiver category projection");require(engine.residualCount()==0,"no unfinished fixture");require(engine.store.get("restore-ready")!=null,"legal FINISH makes restoration eligible");require(runDirectory.toString().equals(engine.store.get("restore-directory")),"restoration directory matches legal FINISH");
  long total=0;for(long after=0;;){TransferStore.MediaReceipt row=RestoreCatalog.next(engine.store,runDirectory,after);if(row==null)break;after=row.n;try(InputStream in=target.getContentResolver().openInputStream(row.source)){java.security.MessageDigest hash=java.security.MessageDigest.getInstance("SHA-256");byte[] buffer=new byte[65536];int n;long size=0;while((n=in.read(buffer))!=-1){hash.update(buffer,0,n);size+=n;}require(size==row.item.size&&ProtocolCore.equal(hash.digest(),row.item.hash),"actual receiver bytes match durable receipt");total+=size;}}
  require(total==2162690,"exact synthetic destination byte total");result.putLong("receivedCount",engine.receivedCount);result.putLong("fixtureBytes",total);assertOriginalFinished(true,3);result.putBoolean("nativeFinalReceipt",true);
 }
 private void sender(Bundle result)throws Exception {
  phase="pair-private-ipc";String code;try(ServerSocket ipc=new ServerSocket(10082,2,InetAddress.getLoopbackAddress())){ipc.setSoTimeout(60000);try(Socket host=ipc.accept()){host.setSoTimeout(10000);code=ProtocolCore.readString(new DataInputStream(host.getInputStream()),512);}}
  phase="source";Uri parent=DocumentsContract.buildDocumentUriUsingTree(tree(),"root");int[] sizes={0,65537,2097153};List<Uri> sources=new ArrayList<>();for(int size:sizes){Uri uri=DocumentsContract.createDocument(target.getContentResolver(),parent,"application/octet-stream","synthetic-"+size+".bin");try(OutputStream out=target.getContentResolver().openOutputStream(uri,"w")){byte[] b=new byte[65536];for(int k=0;k<b.length;k++)b[k]=(byte)(k*31+7);int left=size;while(left>0){int count=Math.min(left,b.length);out.write(b,0,count);left-=count;}}sources.add(uri);}runOnMainSync(()->engine.clearSelection());waitFor(()->!engine.isActive(),10000,"clear source");runOnMainSync(()->engine.addUris(sources));waitFor(()->!engine.isActive(),10000,"index source");require(engine.selectedCount()==3,"selected scope");require(engine.receiptProjection.acknowledged()==0,"preparation cannot report SAVED");
  phase="send";runOnMainSync(()->engine.sendUsingExisting(code));long until=SystemClock.elapsedRealtime()+180000;while(SystemClock.elapsedRealtime()<until){if(engine.pendingConfirmation!=null)runOnMainSync(()->engine.decide(true));if(engine.status==R.string.sender_complete)break;if(!engine.isActive())throw new AssertionError("sender ended status="+engine.status);Thread.sleep(100);}require(engine.status==R.string.sender_complete,"sender saved hash acknowledgments");waitFor(()->!engine.isActive(),10000,"sender cleanup");require(engine.receiptProjection.acknowledged()==3,"exactly three verified SAVED projections");result.putLong("selectedCount",engine.selectedCount());result.putLong("fixtureBytes",2162690);assertOriginalFinished(false,3);result.putBoolean("nativeSenderTlsAndAcknowledgments",true);
 }
 private android.view.View findText(android.view.View v,String text){if(v instanceof android.widget.TextView&&((android.widget.TextView)v).getText().toString().equals(text))return v;if(v instanceof android.view.ViewGroup){android.view.ViewGroup g=(android.view.ViewGroup)v;for(int i=0;i<g.getChildCount();i++){android.view.View found=findText(g.getChildAt(i),text);if(found!=null)return found;}}return null;}
 private android.view.View rowFor(String text){android.view.View title=findText(activity.getWindow().getDecorView(),text);if(title==null)return null;android.view.View v=title;while(v.getParent() instanceof android.view.View){if(v.findViewById(HostR.id.check_box)!=null&&v.hasOnClickListeners())return v;v=(android.view.View)v.getParent();}return null;}
 private android.widget.CheckBox checkedFor(String text){android.view.View row=rowFor(text);return row==null?null:(android.widget.CheckBox)row.findViewById(HostR.id.check_box);}
 private void scrollList(int position){runOnMainSync(()->{try{android.view.View list=activity.findViewById(HostR.id.scanner_list);list.getClass().getMethod("scrollToPosition",int.class).invoke(list,position);}catch(Exception e){throw new RuntimeException(e);}});}
 private void selection(Bundle result)throws Exception {
  phase="selection-fixtures";engine.resetDisplay();engine.store.clear();for(int i=0;i<121;i++)engine.store.add(Uri.parse("content://synthetic-runtime/selection-"+i),"files","synthetic-ui-"+i+".bin","application/octet-stream",i,i%2==0);
  String files=target.getString(R.string.category_files);android.view.View choose=findText(activity.getWindow().getDecorView(),target.getString(R.string.original_choose_data));require(choose!=null,"actual Guest choose data control");runOnMainSync(choose::performClick);scrollList(9);waitFor(()->checkedFor(files)!=null,10000,"original files category row");require(!checkedFor(files).isChecked(),"partially selected category is unchecked");
  phase="selection-bulk";runOnMainSync(checkedFor(files)::performClick);waitFor(()->!engine.isActive()&&engine.selectedCount()==121&&checkedFor(files)!=null&&checkedFor(files).isChecked(),10000,"original category checkbox bulk choice commits");require(engine.store.selectedCategoryCount("files")==121,"category cache includes rows beyond visible page");android.view.View category=rowFor(files);runOnMainSync(category::performClick);waitFor(()->checkedFor("synthetic-ui-0.bin")!=null,10000,"original file item row");
  phase="selection-single";runOnMainSync(checkedFor("synthetic-ui-0.bin")::performClick);waitFor(()->engine.selectedCount()==120&&checkedFor("synthetic-ui-0.bin")!=null&&!checkedFor("synthetic-ui-0.bin").isChecked(),10000,"single checkbox and committed selection agree");require(engine.store.selectedCategoryCount("files")==120,"single choice refreshes category cache");android.view.View selectAll=activity.findViewById(HostR.id.select_all);require(selectAll!=null,"original select all ID exists");runOnMainSync(selectAll::performClick);waitFor(()->!engine.isActive()&&engine.selectedCount()==121&&checkedFor("synthetic-ui-0.bin")!=null&&checkedFor("synthetic-ui-0.bin").isChecked(),10000,"original select all refreshes same visible item");
  phase="selection-busy";java.lang.reflect.Field field=TransferEngine.class.getDeclaredField("tasks");field.setAccessible(true);java.util.concurrent.atomic.AtomicInteger tasks=(java.util.concurrent.atomic.AtomicInteger)field.get(engine);tasks.incrementAndGet();try{runOnMainSync(activity::changed);waitFor(()->checkedFor("synthetic-ui-0.bin")!=null&&!checkedFor("synthetic-ui-0.bin").isEnabled(),3000,"busy item input disabled");require(!checkedFor("synthetic-ui-0.bin").isEnabled(),"busy original item rebind disables input");android.view.View item=rowFor("synthetic-ui-0.bin");runOnMainSync(item::performClick);require(engine.selectedCount()==121&&engine.store.isSelected(engine.page("files",0).get(0).n),"busy original row cannot mutate snapshot");}finally{tasks.decrementAndGet();runOnMainSync(activity::changed);}
  phase="selection-pagination";scrollList(50);waitFor(()->findText(activity.getWindow().getDecorView(),target.getString(R.string.next_page))!=null,10000,"original first page next control");android.view.View next=clickableAncestor(findText(activity.getWindow().getDecorView(),target.getString(R.string.next_page)));runOnMainSync(next::performClick);waitFor(()->checkedFor("synthetic-ui-50.bin")!=null,10000,"second page first original row");scrollList(51);waitFor(()->findText(activity.getWindow().getDecorView(),target.getString(R.string.next_page))!=null,10000,"original second page next control");next=clickableAncestor(findText(activity.getWindow().getDecorView(),target.getString(R.string.next_page)));runOnMainSync(next::performClick);waitFor(()->checkedFor("synthetic-ui-100.bin")!=null,10000,"third page first original row");require(engine.scannedCount()==121&&engine.selectedCount()==121,"paging preserves all counts");
  phase="selection-recreation";java.lang.reflect.Field scopeField=CoreActivity.class.getDeclaredField("scanConsent");scopeField.setAccessible(true);((ScanConsent)scopeField.get(activity)).request(new boolean[]{true,false,false});ActivityMonitor monitor=addMonitor(UniversalActivity.class.getName(),null,false);UniversalActivity prior=activity;runOnMainSync(prior::recreate);activity=(UniversalActivity)monitor.waitForActivityWithTimeout(10000);removeMonitor(monitor);require(activity!=null&&activity!=prior,"actual owned original Activity recreation");waitFor(()->checkedFor("synthetic-ui-100.bin")!=null,10000,"original page cursor survives recreation");require(checkedFor("synthetic-ui-100.bin").isChecked()&&engine.selectedCount()==121,"recreated checkbox matches committed store");boolean[] pending=((ScanConsent)scopeField.get(activity)).consume();require(pending!=null&&pending[0]&&!pending[1]&&!pending[2],"pending scan scope survives original Activity recreation");require(((ScanConsent)scopeField.get(activity)).consume()==null,"recreated scan scope callback is single use");result.putBoolean("actualPendingScanScopeRecreation",true);
  result.putBoolean("actualOriginalSelectionAndPagination",true);if("true".equals(options.getString("capture","false")))captureSynthetic(result,"selection");
 }
 private void captureSynthetic(Bundle result,String name)throws Exception {
  phase="synthetic-capture";require(!engine.isActive()&&engine.serverPair==null&&engine.clientPair==null&&engine.pendingConfirmation==null,"capture only idle synthetic state");
  File directory=new File(target.getCacheDir(),"mimover-runtime-screenshots");require(directory.isDirectory()||directory.mkdirs(),"test screenshot directory available");File file=new File(directory,name+".png");
  runOnMainSync(()->{activity.getWindow().clearFlags(android.view.WindowManager.LayoutParams.FLAG_SECURE);try{for(String fieldName:new String[]{"originalQr","uiSsid"}){java.lang.reflect.Field field=UniversalActivity.class.getDeclaredField(fieldName);field.setAccessible(true);android.view.View view=(android.view.View)field.get(activity);if(view!=null)view.setVisibility(android.view.View.INVISIBLE);}maskDrafts(activity.getWindow().getDecorView());android.view.View view=activity.getWindow().getDecorView();Bitmap image=Bitmap.createBitmap(view.getWidth(),view.getHeight(),Bitmap.Config.ARGB_8888);view.draw(new android.graphics.Canvas(image));try(OutputStream out=new FileOutputStream(file)){if(!image.compress(Bitmap.CompressFormat.PNG,100,out))throw new IOException("CAPTURE");}finally{image.recycle();}}catch(Exception e){throw new RuntimeException(e);}});
  Uri export=DocumentsContract.createDocument(target.getContentResolver(),DocumentsContract.buildDocumentUriUsingTree(tree(),"root"),"image/png","synthetic-"+name+".png");try(InputStream in=new FileInputStream(file);OutputStream output=target.getContentResolver().openOutputStream(export,"w")){byte[] buffer=new byte[65536];int n;while((n=in.read(buffer))!=-1)output.write(buffer,0,n);}result.putString("captureDocumentId",DocumentsContract.getDocumentId(export));result.putBoolean("syntheticCaptureMasked",true);result.putString("captureName",name);int hold=Integer.parseInt(options.getString("hold_seconds","0"));for(int i=0;i<Math.min(hold,30);i++)Thread.sleep(1000);
  runOnMainSync(()->activity.getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAG_SECURE));
 }
 private void maskDrafts(android.view.View view){if(view instanceof android.widget.EditText)((android.widget.EditText)view).setText("");if(view instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)view;for(int i=0;i<group.getChildCount();i++)maskDrafts(group.getChildAt(i));}}
 private void entryOld(Bundle result)throws Exception {
  phase="original-old-entry";ActivityMonitor homeMonitor=addMonitor("in.chinatech.mimoverengine.EntryMainActivity",null,false);Intent launch=target.getPackageManager().getLaunchIntentForPackage(target.getPackageName());require(launch!=null,"modified APK has launcher");runOnMainSync(()->target.startActivity(launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP)));Activity home=homeMonitor.waitForActivityWithTimeout(10000);removeMonitor(homeMonitor);require(home!=null,"actual original home subclass opens");Thread.sleep(1500);android.view.View old=home.findViewById(HostR.id.btn_sender);require(old!=null,"actual old original View ID");result.putString("homeActivity",home.getClass().getName());result.putString("oldViewClass",old.getClass().getName());result.putBoolean("oldVisible",old.isShown());result.putBoolean("oldEnabled",old.isEnabled());result.putBoolean("oldHasClickListener",old.hasOnClickListeners());ActivityMonitor owned=addMonitor(UniversalActivity.class.getName(),null,false);boolean[] clicked={false};if(options.getString("mode").equals("entrytouch")){int[] xy=new int[2];runOnMainSync(()->old.getLocationOnScreen(xy));float x=xy[0]+old.getWidth()/2f,y=xy[1]+old.getHeight()/2f;result.putString("oldTouchBounds",xy[0]+","+xy[1]+","+old.getWidth()+","+old.getHeight());long now=SystemClock.uptimeMillis();android.view.MotionEvent down=android.view.MotionEvent.obtain(now,now,android.view.MotionEvent.ACTION_DOWN,x,y,0),up=android.view.MotionEvent.obtain(now,now+100,android.view.MotionEvent.ACTION_UP,x,y,0);down.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);up.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);try{require(getUiAutomation().injectInputEvent(down,true),"actual touch DOWN injected");require(getUiAutomation().injectInputEvent(up,true),"actual touch UP injected");}finally{down.recycle();up.recycle();}result.putBoolean("oldPhysicalInputInjected",true);}else{runOnMainSync(()->clicked[0]=old.performClick());result.putBoolean("oldPerformClick",clicked[0]);}Activity next=owned.waitForActivityWithTimeout(10000);removeMonitor(owned);require(next!=null,"old original input opens owned Guest");require(!next.getIntent().getBooleanExtra("receiving",true),"old original role is sender");result.putBoolean("actualOriginalOldEntry",true);
 }
 private void renderOriginal(String page){Runnable task=()->{try{java.lang.reflect.Method render=UniversalActivity.class.getDeclaredMethod("render",String.class);render.setAccessible(true);render.invoke(activity,page);}catch(Exception e){throw new RuntimeException(e);}};if(Looper.myLooper()==Looper.getMainLooper())task.run();else runOnMainSync(task);}
 private String originalText(int id){String[] text={null};runOnMainSync(()->{android.view.View view=activity.findViewById(id);if(view instanceof android.widget.TextView)text[0]=((android.widget.TextView)view).getText().toString();});return text[0];}
 private void assertOriginalFinished(boolean receiving,long count)throws Exception{int id=receiving?HostR.id.receiver_finish_title:HostR.id.sender_finish_title;waitFor(()->originalText(id)!=null,10000,"real original finish resource rendered");require(originalText(id).equals(activity.getString(receiving?R.string.receiver_complete:R.string.sender_complete,count)),"original finish title equals legal verified engine completion");}
 private void assertPendingOriginal()throws Exception{runOnMainSync(activity::changed);require(activity.findViewById(HostR.id.receiver_finish_title)==null,"missing or invalid FINISH cannot render original completion");require(engine.receiptProjection.category("files")==1,"saved receiver category is exactly one after replay");}
 private void uiProjection(Bundle result)throws Exception {
  phase="ui-count-projection";engine.resetDisplay();engine.store.clear();engine.store.add(Uri.parse("content://synthetic-runtime/ui-projection-1"),"files","synthetic-one.bin","application/octet-stream",0,true);engine.store.add(Uri.parse("content://synthetic-runtime/ui-projection-2"),"photos","synthetic-two.png","image/png",0,true);for(TransferStore.Row row:engine.page(null,0))engine.store.prepared(row,0,ProtocolCore.sha256(new byte[0]));engine.store.freeze();
  runOnMainSync(()->{activity.receiving=false;engine.status=R.string.preparing_progress;engine.statusArgs=new Object[]{137L,2L};renderOriginal(UniversalActivity.PROGRESS);activity.changed();});require(originalText(HostR.id.transfer_summary).equals(activity.getString(R.string.original_sent_files,0L,2L)),"preparation count cannot fake saved sender count");
  runOnMainSync(()->{engine.receiptProjection.acknowledged("synthetic-ack");engine.receiptProjection.acknowledged("synthetic-ack");engine.status=R.string.retrying;engine.statusArgs=new Object[]{2,3};activity.changed();});require(originalText(HostR.id.transfer_summary).equals(activity.getString(R.string.original_sent_files,1L,2L)),"retry and duplicate ACK cannot inflate original saved count");
  engine.store.clear();ProtocolCore.Item photo=new ProtocolCore.Item(ProtocolCore.token(16),"synthetic.png","image/png",0,ProtocolCore.sha256(new byte[0])),file=new ProtocolCore.Item(ProtocolCore.token(16),"synthetic.bin","application/octet-stream",0,ProtocolCore.sha256(new byte[0]));engine.receiptProjection.receivingPass();engine.receiptProjection.received(photo);engine.receiptProjection.received(file);engine.receiptProjection.received(file);
  runOnMainSync(()->{activity.receiving=true;engine.status=R.string.receiver_progress;engine.statusArgs=new Object[]{2L,100L};engine.expectedCount=100;engine.receivedCount=2;renderOriginal(UniversalActivity.PROGRESS);activity.changed();});require(engine.scannedCount()==0,"receiver has empty sender catalog");require(originalText(HostR.id.transfer_summary).equals(activity.getString(R.string.original_receiving_files,2L,100L)),"original receiver count separates expected from saved");
  waitFor(()->findText(activity.getWindow().getDecorView(),activity.getString(R.string.category_count,activity.getString(R.string.category_photos),1L))!=null,10000,"original photo group reads actual incoming projection");runOnMainSync(()->{try{android.view.View list=activity.findViewById(HostR.id.transfer_list);list.getClass().getMethod("scrollToPosition",int.class).invoke(list,6);}catch(Exception e){throw new RuntimeException(e);}});waitFor(()->findText(activity.getWindow().getDecorView(),activity.getString(R.string.category_count,activity.getString(R.string.category_files),1L))!=null,10000,"original file group reads dedup incoming projection");require(activity.findViewById(HostR.id.receiver_finish_title)==null,"expected count alone cannot render finish");
  runOnMainSync(()->{engine.status=R.string.receiver_complete_pending;engine.statusArgs=new Object[]{2L};activity.changed();});require(activity.findViewById(HostR.id.receiver_finish_title)==null,"pending final receipt cannot render finish");runOnMainSync(()->{engine.status=R.string.receiver_complete_unconfirmed;engine.statusArgs=new Object[]{2L};activity.changed();});require(activity.findViewById(HostR.id.receiver_finish_title)==null,"unconfirmed final receipt cannot render finish");engine.resetDisplay();result.putBoolean("originalUiNeverFakesCounts",true);result.putString("projectionScope","synthetic state injection validates rendering; independent pair/fault tests validate protocol transitions");
 }
 private void hotspot(Bundle result)throws Exception {
  phase="public-lohs";runOnMainSync(()->{engine.setDirectory(tree());engine.createHotspot();});waitFor(()->engine.serverPair!=null||engine.status==R.string.hotspot_failed||engine.status==R.string.permission_denied||engine.status==R.string.transfer_failed||engine.status==R.string.service_start_failed,40000,"public LOHS bounded callback");boolean generated=engine.serverPair!=null&&!engine.serverPair.ssid.isEmpty();result.putBoolean("actualPublicHotspotQr",generated);result.putInt("hotspotStatus",engine.status);result.putString("hotspotFailure",engine.wifi.lastFailure);require(generated,"actual public LOHS returns usable pairing");require(engine.serverPair.host.equals("gateway"),"hotspot requires no private MAC");Bitmap qr=QrCodec.encode(engine.serverPair.encode());try{require(QrCodec.decode(qr).equals(engine.serverPair.encode()),"actual LOHS QR bitmap roundtrip");}finally{qr.recycle();}runOnMainSync(engine::stop);waitFor(()->!engine.isActive(),10000,"public LOHS close");
 }
 private android.view.View clickableAncestor(android.view.View view){while(view!=null&&!view.hasOnClickListeners()){view=view.getParent() instanceof android.view.View?(android.view.View)view.getParent():null;}return view;}
 private void tapCenter(android.view.View view,String label,Bundle result)throws Exception{int[] xy=new int[2];runOnMainSync(()->view.getLocationOnScreen(xy));float x=xy[0]+view.getWidth()/2f,y=xy[1]+view.getHeight()/2f;result.putString(label+"Bounds",xy[0]+","+xy[1]+","+view.getWidth()+","+view.getHeight());long now=SystemClock.uptimeMillis();android.view.MotionEvent down=android.view.MotionEvent.obtain(now,now,android.view.MotionEvent.ACTION_DOWN,x,y,0),up=android.view.MotionEvent.obtain(now,now+100,android.view.MotionEvent.ACTION_UP,x,y,0);down.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);up.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);try{require(getUiAutomation().injectInputEvent(down,true),label+" actual DOWN");require(getUiAutomation().injectInputEvent(up,true),label+" actual UP");}finally{down.recycle();up.recycle();}}
 private void entryNew(Bundle result)throws Exception{
  phase="original-new-source-host";ActivityMonitor homeMonitor=addMonitor("in.chinatech.mimoverengine.EntryMainActivity",null,false);Intent launch=target.getPackageManager().getLaunchIntentForPackage(target.getPackageName());require(launch!=null,"modified APK launcher exists");runOnMainSync(()->target.startActivity(launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP)));Activity home=homeMonitor.waitForActivityWithTimeout(10000);removeMonitor(homeMonitor);require(home!=null,"original home opens for new role");Thread.sleep(1000);android.view.View newer=home.findViewById(HostR.id.btn_receiver);require(newer!=null&&newer.isShown()&&newer.isEnabled(),"original new role view available");ActivityMonitor sourceMonitor=addMonitor("com.miui.huanji.ui.SelectOldDeviceActivity",null,false);tapCenter(newer,"newTouch",result);Activity source=sourceMonitor.waitForActivityWithTimeout(10000);removeMonitor(sourceMonitor);require(source!=null,"real New touch opens exact original source-type Activity");require(source.getClass().getName().equals("com.miui.huanji.ui.SelectOldDeviceActivity"),"source page retains original controller and layout");Thread.sleep(500);android.view.View android=source.findViewById(HostR.id.select_android);require(android!=null&&android.isShown(),"real original Android source card");ActivityMonitor owned=addMonitor(UniversalActivity.class.getName(),null,false);tapCenter(android,"androidSourceTouch",result);activity=(UniversalActivity)owned.waitForActivityWithTimeout(10000);removeMonitor(owned);require(activity!=null&&activity.receiving,"real original source touch opens owned receiving role");require(activity.findViewById(HostR.id.host_hint_message)!=null,"owned Host uses actual original layout ID");engine=TransferEngine.get(target);runOnMainSync(engine::stop);waitFor(()->!engine.isActive(),10000,"new entry test stops only synthetic preparation");runOnMainSync(()->RestoreCoordinator.get(target).stop());waitFor(()->!RestoreCoordinator.get(target).isActive(),10000,"synthetic restore queue idle for screenshot");renderOriginal(UniversalActivity.HOST);captureSynthetic(result,"host-"+options.getString("language","default"));result.putBoolean("actualNewOriginalSourceHostTouch",true);result.putString("language",options.getString("language","default"));
 }
}
